# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# BRONZE LAYER INGESTION
# Generated by Shift-T Architect Agent
# Source: DimSupplier.py

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
# COMMAND ----------
# Title: DimSupplier.dtsx
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# JDBC connection details (use Databricks secrets)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-password")

# Parameter for supplierid threshold (replace with widget or parameter as needed)
supplierid_threshold = dbutils.widgets.get("supplierid_threshold")

source_query = f"""
SELECT supplierid, companyname, address, postalcode, phone, city, country
FROM Production.Suppliers
WHERE supplierid > {supplierid_threshold}
"""

# Read source data
source_df = (
    spark.read.format("jdbc")
    .option("url", db_url)
    .option("user", db_user)
    .option("password", db_password)
    .option("dbtable", f"({source_query}) as src")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups specified. Direct mapping.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "dbo.DimSupplier"
bk_cols = ["supplierid"]
sk_col = "SupplierKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
supplier_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    unknown_row = {
        "SupplierKey": -1,
        "supplierid": -1,
        "companyname": "Unknown",
        "address": "Unknown",
        "postalcode": "Unknown",
        "phone": "Unknown",
        "city": "Unknown",
        "country": "Unknown"
    }
    # Check if unknown exists
    if df.filter(col("SupplierKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = df.unionByName(unknown_df)
    return df

supplier_df = ensure_unknown_member(supplier_df)

# 4. Mandatory Type Casting (STRICT)
# Define target schema explicitly (as per platform rules)
supplier_df = (
    supplier_df
    .withColumn("SupplierKey", col("SupplierKey").cast("integer"))
    .withColumn("supplierid", col("supplierid").cast("integer"))
    .withColumn("companyname", col("companyname").cast("string"))
    .withColumn("address", col("address").cast("string"))
    .withColumn("postalcode", col("postalcode").cast("string"))
    .withColumn("phone", col("phone").cast("string"))
    .withColumn("city", col("city").cast("string"))
    .withColumn("country", col("country").cast("string"))
)

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge for idempotency
(
# [DISABLED_BY_ARCHITECT]     supplier_df.write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
# [DISABLED_BY_ARCHITECT]     .saveAsTable(target_table_name)
)

# Apply Bronze Standard
if 'df_source' not in locals() and 'df' in locals():
    df_source = df

df_bronze = add_ingestion_metadata(df_source)

# Write to Delta
target_table = f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimSupplier"
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)
