# COMMAND ----------
# Title: DimEmployee.dtsx
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Source (HR.Employees via JDBC)
# Use widgets or parameters for connection info
jdbc_url = dbutils.widgets.get("hr_jdbc_url")
jdbc_user = dbutils.secrets.get("scope", "hr_user")
jdbc_password = dbutils.secrets.get("scope", "hr_password")

query = "SELECT empid, (firstname + ' ' + lastname) as fullname, title, city, country, address, phone FROM HR.Employees WHERE empid > ?"
param_empid_min = int(dbutils.widgets.get("empid_min", "0"))
# Parameterize query
sql_query = query.replace("?", str(param_empid_min))

# Read from JDBC

df_source = spark.read.format("jdbc") \
    .option("url", jdbc_url) \
    .option("user", jdbc_user) \
    .option("password", jdbc_password) \
    .option("dbtable", f"({sql_query}) as src") \
    .load()

# 3. Transformations (Apply Logic)
# No lookups in this task. Direct mapping.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimEmployee"
bk_cols = ["empid"]
sk_col = "EmployeeKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
from pyspark.sql import DataFrame
if df_existing.count() > 0:
    df_with_sk = df_existing.unionByName(df_new)
else:
    df_with_sk = df_new

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown row
    unknown_row = {
        sk_col: -1,
        "empid": -1,
        "fullname": "Unknown",
        "title": "Unknown",
        "city": "Unknown",
        "country": "Unknown",
        "address": "Unknown",
        "phone": "Unknown"
    }
    # Check if unknown member exists
    if df.filter(col(sk_col) == -1).count() == 0:
        df_unknown = spark.createDataFrame([unknown_row], df.schema)
        df = df.unionByName(df_unknown)
    return df

df_final = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# Define target schema columns and types explicitly
# (Assuming the following schema for DimEmployee)
target_schema = [
    {"name": "EmployeeKey", "type": "INTEGER"},
    {"name": "empid", "type": "INTEGER"},
    {"name": "fullname", "type": "STRING"},
    {"name": "title", "type": "STRING"},
    {"name": "city", "type": "STRING"},
    {"name": "country", "type": "STRING"},
    {"name": "address", "type": "STRING"},
    {"name": "phone", "type": "STRING"}
]
for field in target_schema:
    col_name = field["name"]
    target_type = field["type"]
    if col_name in df_final.columns:
        df_final = df_final.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge into DimEmployee table
(
    df_final
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(target_table_name)
)

# 6. Optimization (Z-ORDER)
# Z-ORDER on empid for query performance
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (empid)")
