# COMMAND ----------
# Title: DimEmployee.dtsx
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Source (HR.Employees via JDBC)
# Use widgets or parameters for connection info
jdbc_url = dbutils.widgets.get("hr_jdbc_url")
jdbc_user = dbutils.secrets.get("scope", "hr_user")
jdbc_password = dbutils.secrets.get("scope", "hr_password")

query = "SELECT empid,(firstname+' '+ lastname) as fullname,title,city,country,address,phone FROM HR.Employees where empid > ?"
# For migration, parameterize empid > ? as needed. Here, we set to 0 for full load.
query = query.replace('?', '0')

# Read source data
source_df = (
    spark.read.format("jdbc")
    .option("url", jdbc_url)
    .option("dbtable", f"({query}) as src")
    .option("user", jdbc_user)
    .option("password", jdbc_password)
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups in this task. Business Key is empid.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimEmployee"
bk_cols = ["empid"]
sk_col = "EmployeeKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
staged_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define unknown row schema
    unknown_row = {
        "EmployeeKey": -1,
        "empid": -1,
        "fullname": "Unknown",
        "title": "Unknown",
        "city": "Unknown",
        "country": "Unknown",
        "address": "Unknown",
        "phone": "Unknown"
    }
    # Check if unknown exists
    if df.filter(col("EmployeeKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row], df.schema)
        df = df.unionByName(unknown_df)
    return df

staged_df = ensure_unknown_member(staged_df)

# 4. Mandatory Type Casting (STRICT)
# Define target schema explicitly (as per platform rules)
target_schema = [
    {"name": "EmployeeKey", "type": "INTEGER"},
    {"name": "empid", "type": "INTEGER"},
    {"name": "fullname", "type": "STRING"},
    {"name": "title", "type": "STRING"},
    {"name": "city", "type": "STRING"},
    {"name": "country", "type": "STRING"},
    {"name": "address", "type": "STRING"},
    {"name": "phone", "type": "STRING"}
]

for field in target_schema:
    col_name = field["name"]
    target_type = field["type"]
    if col_name in staged_df.columns:
        staged_df = staged_df.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge for idempotency
(
    staged_df
    .select([f["name"] for f in target_schema])
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(target_table_name)
)

# Optional: Z-ORDER optimization (if supported)
# spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (empid)")
