# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# BRONZE LAYER INGESTION
# Generated by Shift-T Architect Agent
# Source: DimShipper.py

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
# COMMAND ----------
# Title: DimShipper.dtsx Migration
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Source (Bronze)
# Extract parameter for shipperid threshold (use widget or parameterization)
shipperid_threshold = int(dbutils.widgets.get('shipperid_threshold'))  # Must be set by pipeline

# Secure JDBC connection setup
jdbc_url = dbutils.secrets.get('jdbc_scope', 'sales_db_url')
jdbc_user = dbutils.secrets.get('jdbc_scope', 'sales_db_user')
jdbc_password = dbutils.secrets.get('jdbc_scope', 'sales_db_password')

source_query = f"""
SELECT * FROM Sales.Shippers WHERE shipperid > {shipperid_threshold}
"""

# Read source table via JDBC (explicit, secure)
df_source = (
    spark.read.format('jdbc')
    .option('url', jdbc_url)
    .option('user', jdbc_user)
    .option('password', jdbc_password)
    .option('dbtable', f"({source_query}) as src")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups or complex logic per task definition

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimShipper"
bk_cols = ["shipperid"]  # Business Key
sk_col = "ShipperKey"    # Surrogate Key (assumed name)

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
from pyspark.sql import DataFrame
if df_existing.count() > 0:
    df_with_sk = df_existing.unionByName(df_new)
else:
    df_with_sk = df_new

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df: DataFrame) -> DataFrame:
    # Define the schema for the unknown member
    unknown_row = {
        sk_col: -1,
        "shipperid": -1,
        "companyname": "Unknown",
        "phone": "Unknown"
    }
    # Check if unknown member exists
    if df.filter(col(sk_col) == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = df.unionByName(unknown_df)
    return df

df_final = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# Target schema (assumed, since not provided in JSON)
target_schema = [
    {"name": "ShipperKey", "type": "INTEGER"},
    {"name": "shipperid", "type": "INTEGER"},
    {"name": "companyname", "type": "STRING"},
    {"name": "phone", "type": "STRING"}
]
for field in target_schema:
    col_name = field["name"]
    target_type = field["type"]
    if col_name in df_final.columns:
        df_final = df_final.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge for idempotency
(
# [DISABLED_BY_ARCHITECT]     df_final.write.format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
# [DISABLED_BY_ARCHITECT]     .saveAsTable(target_table_name)
)

# 6. Optimization (Z-ORDER)
# Z-ORDER on high-cardinality business key
# [DISABLED_BY_ARCHITECT] spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (shipperid)")

# Apply Bronze Standard
if 'df_source' not in locals() and 'df' in locals():
    df_source = df

df_bronze = add_ingestion_metadata(df_source)

# Write to Delta
target_table = f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimShipper"
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)
