from pathlib import Path
from typing import Dict, Any, List
from .base_cartridge import Cartridge

class DbtCartridge(Cartridge):
    """
    Generates dbt-compatible SQL for Medallion Architecture.
    Target Stack: Snowflake / Databricks SQL / Redshift / Postgres.
    """

    def get_file_extension(self) -> str:
        return ".sql"

    def generate_scaffolding(self) -> Dict[str, str]:
        """Generates dbt_project.yml and base schema.yml"""
        project_name = f"migration_{self.project_id}"
        
        dbt_project_yml = f"""
name: '{project_name}'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  {project_name}:
    Bronze:
      +materialized: view
      +schema: bronze
    Silver:
      +materialized: table
      +file_format: delta
      +schema: silver
    Gold:
      +materialized: table
      +schema: gold
"""
        # We also need a sources.yml to define the "Bronze" source inputs if we treat Bronze as Raw.
        # But here valid Architecture is:
        # Bronze = Staging (View on Raw)
        # Silver = Intermediate (Clean Table)
        # Gold = Marts (Business Table)
        
        # We will generate a generic sources.yml in Bronze
        sources_yml = """
version: 2

sources:
  - name: legacy_source
    schema: raw_ingested
    tables:
      # Tables will be dynamically added or assumed
      - name: source_table
"""
        return {
            "dbt_project.yml": dbt_project_yml,
            "Bronze/sources.yml": sources_yml
        }

    def generate_bronze(self, table_metadata: Dict[str, Any]) -> str:
        """
        In dbt, Bronze is typically the 'Staging' layer.
        It reads from a 'source' (Raw) and does light casting/renaming.
        Since we don't have the raw DDL, we assume a source exists.
        """
        source_path = Path(table_metadata.get("source_path", "unknown"))
        source_table_name = source_path.stem
        
        return f"""-- BRONZE LAYER (Staging)
-- Generated by Shift-T Architect Agent
-- Source: {source_path.name}

with source as (
    select * from {{{{ source('legacy_source', '{source_table_name}') }}}}
),

renamed as (
    select
        *,
        current_timestamp() as _ingested_at
    from source
)

select * from renamed
"""

    def generate_silver(self, table_metadata: Dict[str, Any]) -> str:
        """
        In dbt, Silver is 'Intermediate'.
        Reads from Bronze (Staging).
        """
        source_path = Path(table_metadata.get("source_path", "unknown"))
        # We need to know what the Bronze model name is. 
        # By default in ArchitectService we name it "{filename}_bronze".
        bronze_model_name = f"{source_path.stem}_bronze"
        
        pk_columns = table_metadata.get("pk_columns", ["id"])
        pk_str = ", ".join(pk_columns)

        return f"""-- SILVER LAYER (Intermediate/Cleansed)
-- Generated by Shift-T Architect Agent
-- Reference: {bronze_model_name}

{{{{
  config(
    materialized='incremental',
    unique_key=[{', '.join([f"'{c}'" for c in pk_columns])}]
  )
}}}}

with bronze as (
    select * from {{{{ ref('{bronze_model_name}') }}}}
),

deduplicated as (
    -- Simple deduplication via distinct or window function
    select distinct * from bronze
)

select * from deduplicated

-- Incremental logic
{{% if is_incremental() %}}
  -- this filter will only be applied on an incremental run
  where _ingested_at > (select max(_ingested_at) from {{{{ this }}}})
{{% endif %}}
"""

    def generate_gold(self, table_metadata: Dict[str, Any]) -> str:
        """
        In dbt, Gold is 'Marts'.
        Reads from Silver (Intermediate).
        """
        source_path = Path(table_metadata.get("source_path", "unknown"))
        silver_prefix = self.registry.get("naming", {}).get("silver_prefix", "stg_")
        # In ArchitectService we name the file "{silver_prefix}{clean_name}"
        silver_model_name = f"{silver_prefix}{source_path.stem}"
        
        table_type = table_metadata.get("table_type", "DIMENSION")

        return f"""-- GOLD LAYER (Marts/Business)
-- Type: {table_type}
-- Generated by Shift-T Architect Agent

with silver as (
    select * from {{{{ ref('{silver_model_name}') }}}}
)

select * from silver
"""
