from pathlib import Path
from typing import Dict, Any, List
from .base_cartridge import Cartridge

class PySparkCartridge(Cartridge):
    """
    Generates PySpark/Delta Lake code for Medallion Architecture.
    """

    def get_file_extension(self) -> str:
        return ".py"

    def generate_scaffolding(self) -> Dict[str, str]:
        """Generates config.py and utils.py"""
        naming = self.registry.get("naming", {})
        paths = self.registry.get("paths", {})
        
        s_bronze = naming.get("bronze_schema", "bronze_raw")
        s_silver = naming.get("silver_schema", "silver_curated")
        s_gold = naming.get("gold_schema", "gold_business")
        
        p_bronze = paths.get("bronze_path", "/mnt/datalake/bronze")
        p_silver = paths.get("silver_path", "/mnt/datalake/silver")
        p_gold = paths.get("gold_path", "/mnt/datalake/gold")
        
        config_content = f"""# Medallion Architecture Configuration
import os

class Config:
    CATALOG = "main_catalog"
    
    # Schemas
    SCHEMA_BRONZE = "{s_bronze}"
    SCHEMA_SILVER = "{s_silver}"
    SCHEMA_GOLD = "{s_gold}"
    
    # Paths (if using external locations)
    PATH_BRONZE = "{p_bronze}"
    PATH_SILVER = "{p_silver}"
    PATH_GOLD = "{p_gold}"
    
    @staticmethod
    def get_jdbc_url(secret_scope, secret_key):
        return dbutils.secrets.get(scope=secret_scope, key=secret_key)
"""

        utils_content = """# Common Utility Functions
from pyspark.sql import DataFrame
from pyspark.sql.functions import current_timestamp, lit

def add_ingestion_metadata(df: DataFrame) -> DataFrame:
    \"\"\"Adds audit columns: _ingestion_timestamp, _source_system\"\"\"
    return df.withColumn("_ingestion_timestamp", current_timestamp()) \\
             .withColumn("_source_system", lit("SSIS_MIGRATION"))

def quarantine_bad_records(df, rules, quarantine_table):
    # Simplified quarantine logic
    pass
"""
        return {
            "config.py": config_content,
            "utils.py": utils_content
        }

    def generate_bronze(self, table_metadata: Dict[str, Any]) -> str:
        source_path = Path(table_metadata.get("source_path", "unknown_source.py"))
        original_code = table_metadata.get("original_code", "")
        
        # Disable original writes
        processed_lines = []
        for line in original_code.splitlines():
            if any(x in line for x in [".write", ".save", "saveAsTable", "display(", "OPTIMIZE", "VACUUM"]):
                processed_lines.append(f"# [DISABLED_BY_ARCHITECT] {line}")
            else:
                processed_lines.append(line)
        original_code_safe = "\n".join(processed_lines)
        
        return f"""# BRONZE LAYER INGESTION
# Generated by Legacy2Lake Architect Agent
# Source: {source_path.name}

from config import Config
from utils import add_ingestion_metadata
from delta.tables import *
from pyspark.sql.functions import *
# [ORIGINAL READ LOGIC (Adapted)]
{original_code_safe}

# Apply Bronze Standard
if 'df_source' not in locals() and 'df' in locals():
    df_source = df
df_bronze = add_ingestion_metadata(df_source if 'df_source' in locals() else df)

# Write to Delta with schema enforcement and evolution support
# mergeSchema allows new columns, dataChange tracks CDC
target_table = f"{{Config.CATALOG}}.{{Config.SCHEMA_BRONZE}}.{source_path.stem}"
df_bronze.write.format("delta") \\
    .mode("append") \\
    .option("mergeSchema", "true") \\
    .option("dataChange", "true") \\
    .saveAsTable(target_table)

# Log schema for debugging/auditing
print(f"Ingested to Bronze: {{target_table}}")
print(f"Schema: {{df_bronze.schema.simpleString()}}")
"""

    def generate_silver(self, table_metadata: Dict[str, Any]) -> str:
        source_path = Path(table_metadata.get("source_path", "unknown.py"))
        output_table_name = table_metadata.get("output_table_name", source_path.stem)
        
        # Validate and normalize PK columns
        pk_columns = self._validate_and_normalize_pk(table_metadata.get("pk_columns", []))
        
        merge_condition = " AND ".join([f"target.{pk} = source.{pk}" for pk in pk_columns])
        pk_display = ", ".join(pk_columns)
        
        silver_prefix = self.registry.get("naming", {}).get("silver_prefix", "stg_")

        return f"""# SILVER LAYER TRANSFORMATION
# Generated by Legacy2Lake Architect Agent
# Source: {source_path.name}
# Primary Key(s): {pk_display}

from config import Config
from delta.tables import *
from pyspark.sql.functions import *

# Read Bronze
df_bronze = spark.read.table(f"{{Config.CATALOG}}.{{Config.SCHEMA_BRONZE}}.{source_path.stem}")

# Deduplicate
df_clean = df_bronze.dropDuplicates({pk_columns})

# SCD Type 2 Merge (Upsert)
target_table_name = f"{{Config.CATALOG}}.{{Config.SCHEMA_SILVER}}.{output_table_name}"

# Check if table exists AND we have a valid custom PK (not just default 'id')
table_exists = spark.catalog.tableExists(target_table_name)
has_custom_pk = pk_columns[0] != "id"

if table_exists and has_custom_pk:
    target_table = DeltaTable.forName(spark, target_table_name)
    target_table.alias("target").merge(
        df_clean.alias("source"),
        "{merge_condition}"
    ).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
else:
    # First load or using default PK - use overwrite for simplicity
    df_clean.write.format("delta").mode("overwrite").saveAsTable(target_table_name)
"""

    def generate_gold(self, table_metadata: Dict[str, Any]) -> str:
        source_path = Path(table_metadata.get("source_path", "unknown.py"))
        output_table_name = table_metadata.get("output_table_name", source_path.stem)
        table_type = table_metadata.get("table_type", "DIMENSION")
        
        logic_comment = "# Gold Logic: Business-ready projection."
        select_logic = "df_silver.select(\"*\")"
        if table_type == "FACT":
            logic_comment = "# Gold Logic: Fact table aggregation / Semantic measures."
            select_logic = "df_silver.select(\"*\", (col(\"qty\") * col(\"unitprice\")).alias(\"total_amount\"))"

        return f"""# GOLD LAYER - BUSINESS VIEW ({table_type})
# Generated by Legacy2Lake Architect Agent
# Source: {source_path.name}

from config import Config
from pyspark.sql.functions import *

target_silver_table = f"{{Config.CATALOG}}.{{Config.SCHEMA_SILVER}}.{source_path.stem}" 
df_silver = spark.read.table(target_silver_table)

{logic_comment}
df_gold = {select_logic}

# Write to Gold
target_gold_table = f"{{Config.CATALOG}}.{{Config.SCHEMA_GOLD}}.{output_table_name}"
df_gold.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_gold_table)

print(f"Gold Layer updated: {{target_gold_table}}")
"""

    def generate_orchestration(self, tables_metadata: List[Dict[str, Any]]) -> str:
        """Generates an Airflow DAG for Databricks/PySpark orchestration."""
        project_id = self.project_id
        
        dag_content = f"""from airflow import DAG
from airflow.providers.databricks.operators.databricks import DatabricksRunNowOperator
from datetime import datetime, timedelta

default_args = {{
    'owner': 'utm_architect',
    'depends_on_past': False,
    'email_on_failure': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}}

with DAG(
    'dag_databricks_{project_id}_orchestration',
    default_args=default_args,
    description='Medallion Orchestration for Databricks ({project_id})',
    schedule_interval=timedelta(days=1),
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['utm', 'databricks', 'pyspark'],
) as dag:

"""
        for table in tables_metadata:
            name = table['table_name']
            
            # Bronze Job - Use project-based task naming
            task_bronze_name = f"task_{name}_bronze"
            dag_content += f"""
    # Orchestration for {name} - Bronze Layer
    {task_bronze_name} = DatabricksSubmitRunOperator(
        task_id='{task_bronze_name}',
        databricks_conn_id='databricks_default',
        new_cluster={{
            "spark_version": "13.3.x-scala2.12",
            "node_type_id": "Standard_DS3_v2",
            "num_workers": 2,
        }},
        notebook_task={{
            "notebook_path": f"/Users/airflow@{project_id}.com/Bronze/{name}_bronze",
        }},
        timeout_seconds=3600,
    )
"""
            # Silver Job
            task_silver_name = f"task_{name}_silver"
            dag_content += f"""
    # Orchestration for {name} - Silver Layer
    {task_silver_name} = DatabricksSubmitRunOperator(
        task_id='{task_silver_name}',
        databricks_conn_id='databricks_default',
        new_cluster={{
            "spark_version": "13.3.x-scala2.12",
            "node_type_id": "Standard_DS3_v2",
            "num_workers": 2,
        }},
        notebook_task={{
            "notebook_path": f"/Users/airflow@{project_id}.com/Silver/{name}_silver",
        }},
        timeout_seconds=3600,
    )
"""
            # Gold Job
            task_gold_name = f"task_{name}_gold"
            dag_content += f"""
    # Orchestration for {name} - Gold Layer
    {task_gold_name} = DatabricksSubmitRunOperator(
        task_id='{task_gold_name}',
        databricks_conn_id='databricks_default',
        new_cluster={{
            "spark_version": "13.3.x-scala2.12",
            "node_type_id": "Standard_DS3_v2",
            "num_workers": 2,
        }},
        notebook_task={{
            "notebook_path": f"/Users/airflow@{project_id}.com/Gold/{name}_gold",
        }},
        timeout_seconds=3600,
    )
"""
            # Task Dependencies
            dag_content += f"""
    {task_bronze_name} >> {task_silver_name} >> {task_gold_name}
"""
        return dag_content

    def generate_bronze_sql(self, table_metadata: Dict[str, Any]) -> str:
        source_path = Path(table_metadata.get("source_path", "unknown_source.py"))
        return f"""-- BRONZE LAYER (ANSI SQL)
-- Source: {source_path.name}
-- Logic: Create or replace raw table representing the source data.

CREATE OR REPLACE TABLE bronze_{source_path.stem}
USING DELTA
AS SELECT *, current_timestamp() as _ingestion_timestamp
FROM {table_metadata.get("source_path", "source_table")};
"""

    def generate_silver_sql(self, table_metadata: Dict[str, Any]) -> str:
        output_table_name = table_metadata.get("output_table_name", "silver_table")
        pk_columns = table_metadata.get("pk_columns", ["id"])
        merge_condition = " AND ".join([f"target.{pk} = source.{pk}" for pk in pk_columns])
        
        return f"""-- SILVER LAYER (ANSI SQL)
-- Target: {output_table_name}
-- Logic: Upsert from Bronze to Silver with deduplication.

MERGE INTO silver_{output_table_name} AS target
USING (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY {", ".join(pk_columns)} ORDER BY _ingestion_timestamp DESC) as _rn
        FROM bronze_{output_table_name.replace("stg_", "")}
    ) WHERE _rn = 1
) AS source
ON {merge_condition}
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *;
"""

    def generate_gold_sql(self, table_metadata: Dict[str, Any]) -> str:
        output_table_name = table_metadata.get("output_table_name", "gold_table")
        table_type = table_metadata.get("table_type", "DIMENSION")
        
        return f"""-- GOLD LAYER (ANSI SQL)
-- Target: {output_table_name} ({table_type})
-- Logic: Business view with optional calculated measures.

CREATE OR REPLACE VIEW gold_{output_table_name}
AS
SELECT 
    * 
    {', (qty * unitprice) AS total_amount' if table_type == 'FACT' else ''}
FROM silver_{output_table_name.replace("dim_", "stg_").replace("fact_", "stg_")};
"""

    def get_rules(self, node_data: Dict[str, Any]) -> str:
        """
        Returns specific architectural rules for the LLM based on source tech.
        """
        # 1. Try Dynamic Rules from DB (via BaseCartridge)
        db_rules = super().get_rules(node_data)
        if db_rules:
            return db_rules

        # 2. Fallback to Legacy Hardcoded Rules (for backward compatibility)
        source_tech = str(node_data.get("source_tech", "mssql")).lower()
        
        base_rules = """
- USE PYSPARK DATAFRAME API PREFERABLY (Avoid hardcoded SQL unless complex).
- ENFORCE SCHEMA ON READ.
- USE DELTA FORMAT FOR ALL TABLES.
- [CRITICAL] ALWAYS USE 'MERGE INTO' (DeltaTable.merge) INSTEAD OF .mode("overwrite"), EVEN IF INPUT SAYS "FULL_OVERWRITE".
- [CRITICAL] WRAP LOGIC IN A FUNCTION `def execute_task(spark, config):` AND CALL IT AT THE END.
- [CRITICAL] EXPLICIT TYPE CASTING: YOU MUST EXPLICITLY CAST EVERY COLUMN TO ITS TARGET TYPE (e.g., `.cast("string")`, `.cast("decimal(18,2)")`) BEFORE WRITING. DO NOT RELY ON INFERENCE.
- [CRITICAL] DATA INTEGRITY: USE `COALESCE(col, F.lit(<default>))` FOR JOIN KEYS. Literal values MUST be wrapped in `F.lit()`.
- [CRITICAL] MANDATORY LOGGING: Log row counts BEFORE and AFTER transformation and load using `print(f"Rows processed: {count}")`.
- [CRITICAL] NO HARDCODED PATHS: NEVER hardcode paths like `/mnt/delta/`. Use ONLY `config['bronze_path']`, `config['silver_path']` etc.
- [STRUCTURE] ORCHESTRATION: For orchestration scripts (e.g., run_all), call other notebook functions or trigger jobs.
- [STRUCTURE] SEPARATION: Use comments to mark `# [EXTRACT]`, `# [TRANSFORM]`, and `# [LOAD]` sections.
- [OPTIMIZATION] ADD COMMENTS for needed `broadcast()` hints on small tables and `OPTIMIZE/ZORDER` recommendations.
- ADD 'L2L MODERNIZATION TRACE' HEADER EXACTLY AS FOLLOWS:
# L2L MODERNIZATION TRACE
# Source: <Original Asset Name>
# Component: PySpark Notebook
# Logic: <Brief Description of Transformation>
# Generated At: <Current ISO Timestamp>
"""
        if "oracle" in source_tech:
            return base_rules + """
- [ORACLE SPECIFIC] HANDLE NUMBER(38,0) AS DECIMAL/LONG, NOT INTEGER.
- [ORACLE SPECIFIC] CONVERT TO_DATE/TO_CHAR LOGIC TO SPARK DATE_FORMAT.
- [ORACLE SPECIFIC] HANDLE ROWNUM LOGIC WITH WINDOW FUNCTIONS (row_number()).
- [ORACLE SPECIFIC] NVL SHOULD BE CONVERTED TO COALESCE.
"""
        elif "mssql" in source_tech or "sql" in source_tech:
            return base_rules + """
- [MSSQL SPECIFIC] CONVERT ISNULL TO COALESCE.
- [MSSQL SPECIFIC] HANDLE SQUARE BRACKETS [] IN COLUMN NAMES.
- [MSSQL SPECIFIC] CONVERT TOP N TO LIMIT N.
"""
        return base_rules
