# ===============================================================================
# GOLD LAYER - BUSINESS VIEW (SNOWFLAKE)
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: {source_table}
# Target: GOLD_BUSINESS.{target_table}
# Table Type: {DIMENSION|FACT}
# Generated: {timestamp}
# ===============================================================================

import snowflake.snowpark as snowpark
from snowflake.snowpark import Session
import snowflake.snowpark.functions as F
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def main(session: Session) -> str:
    """
    Gold layer business view creation.
    
    Args:
        session: Snowpark Session
    
    Returns:
        str: Status message
    """
    
    # CONFIGURATION
    SCHEMA_SILVER = "SILVER_CURATED"
    SCHEMA_GOLD = "GOLD_BUSINESS"
    # You must set these variables before running
    SOURCE_TABLE = "REPLACE_WITH_SILVER_TABLE".upper()
    TARGET_TABLE = "REPLACE_WITH_GOLD_TABLE".upper()
    TABLE_TYPE = "FACT"  # Change to DIMENSION if this is for a dimension
    
    try:
        logger.info(f"Starting Gold layer for {TARGET_TABLE}")
        
        # READ SILVER
        silver_table = f"{SCHEMA_SILVER}.{SOURCE_TABLE}"
        df_silver = session.table(silver_table)
        
        logger.info(f"Read {df_silver.count()} records from Silver")
        
        # APPLY BUSINESS LOGIC
        if TABLE_TYPE == "DIMENSION":
            # Dimension: Business-friendly projections
            df_gold = df_silver.select(
                F.col("CUSTOMER_ID").alias("CUSTOMER_KEY"),
                F.col("CUSTOMER_NAME"),
                F.col("EMAIL"),
                F.col("COUNTRY"),
                F.when(F.col("STATUS") == F.lit("A"), F.lit("Active"))
                 .otherwise(F.lit("Inactive")).alias("STATUS_LABEL"),
                F.col("_INGESTION_TIMESTAMP").alias("LAST_UPDATED")
            )
        
        elif TABLE_TYPE == "FACT":
            # Fact: Computed measures (example for Sales Orders)
            df_gold = df_silver.select(
                F.col("ORDER_ID").alias("ORDER_KEY"),
                F.col("CUSTOMER_ID").alias("CUSTOMER_KEY"),
                F.col("PRODUCT_ID").alias("PRODUCT_KEY"),
                F.col("ORDER_DATE").alias("DATE_KEY"),
                F.col("QUANTITY"),
                F.col("UNIT_PRICE"),
                (F.col("QUANTITY") * F.col("UNIT_PRICE")).alias("TOTAL_AMOUNT"),
                ((F.col("QUANTITY") * F.col("UNIT_PRICE")) * F.col("DISCOUNT_PCT")).alias("DISCOUNT_AMOUNT"),
                F.current_timestamp().alias("PROCESSED_TIMESTAMP")
            )
        else:
            df_gold = df_silver.select("*")
        
        logger.info(f"Applied {TABLE_TYPE} business logic")
        
        # VALIDATE
        record_count = df_gold.count()
        if record_count == 0:
            raise ValueError(f"No records for Gold layer: {TARGET_TABLE}")
        
        logger.info(f"Validated: {record_count} records")
        
        # WRITE TO GOLD
        target_gold_table = f"{SCHEMA_GOLD}.{TARGET_TABLE}"
        df_gold.write \
            .mode("overwrite") \
            .save_as_table(target_gold_table)
        
        success_msg = f"\u2705 Gold layer updated: {target_gold_table} ({record_count} records)"
        logger.info(success_msg)
        
        return success_msg
    
    except Exception as e:
        error_msg = f"\u274c Gold layer failed: {str(e)}"
        logger.error(error_msg)
        raise Exception(error_msg)
    
    finally:
        logger.info("Gold layer process completed")

if __name__ == "__main__":
    session = snowpark.Session.builder.getOrCreate()
    result = main(session)
    print(result)
