{# =========================================================================== #}
{# SILVER LAYER (INTERMEDIATE / CLEANSED)                                     #}
{# =========================================================================== #}
{# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)            #}
{# Source: bronze.stg_customers                                             #}
{# Target: silver.int_customers                                             #}
{# Primary Keys: customer_id                                                #}
{# Generated: 2026-02-10                                                    #}
{# =========================================================================== #}

{{
  config(
    materialized='incremental',
    unique_key='customer_id',
    schema='silver'
  )
}}

with bronze as (
    select * from {{ ref('stg_customers') }}
    
    {% if is_incremental() %}
    where _ingested_at > (select max(_ingested_at) from {{ this }})
    {% endif %}
),

deduplicated as (
    select * from (
        select 
            *,
            row_number() over (
                partition by customer_id
                order by _ingested_at desc
            ) as _row_num
        from bronze
    )
    where _row_num = 1
),

cleansed as (
    select *
    from deduplicated
    where customer_id is not null
)

select * from cleansed
