# ==============================================================================
# BRONZE LAYER INGESTION
# ==============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: (REPLACE_WITH_SOURCE_FILE_NAME_OR_PATH)
# Target: main_catalog.bronze_raw.customers
# Generated: 2026-02-10T00:00:00Z
# ==============================================================================

# 1. IMPORTS
from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    current_timestamp, 
    current_date, 
    input_file_name, 
    lit,
    col
)
from delta.tables import DeltaTable
import logging

# 2. LOGGING SETUP
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# 3. SPARK SESSION (if not already available)
# Note: In Databricks/EMR, spark is already available
spark = SparkSession.builder \
    .appName("Bronze_Ingestion_customers") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .getOrCreate()

# 4. CONFIGURATION
CATALOG = "main_catalog"
SCHEMA_BRONZE = "bronze_raw"
SOURCE_SYSTEM = "SSIS_MIGRATION"  # Adjust as needed
TABLE_NAME = "customers"

try:
    logger.info(f"Starting Bronze ingestion for {TABLE_NAME}")
    
    # 5. READ SOURCE DATA
    # Please adapt the following line to the actual source format and path
    df_source = spark.read \
        .format("csv") \
        .option("header", "true") \
        .option("inferSchema", "true") \
        .load("s3://raw-data/customers/2026-02-10/customers.csv")
    
    logger.info(f"Read {df_source.count()} records from source")
    
    # 6. ADD METADATA COLUMNS (MANDATORY)
    df_bronze = df_source \
        .withColumn("_ingestion_timestamp", current_timestamp()) \
        .withColumn("_ingestion_date", current_date()) \
        .withColumn("_source_file", input_file_name()) \
        .withColumn("_source_system", lit(SOURCE_SYSTEM))
    
    # 7. DATA VALIDATION
    record_count = df_bronze.count()
    assert record_count > 0, f"No records to ingest for {TABLE_NAME}"
    logger.info(f"Validated: {record_count} records ready for ingestion")
    
    # 8. WRITE TO DELTA LAKE
    target_table = f"{CATALOG}.{SCHEMA_BRONZE}.{TABLE_NAME}"
    
    df_bronze.write \
        .format("delta") \
        .mode("append") \
        .option("mergeSchema", "true") \
        .option("dataChange", "true") \
        .partitionBy("_ingestion_date") \
        .saveAsTable(target_table)
    
    # 9. SUCCESS LOGGING
    logger.info(f"✅ Successfully ingested to Bronze: {target_table}")
    logger.info(f"Schema: {df_bronze.schema.simpleString()}")
    logger.info(f"Partition: _ingestion_date")
    
except Exception as e:
    logger.error(f"❌ Bronze ingestion failed for {TABLE_NAME}: {str(e)}")
    raise
finally:
    logger.info("Bronze ingestion process completed")
