# ===============================================================================
# SILVER LAYER TRANSFORMATION (SNOWFLAKE)
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: BRONZE_RAW.CUSTOMERS
# Target: SILVER_CURATED.CUSTOMERS
# Primary Keys: ['CUSTOMER_KEY']
# Generated: 2026-02-10
# ===============================================================================

import snowflake.snowpark as snowpark
from snowflake.snowpark import Session
import snowflake.snowpark.functions as F
from snowflake.snowpark.table import Table
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def main(session: Session) -> str:
    """
    Silver layer transformation with deduplication and MERGE.
    
    Args:
        session: Snowpark Session
    
    Returns:
        str: Status message
    """
    
    # CONFIGURATION
    SCHEMA_BRONZE = "BRONZE_RAW"
    SCHEMA_SILVER = "SILVER_CURATED"
    TABLE_NAME = "CUSTOMERS"
    PRIMARY_KEYS = ["CUSTOMER_KEY"]
    
    try:
        logger.info(f"Starting Silver transformation for {TABLE_NAME}")
        
        # READ BRONZE
        bronze_table = f"{SCHEMA_BRONZE}.{TABLE_NAME}"
        df_bronze = session.table(bronze_table)
        
        logger.info(f"Read {df_bronze.count()} records from Bronze")
        
        # DATA QUALITY: Filter NULL Primary Keys
        for pk in PRIMARY_KEYS:
            df_bronze = df_bronze.filter(F.col(pk).is_not_null())
        
        # DEDUPLICATION (Keep latest by _INGESTION_TIMESTAMP)
        df_clean = df_bronze \
            .sort(F.col("_INGESTION_TIMESTAMP").desc()) \
            .drop_duplicates(PRIMARY_KEYS)
        
        logger.info(f"After deduplication: {df_clean.count()} records")
        
        # TARGET TABLE
        target_table = f"{SCHEMA_SILVER}.{TABLE_NAME}"
        
        # CHECK IF TABLE EXISTS
        try:
            existing_table = session.table(target_table)
            table_exists = True
        except:
            table_exists = False
        
        # MERGE (if exists) OR OVERWRITE (if first load)
        if table_exists and PRIMARY_KEYS[0] != "ID":
            logger.info(f"Performing MERGE into {target_table}")
            
            # Build merge condition
            merge_condition = " AND ".join(
                [f"TARGET.{pk} = SOURCE.{pk}" for pk in PRIMARY_KEYS]
            )
            
            # Execute MERGE
            existing_table.merge(
                df_clean.alias("SOURCE"),
                merge_condition,
                [
                    F.when_matched().update({col: df_clean[col] for col in df_clean.columns}),
                    F.when_not_matched().insert({col: df_clean[col] for col in df_clean.columns})
                ]
            )
            
            result_msg = f"✅ MERGE completed for {target_table}"
        else:
            logger.info(f"Initial load to {target_table}")
            
            df_clean.write \
                .mode("overwrite") \
                .save_as_table(target_table)
            
            result_msg = f"✅ Initial load completed for {target_table}"
        
        logger.info(result_msg)
        return result_msg
    
    except Exception as e:
        error_msg = f"❌ Silver transformation failed: {str(e)}"
        logger.error(error_msg)
        raise Exception(error_msg)
    
    finally:
        logger.info("Silver transformation completed")

if __name__ == "__main__":
    session = snowpark.Session.builder.getOrCreate()
    result = main(session)
    print(result)
