# ===============================================================================
# GOLD LAYER - BUSINESS VIEW
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: silver_curated.fact_orders_silver
# Target: main_catalog.gold_business.fact_orders
# Table Type: FACT
# Generated: 2026-02-10
# ===============================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, lit, sum as _sum, avg, count, max as _max, min as _min,
    current_timestamp, current_date, when, coalesce
)
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

CATALOG = "main_catalog"
SCHEMA_SILVER = "silver_curated"
SCHEMA_GOLD = "gold_business"
SOURCE_TABLE = "fact_orders_silver"
TARGET_TABLE = "fact_orders"
TABLE_TYPE = "FACT"

try:
    logger.info(f"Starting Gold layer creation for {TARGET_TABLE}")
    
    # 1. READ SILVER DATA
    silver_table = f"{CATALOG}.{SCHEMA_SILVER}.{SOURCE_TABLE}"
    df_silver = spark.read.table(silver_table)
    logger.info(f"Read {df_silver.count()} records from Silver")
    
    # 2. APPLY BUSINESS LOGIC
    # Grain: One row per order (order_id as grain), with denormalized customer attributes
    # If star schema required, join customer dimension
    customer_dim = spark.read.table(f"{CATALOG}.{SCHEMA_GOLD}.dim_customers")
    logger.info(f"Read {customer_dim.count()} records from Customer Dimension")

    df_joined = df_silver.join(
        customer_dim,
        df_silver.customer_id == customer_dim.customer_key,
        how="left"
    )
    logger.info(f"Joined Fact with Dimension: {df_joined.count()} records")

    # Aggregation: One row per order (order_id is unique, but also include customer, product for BI usability)
    df_gold = df_joined.groupBy(
        col("order_id").alias("order_key"),
        col("order_date").alias("date_key"),
        col("customer_id").alias("customer_key"),
        col("product_id").alias("product_key")
    ).agg(
        _sum(coalesce(col("order_amount"), lit(0.0))).alias("order_amount"),
        _sum(coalesce(col("quantity"), lit(0))).alias("quantity"),
        _max(col("order_status")).alias("order_status"),
        _max(col("customer_name")).alias("customer_name"),
        _max(col("country")).alias("customer_country")
    ).withColumn(
        "processed_timestamp", current_timestamp()
    )
    logger.info(f"Fact aggregation completed: {df_gold.count()} records")

    # 3. DATA VALIDATION
    record_count = df_gold.count()
    assert record_count > 0, f"No records in Gold layer for {TARGET_TABLE}"
    logger.info(f"Validated: {record_count} records ready for Gold")

    # 4. WRITE TO GOLD
    target_gold_table = f"{CATALOG}.{SCHEMA_GOLD}.{TARGET_TABLE}"
    df_gold.write \
        .format("delta") \
        .mode("overwrite") \
        .option("overwriteSchema", "true") \
        .saveAsTable(target_gold_table)
    logger.info(f"✅ Gold layer updated: {target_gold_table}")
    logger.info(f"Schema: {df_gold.schema.simpleString()}")

except Exception as e:
    logger.error(f"❌ Gold layer creation failed for {TARGET_TABLE}: {str(e)}")
    raise
finally:
    logger.info("Gold layer process completed")
