# ===============================================================================
# MS FABRIC - BRONZE LAYER (Lakehouse Notebook)
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: adls://customers.csv
# Target Lakehouse: bronze
# Target Table: bronze_customers
# Generated: 2026-02-10
# ===============================================================================

# [IMPORTS]
from pyspark.sql import SparkSession
from pyspark.sql.functions import current_timestamp, current_date, input_file_name, lit
import logging

# [CONFIGURATION]
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

LAKEHOUSE_BRONZE = "bronze"  # Bronze Lakehouse name
SOURCE_SYSTEM = "ADLS"       # Source system name (customize if known)
TABLE_NAME = "bronze_customers"

try:
    logger.info(f"Starting Bronze ingestion for {TABLE_NAME}")
    # [EXTRACT]
    df_source = spark.read \
        .format("csv") \
        .option("header", "true") \
        .option("inferSchema", "true") \
        .load(f"Files/raw/{TABLE_NAME}/*.csv")

    logger.info(f"Read {df_source.count()} records from source")
    
    # [TRANSFORM] - Add Fabric Audit Columns
    df_bronze = df_source \
        .withColumn("_FabricIngestTime", current_timestamp()) \
        .withColumn("_IngestionDate", current_date()) \
        .withColumn("_SourceFile", input_file_name()) \
        .withColumn("_SourceSystem", lit(SOURCE_SYSTEM))
    
    # [VALIDATION]
    record_count = df_bronze.count()
    assert record_count > 0, f"No data to ingest for {TABLE_NAME}"
    logger.info(f"Validated: {record_count} records ready for ingestion")
    
    # [LOAD] - Write to Bronze Lakehouse Table
    target_table = f"{LAKEHOUSE_BRONZE}.{TABLE_NAME}"
    df_bronze.write \
        .format("delta") \
        .mode("append") \
        .option("mergeSchema", "true") \
        .option("delta.enableChangeDataFeed", "true") \
        .saveAsTable(target_table)
    
    # [OPTIMIZE] - V-Order for Power BI Direct Lake
    spark.sql(f"""
        OPTIMIZE {target_table}
        VORDER BY (_IngestionDate)
    """)
    
    logger.info(f"\u2705 Successfully ingested to Bronze: {target_table}")
    logger.info(f"\u2705 Table optimized with V-Order for Direct Lake mode")
    
except Exception as e:
    logger.error(f"\u274c Bronze ingestion failed for {TABLE_NAME}: {str(e)}")
    raise
finally:
    logger.info("Bronze ingestion process completed")
