# ===============================================================================
# GOLD LAYER - BUSINESS VIEW (SNOWFLAKE)
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: FACT_ORDERS (silver)
# Target: GOLD_BUSINESS.FACT_ORDERS
# Table Type: FACT
# Generated: 2026-02-10
# ==============================================================================

import snowflake.snowpark as snowpark
from snowflake.snowpark import Session
import snowflake.snowpark.functions as F
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def main(session: Session) -> str:
    """
    Gold layer business view creation.
    
    Args:
        session: Snowpark Session
    
    Returns:
        str: Status message
    """
    # CONFIGURATION
    SCHEMA_SILVER = "SILVER_CURATED"
    SCHEMA_GOLD = "GOLD_BUSINESS"
    SOURCE_TABLE = "FACT_ORDERS"
    TARGET_TABLE = "FACT_ORDERS"
    TABLE_TYPE = "FACT"
    
    try:
        logger.info(f"Starting Gold layer for {TARGET_TABLE}")
        # READ SILVER
        silver_table = f"{SCHEMA_SILVER}.{SOURCE_TABLE}"
        df_silver = session.table(silver_table)
        logger.info(f"Read {df_silver.count()} records from Silver")
        # APPLY BUSINESS LOGIC
        df_gold = df_silver.select(
            F.col("ORDER_ID").alias("ORDER_KEY"),
            F.col("CUSTOMER_ID").alias("CUSTOMER_KEY"),
            F.col("PRODUCT_ID").alias("PRODUCT_KEY"),
            F.col("ORDER_DATE").alias("DATE_KEY"),
            F.col("QUANTITY"),
            F.col("ORDER_AMOUNT"),
            F.col("DISCOUNT_AMOUNT"),
            # Derived measures (ensure null handling)
            F.coalesce(F.col("ORDER_AMOUNT"), F.lit(0)).alias("TOTAL_AMOUNT"),
            F.coalesce(F.col("DISCOUNT_AMOUNT"), F.lit(0)).alias("ADJUSTED_DISCOUNT_AMOUNT"),
            # Audit
            F.current_timestamp().alias("PROCESSED_TIMESTAMP")
        )
        logger.info(f"Applied {TABLE_TYPE} business logic")
        # VALIDATE
        record_count = df_gold.count()
        if record_count == 0:
            raise ValueError(f"No records for Gold layer: {TARGET_TABLE}")
        logger.info(f"Validated: {record_count} records")
        # WRITE TO GOLD
        target_gold_table = f"{SCHEMA_GOLD}.{TARGET_TABLE}"
        df_gold.write \
            .mode("overwrite") \
            .save_as_table(target_gold_table)
        success_msg = f"✅ Gold layer updated: {target_gold_table} ({record_count} records)"
        logger.info(success_msg)
        return success_msg
    except Exception as e:
        error_msg = f"❌ Gold layer failed: {str(e)}"
        logger.error(error_msg)
        raise Exception(error_msg)
    finally:
        logger.info("Gold layer process completed")

if __name__ == "__main__":
    session = snowpark.Session.builder.getOrCreate()
    result = main(session)
    print(result)
