# ==============================================================================
# SILVER LAYER TRANSFORMATION
# ==============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source: bronze_raw.dim_customers
# Target: main_catalog.silver_clean.dim_customers
# Primary Key(s): CustomerKey
# Generated: 2026-02-10
# ==============================================================================

from pyspark.sql import SparkSession, Window
from pyspark.sql.functions import col, row_number
from delta.tables import DeltaTable
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# CONFIGURATION
CATALOG = "main_catalog"
SCHEMA_BRONZE = "bronze_raw"
SCHEMA_SILVER = "silver_clean"
TABLE_NAME = "dim_customers"
PRIMARY_KEYS = ["CustomerKey"]

try:
    logger.info(f"Starting Silver transformation for {TABLE_NAME}")

    # READ BRONZE DATA
    bronze_table = f"{CATALOG}.{SCHEMA_BRONZE}.{TABLE_NAME}"
    df_bronze = spark.read.table(bronze_table)
    logger.info(f"Read {df_bronze.count()} records from Bronze")

    # DATA QUALITY CHECKS: Filter NULLs in PK
    null_pks = df_bronze.filter(col("CustomerKey").isNull()).count()
    if null_pks > 0:
        logger.warning(f"Found {null_pks} records with NULL primary keys - will be filtered")
        df_bronze = df_bronze.filter(col("CustomerKey").isNotNull())

    # DEDUPLICATION (Window function, MANDATORY)
    window_spec = Window.partitionBy("CustomerKey").orderBy(col("_ingestion_timestamp").desc())
    df_clean = df_bronze \
        .withColumn("_row_num", row_number().over(window_spec)) \
        .filter(col("_row_num") == 1) \
        .drop("_row_num")
    logger.info(f"After deduplication: {df_clean.count()} records")

    # WRITE TO SILVER (SCD Type 2 Upsert)
    target_table_name = f"{CATALOG}.{SCHEMA_SILVER}.{TABLE_NAME}"
    table_exists = spark.catalog.tableExists(target_table_name)
    has_valid_pk = PRIMARY_KEYS[0] != "id"

    if table_exists and has_valid_pk:
        logger.info(f"Performing MERGE into {target_table_name}")
        target_table = DeltaTable.forName(spark, target_table_name)
        merge_condition = "target.CustomerKey = source.CustomerKey"
        target_table.alias("target").merge(
            df_clean.alias("source"),
            merge_condition
        ).whenMatchedUpdateAll() \
         .whenNotMatchedInsertAll() \
         .execute()
        logger.info("✅ MERGE completed successfully")
    else:
        logger.info(f"Initial load to {target_table_name}")
        df_clean.write \
            .format("delta") \
            .mode("overwrite") \
            .saveAsTable(target_table_name)
        logger.info("✅ Initial load completed")

    # FINAL VALIDATION
    final_count = spark.read.table(target_table_name).count()
    logger.info(f"Final Silver table count: {final_count} records")

except Exception as e:
    logger.error(f"❌ Silver transformation failed for {TABLE_NAME}: {str(e)}")
    raise
finally:
    logger.info("Silver transformation process completed")
