-- ===============================================================================
-- GCP BIGQUERY - BRONZE LAYER (Raw Ingestion)
-- ===============================================================================
-- Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
-- Source: gs://bucket/customers.csv
-- Target: `bc0a94d4-e0e5-424a-ad93-0c8ae586a8f4.bronze_raw.customers`
-- Generated: 2026-02-10T00:00:00Z
-- ===============================================================================

-- Configuration
DECLARE project_id STRING DEFAULT 'bc0a94d4-e0e5-424a-ad93-0c8ae586a8f4';
DECLARE dataset_bronze STRING DEFAULT 'bronze_raw';
DECLARE source_system STRING DEFAULT 'GCS';
DECLARE table_name STRING DEFAULT 'customers';

-- Bronze Layer Ingestion
CREATE OR REPLACE TABLE `bc0a94d4-e0e5-424a-ad93-0c8ae586a8f4.bronze_raw.customers`
PARTITION BY DATE(_ingestion_date)
CLUSTER BY customer_key
AS
SELECT
    customer_key,
    customer_id,
    name,
    email,
    region,
    CURRENT_TIMESTAMP() AS _ingestion_timestamp,
    CURRENT_DATE() AS _ingestion_date,
    'gs://bucket/customers.csv' AS _source_file,
    'GCS' AS _source_system
FROM
    `bc0a94d4-e0e5-424a-ad93-0c8ae586a8f4.bronze_raw.external_customers`;

-- Log completion
INSERT INTO `bc0a94d4-e0e5-424a-ad93-0c8ae586a8f4.utils.job_logs` (job_name, timestamp, status, row_count)
SELECT
    'bronze_customers' AS job_name,
    CURRENT_TIMESTAMP() AS timestamp,
    'SUCCESS' AS status,
    COUNT(*) AS row_count
FROM `bc0a94d4-e0e5-424a-ad93-0c8ae586a8f4.bronze_raw.customers`;
