# ===============================================================================
# MS FABRIC - GOLD LAYER (Business/Semantic)
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source Lakehouse: silver
# Target Lakehouse: gold
# Table: <REPLACE_WITH_TABLE_NAME>
# Table Type: <DIMENSION|FACT>
# Power BI: Direct Lake Compatible
# Generated: <REPLACE_WITH_TIMESTAMP>
# ===============================================================================

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, lit, sum as _sum, avg, count,
    current_timestamp, when, coalesce
)
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# =====================[CONFIGURATION]=====================
LAKEHOUSE_SILVER = "silver"
LAKEHOUSE_GOLD = "gold"
SOURCE_TABLE = "<REPLACE_WITH_SOURCE_TABLE>"  # e.g., 'DimCustomer' or 'FactSales'
TARGET_TABLE = "<REPLACE_WITH_TARGET_TABLE>"
TABLE_TYPE = "<DIMENSION|FACT>" # Must be set to either 'DIMENSION' or 'FACT'

try:
    logger.info(f"Starting Gold layer for {TARGET_TABLE}")
    # =====================[EXTRACT]=====================
    silver_table = f"{LAKEHOUSE_SILVER}.{SOURCE_TABLE}"
    df_silver = spark.read.table(silver_table)
    logger.info(f"Read {df_silver.count()} records from Silver")

    # =====================[TRANSFORM]=====================
    if TABLE_TYPE == "DIMENSION":
        # Example for Customer Dimension; adapt columns as necessary
        df_gold = df_silver.select(
            col("customer_id").cast("long").alias("CustomerKey"),
            col("customer_name").cast("string").alias("CustomerName"),
            col("email").cast("string").alias("Email"),
            col("country").cast("string").alias("Country"),
            when(col("status") == lit("A"), lit("Active"))
                .otherwise(lit("Inactive")).alias("StatusLabel"),
            col("registration_date").cast("date").alias("CustomerSinceDate"),
            col("_FabricIngestTime").alias("LastUpdated")
        )
    elif TABLE_TYPE == "FACT":
        # Example for Sales Fact; adapt columns as necessary
        df_gold = df_silver.select(
            col("order_id").cast("long").alias("OrderKey"),
            col("customer_id").cast("long").alias("CustomerKey"),
            col("product_id").cast("long").alias("ProductKey"),
            col("order_date").cast("date").alias("DateKey"),
            col("quantity").cast("int").alias("Quantity"),
            col("unit_price").cast("decimal(18,2)").alias("UnitPrice"),
            (col("quantity") * col("unit_price")).cast("decimal(18,2)").alias("TotalAmount"),
            ((col("quantity") * col("unit_price")) * coalesce(col("discount_pct"), lit(0))).cast("decimal(18,2)").alias("DiscountAmount"),
            current_timestamp().alias("ProcessedTimestamp")
        )
    else:
        # Default: Passthrough with renaming/casting if necessary
        df_gold = df_silver

    logger.info(f"Applied {TABLE_TYPE} business logic")

    # =====================[VALIDATION]=====================
    record_count = df_gold.count()
    assert record_count > 0, f"No records for Gold layer: {TARGET_TABLE}"
    logger.info(f"Validated: {record_count} records")

    # =====================[LOAD]=====================
    target_gold_table = f"{LAKEHOUSE_GOLD}.{TARGET_TABLE}"
    df_gold.write \
        .format("delta") \
        .mode("overwrite") \
        .option("overwriteSchema", "true") \
        .option("delta.enableChangeDataFeed", "true") \
        .saveAsTable(target_gold_table)
    logger.info(f"✅ Gold layer updated: {target_gold_table}")

    # =====================[OPTIMIZE]=====================
    if TABLE_TYPE == "DIMENSION":
        spark.sql(f"""
            OPTIMIZE {target_gold_table}
            VORDER BY (CustomerKey)
        """)
    elif TABLE_TYPE == "FACT":
        spark.sql(f"""
            OPTIMIZE {target_gold_table}
            VORDER BY (DateKey)
        """)
    else:
        spark.sql(f"OPTIMIZE {target_gold_table}")
    logger.info(f"✅ Table optimized with V-Order for Power BI Direct Lake")
    logger.info(f"✅ {record_count} records ready for semantic model")

except Exception as e:
    logger.error(f"❌ Gold layer failed: {str(e)}")
    raise
finally:
    logger.info("Gold layer process completed")
