-- ===========================================================================
-- BRONZE LAYER (STAGING)
-- ===========================================================================
-- Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
-- Source: raw_data.customers
-- Target: bronze.stg_customers
-- Generated: {{ run_started_at | as_datetime }}
-- ===========================================================================

{{
  config(
    materialized='view',
    schema='bronze'
  )
}}

with source as (
    select * from {{ source('raw_data', 'customers') }}
),

renamed as (
    select
        -- TODO: Replace with explicit column selection once DDL is known
        *,
        current_timestamp() as _ingested_at,
        current_date() as _ingested_date,
        'raw_data' as _source_system
    from source
)

select * from renamed