# ===============================================================================
# MS FABRIC - SILVER LAYER (Lakehouse Notebook)
# ===============================================================================
# Generated by: Legacy2Lake UTM Platform - Agent C (Interpreter)
# Source Lakehouse: bronze
# Target Lakehouse: silver
# Table: <<REPLACE_WITH_TABLE_NAME>>
# Primary Keys: [<<REPLACE_WITH_PK1>>, <<REPLACE_WITH_PK2>>]
# Generated: 2026-02-10
# ===============================================================================

def execute_task(spark, config):
    from pyspark.sql import SparkSession
    from pyspark.sql.functions import col, row_number
    from pyspark.sql.window import Window
    from delta.tables import DeltaTable
    import logging

    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)

    # [CONFIGURATION]
    LAKEHOUSE_BRONZE = config["bronze_lakehouse"] if "bronze_lakehouse" in config else "bronze"
    LAKEHOUSE_SILVER = config["silver_lakehouse"] if "silver_lakehouse" in config else "silver"
    TABLE_NAME = config["table_name"]
    PRIMARY_KEYS = config["primary_keys"]  # e.g., ["customer_id", "order_id"]
    DEDUP_TIMESTAMP_COL = config.get("dedup_timestamp_col", "_FabricIngestTime")
    VORDER_COL = config.get("vorder_col", "_IngestionDate")

    try:
        logger.info(f"Starting Silver transformation for {TABLE_NAME}")
        # [EXTRACT]
        bronze_table = f"{LAKEHOUSE_BRONZE}.{TABLE_NAME}"
        df_bronze = spark.read.table(bronze_table)
        count_bronze = df_bronze.count()
        logger.info(f"Read {count_bronze} records from Bronze")
        print(f"Rows processed (bronze extract): {count_bronze}")

        # [TRANSFORM] - Data Quality: Filter NULL PKs
        filter_expr = " AND ".join([f"{pk} IS NOT NULL" for pk in PRIMARY_KEYS])
        df_bronze = df_bronze.filter(filter_expr)

        # [TRANSFORM] - Deduplication
        window_spec = Window.partitionBy(*PRIMARY_KEYS).orderBy(col(DEDUP_TIMESTAMP_COL).desc())
        df_clean = df_bronze \
            .withColumn("_row_num", row_number().over(window_spec)) \
            .filter(col("_row_num") == 1) \
            .drop("_row_num")
        count_clean = df_clean.count()
        logger.info(f"After deduplication: {count_clean} records")
        print(f"Rows processed (deduped): {count_clean}")

        # [LOAD]
        target_table = f"{LAKEHOUSE_SILVER}.{TABLE_NAME}"
        table_exists = spark.catalog.tableExists(target_table)
        has_valid_pk = len(PRIMARY_KEYS) > 0 and all([pk != "id" for pk in PRIMARY_KEYS])

        if table_exists and has_valid_pk:
            logger.info(f"Performing MERGE into {target_table}")
            merge_condition = " AND ".join([f"target.{pk} = source.{pk}" for pk in PRIMARY_KEYS])
            target_delta = DeltaTable.forName(spark, target_table)
            target_delta.alias("target").merge(
                df_clean.alias("source"),
                merge_condition
            ).whenMatchedUpdateAll() \
             .whenNotMatchedInsertAll() \
             .execute()
            logger.info("\u2705 MERGE completed successfully")
        else:
            logger.info(f"Initial load to {target_table}")
            df_clean.write \
                .format("delta") \
                .mode("overwrite") \
                .option("delta.enableChangeDataFeed", "true") \
                .saveAsTable(target_table)
            logger.info("\u2705 Initial load completed")

        # [OPTIMIZE]
        spark.sql(f"""
            OPTIMIZE {target_table}
            VORDER BY ({VORDER_COL})
        """)
        logger.info(f"\u2705 Table optimized with V-Order for Direct Lake")

        # [AUDIT]
        final_count = spark.read.table(target_table).count()
        logger.info(f"Final Silver table count: {final_count} records")
        print(f"Rows processed (final silver): {final_count}")

    except Exception as e:
        logger.error(f"\u274c Silver transformation failed for {TABLE_NAME}: {str(e)}")
        raise
    finally:
        logger.info("Silver transformation completed")

# Call pattern
# Example config:
# config = {
#     "bronze_lakehouse": "bronze",
#     "silver_lakehouse": "silver",
#     "table_name": "your_table",
#     "primary_keys": ["pk1", "pk2"],
#     "dedup_timestamp_col": "_FabricIngestTime",   # optional
#     "vorder_col": "_IngestionDate"                # optional
# }
# execute_task(spark, config)
