-- ================================================================
-- Sprint 14 Fix: Add cartridge_microsoft_fabric_direct prompt
-- Date: 2026-02-16
-- ================================================================
-- Problem: Agent C generates architectural patterns in direct mode
--          because cartridge prompt is missing from database
-- Solution: Insert new cartridge prompt for Microsoft Fabric direct translation
-- ================================================================

-- Insert the Microsoft Fabric Direct Translation cartridge prompt
INSERT INTO public.utm_prompts (
    prompt_id,
    content,
    is_active,
    agent_id,
    tech_stack,
    pattern_type,
    metadata,
    created_at,
    updated_at
) VALUES (
    'cartridge_microsoft_fabric_direct',
    E'# Microsoft Fabric PySpark Direct Translation Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS (1:1 Transpilation - Zero Architecture)\n\n### 1. MANDATORY L2L DIRECT TRANSLATION HEADER\n```python\n# ================================================================\n# L2L DIRECT TRANSLATION: {{asset_name}}\n# ================================================================\n# Source Asset: {{source_asset_name}}\n# Source Technology: {{source_tech}}\n# Target Platform: Microsoft Fabric (Lakehouse + PySpark + Delta Lake)\n# Translation Mode: Direct 1:1 (No Architectural Patterns)\n# Component Type: Data Pipeline\n# Business Entity: {{business_entity}}\n# Load Strategy: {{load_strategy}}\n# Generated At: {{timestamp}}\n# Generated By: L2L Agent-C (Cartridge: DirectTranspiler v4.0 - Fabric)\n# ================================================================\n# NOTE: This is a functional translation that preserves original logic.\n#       For architectural patterns (Medallion, Data Vault, etc.), \n#       apply Pattern Application phase after validation.\n# ================================================================\n```\n\n### 2. CRITICAL RULES FOR DIRECT TRANSLATION\n\n**✅ REQUIRED:**\n- Header: "L2L DIRECT TRANSLATION: {asset_name}" (not "MODERNIZATION TRACE")\n- Function signature: `execute_task(spark, config)` ONLY (no main())\n- Zero hardcoded values (all from config dictionary)\n- Type casting from metadata (Sprint 10)\n- Row count logging at each stage\n- Simple write: `.mode(''overwrite'')` or `.mode(''append'')`\n\n**❌ FORBIDDEN:**\n- NO MERGE INTO patterns\n- NO Bronze/Silver/Gold layer references\n- NO Medallion columns (_ingestion_timestamp, _record_hash)\n- NO OPTIMIZE or VACUUM commands\n- NO COALESCE for unknown member handling (unless in original)\n- NO architectural enhancements\n\n### 3. LOAD STRATEGY IMPLEMENTATION\n\n**For FULL_OVERWRITE:**\n```python\n# ✅ CORRECT: Simple overwrite\nload_mode = config.get(''load_mode'', ''overwrite'')\ndf_final.write.format("delta").mode(load_mode).save(target_path)\n```\n\n**❌ WRONG: Do NOT use MERGE in direct translation**\n```python\n# This is architectural pattern - NOT for direct mode\n# DeltaTable.forPath(spark, target_path).merge(...)\n```\n\n### 4. EXAMPLE STRUCTURE\n```python\n# ================================================================\n# L2L DIRECT TRANSLATION: {{asset_name}}\n# ================================================================\n# [Full header with all fields]\n# ================================================================\n\nfrom pyspark.sql import functions as F\nfrom pyspark.sql.types import *\nimport logging\n\ndef execute_task(spark, config):\n    """\n    Direct translation preserving original logic.\n    No architectural patterns applied.\n    """\n    logger = logging.getLogger(__name__)\n    \n    # [EXTRACT]\n    logger.info(f"[EXTRACT] Reading source")\n    df = spark.read.jdbc(\n        url=config[''jdbc_url''],\n        table=f"({config[''source_query'']}) AS source",\n        properties={"user": config[''jdbc_user''], "password": config[''jdbc_password'']}\n    )\n    logger.info(f"[EXTRACT] Source rows: {df.count()}")\n    \n    # [TRANSFORM]\n    logger.info("[TRANSFORM] Applying type casting")\n    df_typed = df.select([\n        F.col(col[''name'']).cast(_parse_data_type(col[''data_type''])).alias(col[''name''])\n        for col in config.get(''columns'', [])\n    ])\n    logger.info(f"[TRANSFORM] Transformed rows: {df_typed.count()}")\n    \n    # [LOAD] - Simple overwrite (NO MERGE)\n    load_mode = config.get(''load_mode'', ''overwrite'')\n    logger.info(f"[LOAD] Writing to {config[''target_path'']} (mode={load_mode})")\n    df_typed.write.format("delta").mode(load_mode).save(config[''target_path''])\n    logger.info(f"[LOAD] Success: {df_typed.count()} rows")\n    \n    return {''status'': ''success'', ''rows_written'': df_typed.count()}\n\ndef _parse_data_type(dtype_str):\n    dtype_map = {\n        ''STRING'': StringType(), ''INT'': IntegerType(), \n        ''BIGINT'': LongType(), ''DOUBLE'': DoubleType(),\n        ''DECIMAL'': DecimalType(38, 10),\n        ''DATE'': DateType(), ''TIMESTAMP'': TimestampType(),\n        ''BOOLEAN'': BooleanType()\n    }\n    return dtype_map.get(str(dtype_str).upper(), StringType())\n```\n\n## 🎯 VALIDATION CHECKLIST (Agent F Criteria)\n- ✅ Header: "L2L DIRECT TRANSLATION: {asset_name}"\n- ✅ No hardcoded paths/credentials\n- ✅ Function: `execute_task(spark, config)` only\n- ✅ Type casting from metadata\n- ✅ Row count logging\n- ✅ Simple write: `.mode(''overwrite'')` or `.mode(''append'')`\n- ❌ NO MERGE patterns\n- ❌ NO Bronze/Silver/Gold references\n- ❌ NO OPTIMIZE/VACUUM\n- ❌ NO Medallion columns\n\n**Reference:** See `/apps/api/prompts/cartridge_microsoft_fabric_direct.md` for full specification.',
    true,
    'agent-c',
    'microsoft_fabric',
    'direct',
    '{"description": "Microsoft Fabric direct translation cartridge rules (1:1 functional equivalence, no architectural patterns)", "version": "4.0", "source_file": "cartridge_microsoft_fabric_direct.md", "created_by": "sprint_14_fix"}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (prompt_id) DO UPDATE SET
    content = EXCLUDED.content,
    is_active = EXCLUDED.is_active,
    agent_id = EXCLUDED.agent_id,
    tech_stack = EXCLUDED.tech_stack,
    pattern_type = EXCLUDED.pattern_type,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

-- Verify insertion
SELECT 
    prompt_id,
    agent_id,
    tech_stack,
    pattern_type,
    is_active,
    LENGTH(content) as content_length,
    metadata->>'version' as version,
    created_at
FROM public.utm_prompts
WHERE prompt_id = 'cartridge_microsoft_fabric_direct';

-- ================================================================
-- Expected Result:
-- ================================================================
-- prompt_id                          | cartridge_microsoft_fabric_direct
-- agent_id                           | agent-c
-- tech_stack                         | microsoft_fabric
-- pattern_type                       | direct
-- is_active                          | true
-- content_length                     | ~3500 chars
-- version                            | 4.0 (from metadata)
-- created_at                         | 2026-02-16 ...
-- ================================================================
