-- ================================================================
-- Sprint 14 Fix: Add Microsoft Fabric Medallion Cartridge Prompts
-- Date: 2026-02-20
-- ================================================================
-- Problem: Projects with target_tech='fabric' cannot find cartridge prompts
--          for Bronze, Silver, and Gold layers (404 errors)
-- Solution: Insert 3 new cartridge prompts for Microsoft Fabric Medallion layers
--           (adapted from Databricks cartridges since Fabric uses PySpark + Delta Lake)
-- ================================================================

-- ================================================================
-- 1. BRONZE LAYER CARTRIDGE
-- ================================================================
INSERT INTO public.utm_prompts (
    prompt_id,
    content,
    is_active,
    agent_id,
    tech_stack,
    pattern_type,
    metadata,
    created_at,
    updated_at
) VALUES (
    'cartridge_fabric_bronze',
    E'# Microsoft Fabric PySpark Bronze Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS (Zero-Hardcode Policy)\n\n### 1. MANDATORY L2L MODERNIZATION TRACE HEADER\n```python\n# ================================================================\n# L2L MODERNIZATION TRACE: Bronze Layer - {{asset_name}}\n# ================================================================\n# Source Asset: {{source_asset_name}}\n# Source Technology: {{source_tech}}\n# Target Platform: Microsoft Fabric (Lakehouse + PySpark + Delta Lake)\n# Medallion Layer: Bronze\n# Component Type: Data Pipeline\n# Business Entity: {{business_entity}}\n# Load Strategy: {{load_strategy}}\n# Generated At: {{timestamp}}\n# Generated By: L2L Agent-C (Cartridge: FabricBronze v4.0)\n# ================================================================\n```\n\n### 2. ZERO-HARDCODE CONFIGURATION\n**❌ FORBIDDEN: Hardcoded values anywhere in code**\n- NO hardcoded paths: `/lakehouse/default/Tables/bronze_*`\n- NO example credentials: `<JDBC_URL>`, `<USER>`, `<PASSWORD>`\n- NO sample configs in `main()` functions\n- NO static connection strings\n\n**✅ REQUIRED: All paths and configs from orchestrator context**\n```python\ndef execute_task(spark, config):\n    # Extract ALL values from config dictionary\n    bronze_path = config[''bronze_path'']\n    workspace = config.get(''workspace_name'', ''default'')\n    lakehouse = config.get(''lakehouse_name'', ''main'')\n    jdbc_url = config[''jdbc_url'']  # Injected by orchestrator\n    jdbc_user = config[''jdbc_user'']  # Injected by orchestrator\n    jdbc_password = config[''jdbc_password'']  # Injected by orchestrator\n```\n\n### 3. PARAMETERIZED EXTRACTION (Required)\n**✅ REQUIRED: Parameterized extraction using config**\n```python\n# Extract parameters from config\nif config.get(''load_mode'') == ''incremental'':\n    watermark_col = config[''watermark_column'']\n    last_watermark = config.get(''last_watermark_value'')\n    \n    query = f"""\n        SELECT * FROM {config[''source_table'']}\n        WHERE {watermark_col} > ''{last_watermark}''\n    """\n    df = spark.read.jdbc(url=jdbc_url, table=f"({query}) AS incremental_data", properties={...})\nelse:\n    df = spark.read.jdbc(url=jdbc_url, table=config[''source_table''], properties={...})\n```\n\n### 4. BRONZE LAYER SPECIFIC REQUIREMENTS\n**Medallion Columns (Automatically Added):**\n```python\n# Add Bronze layer metadata columns\ndf_bronze = df \\\n    .withColumn("_ingestion_timestamp", F.current_timestamp()) \\\n    .withColumn("_source_file", F.lit(config.get(''source_file'', ''N/A''))) \\\n    .withColumn("_record_hash", F.sha2(F.concat_ws("||", *df.columns), 256))\n```\n\n**Write Pattern:**\n```python\n# Bronze: Always append (never overwrite)\ndf_bronze.write \\\n    .format("delta") \\\n    .mode("append") \\\n    .option("mergeSchema", "true") \\\n    .save(config[''bronze_path''])\n```\n\n### 5. TYPE CASTING FROM METADATA (Sprint 10 Compliance)\n```python\n# Apply type casting from metadata (utm_asset_columns)\nfrom pyspark.sql.types import *\n\ndef _parse_data_type(dtype_str):\n    dtype_map = {\n        ''STRING'': StringType(), ''INT'': IntegerType(),\n        ''BIGINT'': LongType(), ''DOUBLE'': DoubleType(),\n        ''DECIMAL'': DecimalType(38, 10),\n        ''DATE'': DateType(), ''TIMESTAMP'': TimestampType(),\n        ''BOOLEAN'': BooleanType()\n    }\n    return dtype_map.get(str(dtype_str).upper(), StringType())\n\n# Cast columns\ndf_typed = df.select([\n    F.col(col[''name'']).cast(_parse_data_type(col[''data_type''])).alias(col[''name''])\n    for col in config.get(''columns'', [])\n])\n```\n\n### 6. ROW COUNT LOGGING (Required)\n```python\nimport logging\nlogger = logging.getLogger(__name__)\n\n# Log row counts at each stage\nlogger.info(f"[EXTRACT] Source rows: {df.count()}")\nlogger.info(f"[TRANSFORM] Typed rows: {df_typed.count()}")\nlogger.info(f"[LOAD] Bronze rows written: {df_bronze.count()}")\n```\n\n## 🎯 VALIDATION CHECKLIST (Agent F Criteria)\n- ✅ Header: L2L MODERNIZATION TRACE with all fields\n- ✅ No hardcoded paths/credentials\n- ✅ Function signature: `execute_task(spark, config)`\n- ✅ Type casting from metadata (utm_asset_columns)\n- ✅ Bronze metadata columns: `_ingestion_timestamp`, `_source_file`, `_record_hash`\n- ✅ Write mode: `append` (never overwrite)\n- ✅ Row count logging at each stage\n- ✅ Incremental logic uses config parameters',
    true,
    'agent-c',
    'fabric',
    'bronze',
    '{"description": "Microsoft Fabric Bronze Layer cartridge (raw data ingestion with Medallion pattern)", "version": "4.0", "created_by": "sprint_14_fabric_fix", "adapted_from": "cartridge_databricks_bronze"}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (prompt_id) DO UPDATE SET
    content = EXCLUDED.content,
    is_active = EXCLUDED.is_active,
    agent_id = EXCLUDED.agent_id,
    tech_stack = EXCLUDED.tech_stack,
    pattern_type = EXCLUDED.pattern_type,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

-- ================================================================
-- 2. SILVER LAYER CARTRIDGE
-- ================================================================
INSERT INTO public.utm_prompts (
    prompt_id,
    content,
    is_active,
    agent_id,
    tech_stack,
    pattern_type,
    metadata,
    created_at,
    updated_at
) VALUES (
    'cartridge_fabric_silver',
    E'# Microsoft Fabric PySpark Silver Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS (Zero-Hardcode Policy)\n\n### 1. MANDATORY L2L MODERNIZATION TRACE HEADER\n```python\n# ================================================================\n# L2L MODERNIZATION TRACE: Silver Layer - {{asset_name}}\n# ================================================================\n# Source Asset: {{source_asset_name}}\n# Source Technology: {{source_tech}}\n# Target Platform: Microsoft Fabric (Lakehouse + PySpark + Delta Lake)\n# Medallion Layer: Silver\n# Component Type: Data Pipeline\n# Business Entity: {{business_entity}}\n# Load Strategy: {{load_strategy}}\n# Generated At: {{timestamp}}\n# Generated By: L2L Agent-C (Cartridge: FabricSilver v4.0)\n# ================================================================\n```\n\n### 2. SILVER LAYER CHARACTERISTICS\n**Purpose:** Cleansed, deduplicated, and conformed data\n\n**Key Features:**\n- Read from Bronze layer (Delta Lake)\n- Data quality checks and cleansing\n- Deduplication using business keys\n- Standardized naming conventions\n- MERGE operations for SCD Type 1/2\n\n### 3. READ FROM BRONZE\n```python\n# Read from Bronze layer\nbronze_path = config[''bronze_path'']\ndf_bronze = spark.read.format("delta").load(bronze_path)\n\n# Apply incremental filter if needed\nif config.get(''load_mode'') == ''incremental'':\n    last_timestamp = config[''last_run_timestamp'']\n    df_bronze = df_bronze.filter(F.col("_ingestion_timestamp") > last_timestamp)\n```\n\n### 4. DATA QUALITY CHECKS\n```python\n# Remove nulls in critical columns\ndf_cleaned = df_bronze.dropna(subset=config.get(''critical_columns'', []))\n\n# Standardize string columns\ndf_cleaned = df_cleaned \\\n    .withColumn("customer_name", F.trim(F.upper(F.col("customer_name")))) \\\n    .withColumn("email", F.lower(F.trim(F.col("email"))))\n\n# Log data quality metrics\ninitial_count = df_bronze.count()\nfinal_count = df_cleaned.count()\nrejected_count = initial_count - final_count\nlogger.info(f"[DQ] Initial: {initial_count}, Cleaned: {final_count}, Rejected: {rejected_count}")\n```\n\n### 5. DEDUPLICATION (Business Key)\n```python\n# Deduplicate using business key from config\nbusiness_keys = config.get(''business_keys'', [])\n\nif business_keys:\n    window_spec = Window.partitionBy(*business_keys).orderBy(F.col("_ingestion_timestamp").desc())\n    df_dedup = df_cleaned \\\n        .withColumn("row_num", F.row_number().over(window_spec)) \\\n        .filter(F.col("row_num") == 1) \\\n        .drop("row_num")\nelse:\n    df_dedup = df_cleaned\n```\n\n### 6. MERGE INTO SILVER (SCD Type 1)\n```python\nfrom delta.tables import DeltaTable\n\nsilver_path = config[''silver_path'']\n\nif DeltaTable.isDeltaTable(spark, silver_path):\n    silver_table = DeltaTable.forPath(spark, silver_path)\n    \n    merge_condition = " AND ".join([f"target.{key} = source.{key}" for key in business_keys])\n    \n    silver_table.alias("target").merge(\n        df_silver.alias("source"),\n        merge_condition\n    ).whenMatchedUpdateAll() \\\n     .whenNotMatchedInsertAll() \\\n     .execute()\n    \n    logger.info(f"[MERGE] Silver merge completed")\nelse:\n    # First load - create table\n    df_silver.write.format("delta").mode("overwrite").save(silver_path)\n    logger.info(f"[CREATE] Silver table created with {df_silver.count()} rows")\n```\n\n### 7. SILVER METADATA COLUMNS\n```python\n# Add Silver layer metadata\ndf_silver = df_dedup \\\n    .withColumn("_processed_timestamp", F.current_timestamp()) \\\n    .withColumn("_silver_layer", F.lit("silver")) \\\n    .withColumn("_is_current", F.lit(True)) \\\n    .drop("_record_hash", "_source_file")  # Remove Bronze metadata\n```\n\n## 🎯 VALIDATION CHECKLIST (Agent F Criteria)\n- ✅ Header: L2L MODERNIZATION TRACE with Silver layer\n- ✅ Read from Bronze Delta table\n- ✅ Data quality checks implemented\n- ✅ Deduplication using business keys\n- ✅ MERGE operation for SCD Type 1\n- ✅ Silver metadata columns: `_processed_timestamp`, `_silver_layer`, `_is_current`\n- ✅ No hardcoded values\n- ✅ Row count logging',
    true,
    'agent-c',
    'fabric',
    'silver',
    '{"description": "Microsoft Fabric Silver Layer cartridge (cleaned and deduplicated data with Medallion pattern)", "version": "4.0", "created_by": "sprint_14_fabric_fix", "adapted_from": "cartridge_databricks_silver"}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (prompt_id) DO UPDATE SET
    content = EXCLUDED.content,
    is_active = EXCLUDED.is_active,
    agent_id = EXCLUDED.agent_id,
    tech_stack = EXCLUDED.tech_stack,
    pattern_type = EXCLUDED.pattern_type,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

-- ================================================================
-- 3. GOLD LAYER CARTRIDGE
-- ================================================================
INSERT INTO public.utm_prompts (
    prompt_id,
    content,
    is_active,
    agent_id,
    tech_stack,
    pattern_type,
    metadata,
    created_at,
    updated_at
) VALUES (
    'cartridge_fabric_gold',
    E'# Microsoft Fabric PySpark Gold Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS (Zero-Hardcode Policy)\n\n### 1. MANDATORY L2L MODERNIZATION TRACE HEADER\n```python\n# ================================================================\n# L2L MODERNIZATION TRACE: Gold Layer - {{asset_name}}\n# ================================================================\n# Source Asset: {{source_asset_name}}\n# Source Technology: {{source_tech}}\n# Target Platform: Microsoft Fabric (Lakehouse + PySpark + Delta Lake)\n# Medallion Layer: Gold\n# Component Type: Data Pipeline\n# Business Entity: {{business_entity}}\n# Load Strategy: {{load_strategy}}\n# Generated At: {{timestamp}}\n# Generated By: L2L Agent-C (Cartridge: FabricGold v4.0)\n# ================================================================\n```\n\n### 2. GOLD LAYER CHARACTERISTICS\n**Purpose:** Business-ready, aggregated, and dimensionally modeled data\n\n**Key Features:**\n- Read from Silver layer(s)\n- Join multiple Silver tables\n- Business logic aggregations\n- Dimensional modeling (Facts/Dimensions)\n- Optimized for analytics and reporting\n\n### 3. READ FROM SILVER LAYER(S)\n```python\n# Read from Silver layer(s)\ndf_customers = spark.read.format("delta").load(config[''silver_customers_path''])\ndf_orders = spark.read.format("delta").load(config[''silver_orders_path''])\ndf_products = spark.read.format("delta").load(config[''silver_products_path''])\n```\n\n### 4. BUSINESS LOGIC TRANSFORMATIONS\n```python\n# Join Silver tables\ndf_gold = df_orders \\\n    .join(df_customers, df_orders.customer_id == df_customers.customer_id, "left") \\\n    .join(df_products, df_orders.product_id == df_products.product_id, "left")\n\n# Apply business logic\ndf_gold = df_gold \\\n    .withColumn("total_revenue", F.col("quantity") * F.col("unit_price")) \\\n    .withColumn("profit_margin", \n        (F.col("unit_price") - F.col("cost_price")) / F.col("unit_price") * 100\n    ) \\\n    .withColumn("sales_quarter", F.quarter(F.col("order_date"))) \\\n    .withColumn("customer_segment", \n        F.when(F.col("lifetime_value") > 10000, "Premium")\n         .when(F.col("lifetime_value") > 5000, "Standard")\n         .otherwise("Basic")\n    )\n```\n\n### 5. AGGREGATIONS (Fact Tables)\n```python\n# Create aggregated fact table\ndf_fact_sales = df_gold.groupBy(\n    "sales_quarter",\n    "customer_segment",\n    "product_category"\n).agg(\n    F.sum("total_revenue").alias("total_revenue"),\n    F.avg("profit_margin").alias("avg_profit_margin"),\n    F.count("order_id").alias("order_count"),\n    F.countDistinct("customer_id").alias("unique_customers")\n)\n\nlogger.info(f"[AGGREGATE] Fact table rows: {df_fact_sales.count()}")\n```\n\n### 6. DIMENSIONAL MODELING (SCD Type 2)\n```python\nfrom delta.tables import DeltaTable\n\ngold_path = config[''gold_path'']\n\nif DeltaTable.isDeltaTable(spark, gold_path):\n    gold_table = DeltaTable.forPath(spark, gold_path)\n    \n    # SCD Type 2: Track historical changes\n    merge_condition = "target.customer_id = source.customer_id AND target.is_current = TRUE"\n    \n    gold_table.alias("target").merge(\n        df_gold.alias("source"),\n        merge_condition\n    ).whenMatchedUpdate(\n        condition = "target.customer_name != source.customer_name OR target.email != source.email",\n        set = {\n            "is_current": "FALSE",\n            "end_date": "current_timestamp()"\n        }\n    ).whenNotMatchedInsert(\n        values = {\n            "customer_id": "source.customer_id",\n            "customer_name": "source.customer_name",\n            "email": "source.email",\n            "is_current": "TRUE",\n            "start_date": "current_timestamp()",\n            "end_date": "NULL"\n        }\n    ).execute()\n    \n    logger.info(f"[MERGE] Gold SCD Type 2 merge completed")\nelse:\n    # First load\n    df_gold \\\n        .withColumn("is_current", F.lit(True)) \\\n        .withColumn("start_date", F.current_timestamp()) \\\n        .withColumn("end_date", F.lit(None).cast("timestamp")) \\\n        .write.format("delta").mode("overwrite").save(gold_path)\n    \n    logger.info(f"[CREATE] Gold table created with {df_gold.count()} rows")\n```\n\n### 7. GOLD METADATA COLUMNS\n```python\n# Add Gold layer metadata\ndf_gold_final = df_gold \\\n    .withColumn("_gold_processed_timestamp", F.current_timestamp()) \\\n    .withColumn("_aggregation_level", F.lit(config.get(''aggregation_level'', ''detailed''))) \\\n    .withColumn("_last_refreshed", F.current_timestamp())\n```\n\n### 8. OPTIMIZATION (Gold Layer Specific)\n```python\n# Optimize Gold tables for analytics\nfrom delta.tables import DeltaTable\n\ngold_table = DeltaTable.forPath(spark, gold_path)\n\n# OPTIMIZE and Z-ORDER for query performance\ngold_table.optimize().executeZOrderBy(config.get(''zorder_columns'', [''customer_id'', ''order_date'']))\n\n# VACUUM old versions (optional, configured)\nif config.get(''enable_vacuum'', False):\n    retention_hours = config.get(''vacuum_retention_hours'', 168)  # 7 days default\n    gold_table.vacuum(retention_hours / 24)  # Convert to days\n\nlogger.info(f"[OPTIMIZE] Gold table optimized and z-ordered")\n```\n\n## 🎯 VALIDATION CHECKLIST (Agent F Criteria)\n- ✅ Header: L2L MODERNIZATION TRACE with Gold layer\n- ✅ Read from Silver Delta table(s)\n- ✅ Business logic transformations\n- ✅ Aggregations for fact tables\n- ✅ Dimensional modeling (SCD Type 2 if applicable)\n- ✅ MERGE operation with historical tracking\n- ✅ Gold metadata columns: `_gold_processed_timestamp`, `_aggregation_level`, `_last_refreshed`\n- ✅ Optimization: OPTIMIZE and Z-ORDER\n- ✅ No hardcoded values\n- ✅ Row count logging',
    true,
    'agent-c',
    'fabric',
    'gold',
    '{"description": "Microsoft Fabric Gold Layer cartridge (business-ready aggregated data with Medallion pattern)", "version": "4.0", "created_by": "sprint_14_fabric_fix", "adapted_from": "cartridge_databricks_gold"}'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (prompt_id) DO UPDATE SET
    content = EXCLUDED.content,
    is_active = EXCLUDED.is_active,
    agent_id = EXCLUDED.agent_id,
    tech_stack = EXCLUDED.tech_stack,
    pattern_type = EXCLUDED.pattern_type,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

-- ================================================================
-- VERIFICATION
-- ================================================================

-- Verify all 3 prompts were inserted
SELECT 
    prompt_id,
    agent_id,
    tech_stack,
    pattern_type,
    is_active,
    LENGTH(content) as content_length,
    metadata->>'version' as version,
    metadata->>'adapted_from' as adapted_from,
    created_at
FROM public.utm_prompts
WHERE prompt_id IN (
    'cartridge_fabric_bronze',
    'cartridge_fabric_silver',
    'cartridge_fabric_gold'
)
ORDER BY pattern_type;

-- Expected result:
-- 3 rows with:
-- - prompt_id: cartridge_fabric_bronze, cartridge_fabric_silver, cartridge_fabric_gold
-- - agent_id: agent-c
-- - tech_stack: fabric
-- - pattern_type: bronze, silver, gold
-- - is_active: true
-- - content_length: > 1000 chars each
-- - version: 4.0

-- ================================================================
-- GRANT PERMISSIONS (if RLS enabled)
-- ================================================================
-- Note: These prompts are global (tenant_id is NULL)
-- All authenticated users can READ, only admins can UPDATE/DELETE
