-- ================================================================
-- Sprint 8: Real-Time Validation - Database Schema
-- ================================================================
-- Purpose:
--   Create utm_code_validations table to store validation history
--   Track validation attempts, errors, and test generation results
--
-- Author: Legacy2Lake Engineering
-- Date: 2026-02-11 (Sprint 8)
-- Version: v1.0
-- ================================================================


-- ================================================================
-- 1. CREATE utm_code_validations TABLE
-- ================================================================

CREATE TABLE IF NOT EXISTS utm_code_validations (
    -- Primary key
    validation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Project/Task reference
    project_id UUID NOT NULL,
    task_id UUID NULL,  -- Optional: If validation triggered by specific task
    
    -- Code metadata
    tech_id VARCHAR(50) NOT NULL,  -- pyspark, snowflake, dbt, etc.
    layer VARCHAR(20) NOT NULL DEFAULT 'bronze',  -- bronze, silver, gold
    code_hash VARCHAR(64) NOT NULL,  -- SHA256 hash of code for deduplication
    code_length INT NOT NULL,  -- Length of code in characters
    
    -- Validation results
    is_valid BOOLEAN NOT NULL DEFAULT false,
    errors_count INT NOT NULL DEFAULT 0,
    warnings_count INT NOT NULL DEFAULT 0,
    info_count INT NOT NULL DEFAULT 0,
    
    -- Validation attempts (if retried)
    attempt_number INT NOT NULL DEFAULT 1,
    max_attempts INT NOT NULL DEFAULT 3,
    
    -- Validation details (JSONB for flexibility)
    validation_issues JSONB NULL,  -- Array of ValidationIssue objects
    /*
    Example structure:
    [
        {
            "level": "ERROR",
            "check_name": "python_syntax",
            "message": "Syntax error: unexpected EOF",
            "line_number": 42,
            "suggestion": "Add closing bracket"
        }
    ]
    */
    
    -- Test generation
    test_code_generated BOOLEAN NOT NULL DEFAULT false,
    test_cases_count INT NULL,  -- Number of test cases generated
    
    -- Timestamps
    validated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Tenancy
    tenant_id UUID NOT NULL,
    
    -- Foreign Keys
    CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES utm_projects(project_id) ON DELETE CASCADE,
    CONSTRAINT fk_task FOREIGN KEY (task_id) REFERENCES utm_orchestration_tasks(task_id) ON DELETE CASCADE
);


-- ================================================================
-- 2. INDEXES
-- ================================================================

-- Index on project_id (most common query)
CREATE INDEX idx_code_validations_project ON utm_code_validations(project_id);

-- Index on task_id (task-specific validation history)
CREATE INDEX idx_code_validations_task ON utm_code_validations(task_id);

-- Index on tech_id + layer (technology-specific analytics)
CREATE INDEX idx_code_validations_tech_layer ON utm_code_validations(tech_id, layer);

-- Index on is_valid (filter by pass/fail)
CREATE INDEX idx_code_validations_valid ON utm_code_validations(is_valid);

-- Index on validated_at (time-series queries)
CREATE INDEX idx_code_validations_timestamp ON utm_code_validations(validated_at DESC);

-- Index on tenant_id (multi-tenancy isolation)
CREATE INDEX idx_code_validations_tenant ON utm_code_validations(tenant_id);

-- Index on code_hash (deduplication)
CREATE INDEX idx_code_validations_hash ON utm_code_validations(code_hash);


-- ================================================================
-- 3. ROW LEVEL SECURITY (RLS)
-- ================================================================

-- Enable RLS
ALTER TABLE utm_code_validations ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only access validations in their tenant
CREATE POLICY tenant_validation_isolation ON utm_code_validations
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant_id')::uuid);


-- ================================================================
-- 4. COMMENTS
-- ================================================================

COMMENT ON TABLE utm_code_validations IS 'Sprint 8: Stores validation history for code generated by Agent C. Tracks validation attempts, errors, warnings, and test case generation.';

COMMENT ON COLUMN utm_code_validations.validation_id IS 'Primary key (UUID)';
COMMENT ON COLUMN utm_code_validations.project_id IS 'Reference to utm_projects';
COMMENT ON COLUMN utm_code_validations.task_id IS 'Reference to utm_orchestration_tasks (optional)';
COMMENT ON COLUMN utm_code_validations.tech_id IS 'Technology ID (pyspark, snowflake, dbt, fabric, aws, gcp, generic, salesforce)';
COMMENT ON COLUMN utm_code_validations.layer IS 'Medallion layer (bronze, silver, gold)';
COMMENT ON COLUMN utm_code_validations.code_hash IS 'SHA256 hash of code for deduplication';
COMMENT ON COLUMN utm_code_validations.code_length IS 'Length of code in characters';
COMMENT ON COLUMN utm_code_validations.is_valid IS 'True if validation passed (no errors)';
COMMENT ON COLUMN utm_code_validations.errors_count IS 'Number of ERROR-level issues';
COMMENT ON COLUMN utm_code_validations.warnings_count IS 'Number of WARNING-level issues';
COMMENT ON COLUMN utm_code_validations.info_count IS 'Number of INFO-level issues';
COMMENT ON COLUMN utm_code_validations.attempt_number IS 'Validation attempt number (1-based)';
COMMENT ON COLUMN utm_code_validations.max_attempts IS 'Maximum validation attempts allowed';
COMMENT ON COLUMN utm_code_validations.validation_issues IS 'JSONB array of ValidationIssue objects';
COMMENT ON COLUMN utm_code_validations.test_code_generated IS 'True if test cases were generated';
COMMENT ON COLUMN utm_code_validations.test_cases_count IS 'Number of test cases generated';
COMMENT ON COLUMN utm_code_validations.validated_at IS 'Validation timestamp';
COMMENT ON COLUMN utm_code_validations.tenant_id IS 'Tenant ID for RLS';


-- ================================================================
-- 5. SAMPLE QUERY: Project Validation Statistics
-- ================================================================

/*
-- Get validation statistics for a project
SELECT 
    project_id,
    tech_id,
    layer,
    COUNT(*) AS total_validations,
    SUM(CASE WHEN is_valid THEN 1 ELSE 0 END) AS passed,
    SUM(CASE WHEN NOT is_valid THEN 1 ELSE 0 END) AS failed,
    ROUND(100.0 * SUM(CASE WHEN is_valid THEN 1 ELSE 0 END) / COUNT(*), 2) AS pass_rate,
    AVG(errors_count) AS avg_errors,
    AVG(warnings_count) AS avg_warnings,
    AVG(attempt_number) AS avg_attempts
FROM utm_code_validations
WHERE project_id = '...'
GROUP BY project_id, tech_id, layer
ORDER BY pass_rate DESC;
*/


-- ================================================================
-- 6. SAMPLE QUERY: Most Common Validation Errors
-- ================================================================

/*
-- Get most common validation errors across all projects
SELECT 
    issue->>'check_name' AS check_name,
    issue->>'level' AS level,
    COUNT(*) AS occurrences
FROM utm_code_validations,
     jsonb_array_elements(validation_issues) AS issue
WHERE NOT is_valid
GROUP BY issue->>'check_name', issue->>'level'
ORDER BY occurrences DESC
LIMIT 10;
*/


-- ================================================================
-- 7. SAMPLE QUERY: Validation Timeline
-- ================================================================

/*
-- Get validation timeline for a project (last 30 days)
SELECT 
    DATE(validated_at) AS date,
    COUNT(*) AS total,
    SUM(CASE WHEN is_valid THEN 1 ELSE 0 END) AS passed,
    SUM(CASE WHEN NOT is_valid THEN 1 ELSE 0 END) AS failed,
    ROUND(100.0 * SUM(CASE WHEN is_valid THEN 1 ELSE 0 END) / COUNT(*), 2) AS pass_rate
FROM utm_code_validations
WHERE project_id = '...'
  AND validated_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(validated_at)
ORDER BY date DESC;
*/


-- ================================================================
-- 8. CLEANUP (ROLLBACK)
-- ================================================================

/*
-- To rollback this migration:

DROP POLICY IF EXISTS tenant_validation_isolation ON utm_code_validations;
DROP TABLE IF EXISTS utm_code_validations CASCADE;
*/
