-- ================================================================
-- Sprint 14 Fix: Add Missing Cartridge Prompts for ALL Destinations
-- Date: 2026-02-20
-- ================================================================
-- Problem: Projects with target technologies other than Databricks/Fabric
--          get 404 errors when loading cartridge prompts
-- Solution: Insert Bronze/Silver/Gold cartridges for:
--           - Snowflake (SQL-based)
--           - BigQuery (SQL-based)
--           - AWS Glue (PySpark-based)
--           - Redshift (SQL-based)
-- ================================================================

-- ================================================================
-- SNOWFLAKE CARTRIDGES (SQL-Based)
-- ================================================================

-- 1. Snowflake Bronze
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_snowflake_bronze',
    E'# Snowflake SQL Bronze Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS (Zero-Hardcode Policy)\n\n### 1. MANDATORY L2L MODERNIZATION TRACE HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Bronze Layer - {{asset_name}}\n-- ================================================================\n-- Source Asset: {{source_asset_name}}\n-- Source Technology: {{source_tech}}\n-- Target Platform: Snowflake (SQL + Snowpipe)\n-- Medallion Layer: Bronze\n-- Component Type: Data Pipeline\n-- Business Entity: {{business_entity}}\n-- Load Strategy: {{load_strategy}}\n-- Generated At: {{timestamp}}\n-- Generated By: L2L Agent-C (Cartridge: SnowflakeBronze v4.0)\n-- ================================================================\n```\n\n### 2. ZERO-HARDCODE CONFIGURATION\n**❌ FORBIDDEN:**\n- NO hardcoded database/schema: `USE DATABASE production;`\n- NO hardcoded table names: `INSERT INTO bronze.customers`\n- NO hardcoded credentials in COPY commands\n\n**✅ REQUIRED: Use variables from orchestrator**\n```sql\n-- Variables injected by orchestrator\nSET bronze_database = ''{{ bronze_database }}'';\nSET bronze_schema = ''{{ bronze_schema }}'';\nSET bronze_table = ''{{ bronze_table }}'';\nSET source_stage = ''{{ source_stage }}'';\n```\n\n### 3. BRONZE LAYER PATTERN\n```sql\n-- Create Bronze table with metadata columns\nCREATE TABLE IF NOT EXISTS IDENTIFIER($bronze_database || ''.'' || $bronze_schema || ''.'' || $bronze_table) (\n    -- Source columns (from metadata)\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    \n    -- Bronze metadata columns\n    _ingestion_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),\n    _source_file VARCHAR,\n    _record_hash VARCHAR(64)\n);\n\n-- Load data using COPY INTO (idempotent)\nCOPY INTO IDENTIFIER($bronze_database || ''.'' || $bronze_schema || ''.'' || $bronze_table)\nFROM @IDENTIFIER($source_stage)\nFILE_FORMAT = (TYPE = ''CSV'' SKIP_HEADER = 1)\nON_ERROR = ''CONTINUE''\nFORCE = FALSE;  -- Prevents duplicate loads\n\n-- Track row counts\nSELECT ''LOADED'' AS status, COUNT(*) AS row_count \nFROM IDENTIFIER($bronze_database || ''.'' || $bronze_schema || ''.'' || $bronze_table)\nWHERE _ingestion_timestamp >= DATEADD(minute, -5, CURRENT_TIMESTAMP());\n```\n\n### 4. VALIDATION CHECKLIST\n- ✅ Header with L2L MODERNIZATION TRACE\n- ✅ No hardcoded database/schema/table names\n- ✅ Bronze metadata: `_ingestion_timestamp`, `_source_file`, `_record_hash`\n- ✅ COPY INTO with FORCE=FALSE (idempotent)\n- ✅ Row count tracking',
    true, 'agent-c', 'snowflake', 'bronze',
    '{"description": "Snowflake Bronze Layer cartridge (raw data ingestion with Medallion pattern)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 2. Snowflake Silver
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_snowflake_silver',
    E'# Snowflake SQL Silver Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Silver Layer - {{asset_name}}\n-- Target Platform: Snowflake (SQL)\n-- Medallion Layer: Silver\n-- ================================================================\n```\n\n### 2. SILVER LAYER PATTERN (Cleansing + Deduplication)\n```sql\n-- Create Silver table\nCREATE TABLE IF NOT EXISTS IDENTIFIER($silver_database || ''.'' || $silver_schema || ''.'' || $silver_table) (\n    -- Business columns\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    \n    -- Silver metadata\n    _processed_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),\n    _is_current BOOLEAN DEFAULT TRUE,\n    _silver_layer VARCHAR DEFAULT ''silver''\n);\n\n-- MERGE for SCD Type 1\nMERGE INTO IDENTIFIER($silver_database || ''.'' || $silver_schema || ''.'' || $silver_table) AS target\nUSING (\n    SELECT DISTINCT\n        *,\n        ROW_NUMBER() OVER (PARTITION BY {{business_key}} ORDER BY _ingestion_timestamp DESC) AS rn\n    FROM IDENTIFIER($bronze_database || ''.'' || $bronze_schema || ''.'' || $bronze_table)\n    WHERE _ingestion_timestamp > $last_run_timestamp\n) AS source\nON {{#each business_keys}}target.{{this}} = source.{{this}}{{#unless @last}} AND {{/unless}}{{/each}}\nWHEN MATCHED THEN UPDATE SET *\nWHEN NOT MATCHED THEN INSERT *;\n```\n\n### 3. VALIDATION\n- ✅ Read from Bronze table\n- ✅ Deduplication using business keys\n- ✅ MERGE operation for SCD Type 1\n- ✅ Silver metadata columns',
    true, 'agent-c', 'snowflake', 'silver',
    '{"description": "Snowflake Silver Layer cartridge (cleaned and deduplicated)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 3. Snowflake Gold
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_snowflake_gold',
    E'# Snowflake SQL Gold Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Gold Layer - {{asset_name}}\n-- Target Platform: Snowflake (SQL)\n-- Medallion Layer: Gold\n-- ================================================================\n```\n\n### 2. GOLD LAYER PATTERN (Aggregations + Business Logic)\n```sql\n-- Create Gold table (Fact/Dimension)\nCREATE TABLE IF NOT EXISTS IDENTIFIER($gold_database || ''.'' || $gold_schema || ''.'' || $gold_table) (\n    -- Dimension/Fact columns\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    \n    -- Gold metadata\n    _gold_processed_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),\n    _aggregation_level VARCHAR,\n    _last_refreshed TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()\n);\n\n-- Insert aggregated data\nINSERT INTO IDENTIFIER($gold_database || ''.'' || $gold_schema || ''.'' || $gold_table)\nSELECT\n    -- Business logic transformations\n    {{#each aggregations}}\n    {{expression}} AS {{alias}},\n    {{/each}}\n    CURRENT_TIMESTAMP() AS _gold_processed_timestamp,\n    ''{{aggregation_level}}'' AS _aggregation_level,\n    CURRENT_TIMESTAMP() AS _last_refreshed\nFROM IDENTIFIER($silver_database || ''.'' || $silver_schema || ''.'' || $silver_table)\nGROUP BY {{group_by_columns}};\n```\n\n### 3. VALIDATION\n- ✅ Read from Silver table(s)\n- ✅ Business logic aggregations\n- ✅ Gold metadata columns\n- ✅ Optimized for analytics',
    true, 'agent-c', 'snowflake', 'gold',
    '{"description": "Snowflake Gold Layer cartridge (business-ready aggregated data)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- ================================================================
-- BIGQUERY CARTRIDGES (SQL-Based)
-- ================================================================

-- 4. BigQuery Bronze
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_bigquery_bronze',
    E'# BigQuery SQL Bronze Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Bronze Layer - {{asset_name}}\n-- Target Platform: BigQuery (SQL)\n-- Medallion Layer: Bronze\n-- ================================================================\n```\n\n### 2. BRONZE LAYER PATTERN\n```sql\n-- Create Bronze table\nCREATE TABLE IF NOT EXISTS `{{ project_id }}.{{ bronze_dataset }}.{{ bronze_table }}` (\n    -- Source columns\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    \n    -- Bronze metadata\n    _ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),\n    _source_file STRING,\n    _record_hash STRING\n)\nPARTITION BY DATE(_ingestion_timestamp)\nCLUSTER BY {{ cluster_columns }};\n\n-- Load data from Cloud Storage\nLOAD DATA INTO `{{ project_id }}.{{ bronze_dataset }}.{{ bronze_table }}`\nFROM FILES (\n    format = ''CSV'',\n    uris = [''{{ gcs_uri }}'']\n);\n\n-- Track row counts\nSELECT ''LOADED'' AS status, COUNT(*) AS row_count\nFROM `{{ project_id }}.{{ bronze_dataset }}.{{ bronze_table }}`\nWHERE _ingestion_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 MINUTE);\n```\n\n### 3. VALIDATION\n- ✅ No hardcoded project/dataset/table\n- ✅ Partitioned by _ingestion_timestamp\n- ✅ Bronze metadata columns',
    true, 'agent-c', 'bigquery', 'bronze',
    '{"description": "BigQuery Bronze Layer cartridge (raw data ingestion)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 5. BigQuery Silver
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_bigquery_silver',
    E'# BigQuery SQL Silver Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Silver Layer - {{asset_name}}\n-- Target Platform: BigQuery (SQL)\n-- Medallion Layer: Silver\n-- ================================================================\n```\n\n### 2. SILVER LAYER PATTERN\n```sql\n-- Create Silver table\nCREATE TABLE IF NOT EXISTS `{{ project_id }}.{{ silver_dataset }}.{{ silver_table }}` (\n    -- Business columns\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    _processed_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),\n    _is_current BOOL DEFAULT TRUE\n)\nPARTITION BY DATE(_processed_timestamp);\n\n-- MERGE for SCD Type 1\nMERGE `{{ project_id }}.{{ silver_dataset }}.{{ silver_table }}` AS target\nUSING (\n    SELECT * FROM (\n        SELECT *, ROW_NUMBER() OVER (PARTITION BY {{business_key}} ORDER BY _ingestion_timestamp DESC) AS rn\n        FROM `{{ project_id }}.{{ bronze_dataset }}.{{ bronze_table }}`\n    ) WHERE rn = 1\n) AS source\nON {{merge_condition}}\nWHEN MATCHED THEN UPDATE SET *\nWHEN NOT MATCHED THEN INSERT *;\n```',
    true, 'agent-c', 'bigquery', 'silver',
    '{"description": "BigQuery Silver Layer cartridge (cleaned and deduplicated)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 6. BigQuery Gold
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_bigquery_gold',
    E'# BigQuery SQL Gold Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Gold Layer - {{asset_name}}\n-- Target Platform: BigQuery (SQL)\n-- Medallion Layer: Gold\n-- ================================================================\n```\n\n### 2. GOLD LAYER PATTERN\n```sql\nCREATE TABLE IF NOT EXISTS `{{ project_id }}.{{ gold_dataset }}.{{ gold_table }}` AS\nSELECT\n    {{#each aggregations}}\n    {{expression}} AS {{alias}},\n    {{/each}}\n    CURRENT_TIMESTAMP() AS _gold_processed_timestamp\nFROM `{{ project_id }}.{{ silver_dataset }}.{{ silver_table }}`\nGROUP BY {{group_by_columns}};\n```',
    true, 'agent-c', 'bigquery', 'gold',
    '{"description": "BigQuery Gold Layer cartridge (business-ready aggregated data)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- ================================================================
-- AWS GLUE CARTRIDGES (PySpark-Based - Similar to Databricks)
-- ================================================================

-- 7. AWS Glue Bronze
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_aws_glue_bronze',
    E'# AWS Glue PySpark Bronze Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```python\n# ================================================================\n# L2L MODERNIZATION TRACE: Bronze Layer - {{asset_name}}\n# Target Platform: AWS Glue (PySpark + S3)\n# Medallion Layer: Bronze\n# ================================================================\n```\n\n### 2. AWS GLUE PATTERN\n```python\nimport sys\nfrom awsglue.transforms import *\nfrom awsglue.utils import getResolvedOptions\nfrom pyspark.context import SparkContext\nfrom awsglue.context import GlueContext\nfrom awsglue.job import Job\nfrom pyspark.sql import functions as F\n\nargs = getResolvedOptions(sys.argv, [''JOB_NAME'', ''bronze_path'', ''source_database'', ''source_table''])\n\nsc = SparkContext()\nglueContext = GlueContext(sc)\nspark = glueContext.spark_session\njob = Job(glueContext)\njob.init(args[''JOB_NAME''], args)\n\n# Read from Glue Data Catalog\ndf = glueContext.create_dynamic_frame.from_catalog(\n    database=args[''source_database''],\n    table_name=args[''source_table'']\n).toDF()\n\n# Add Bronze metadata\ndf_bronze = df \\\n    .withColumn("_ingestion_timestamp", F.current_timestamp()) \\\n    .withColumn("_source_file", F.lit(args.get(''source_file'', ''N/A''))) \\\n    .withColumn("_record_hash", F.sha2(F.concat_ws("||", *df.columns), 256))\n\n# Write to S3 as Parquet\ndf_bronze.write \\\n    .format("parquet") \\\n    .mode("append") \\\n    .save(args[''bronze_path''])\n\njob.commit()\n```\n\n### 3. VALIDATION\n- ✅ AWS Glue Context initialization\n- ✅ Read from Glue Data Catalog\n- ✅ Bronze metadata columns\n- ✅ Write to S3',
    true, 'agent-c', 'aws_glue', 'bronze',
    '{"description": "AWS Glue Bronze Layer cartridge (raw data ingestion)", "version": "4.0", "pyspark_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 8. AWS Glue Silver
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_aws_glue_silver',
    E'# AWS Glue PySpark Silver Layer Cartridge Rules\n\n## 🎯 SILVER LAYER PATTERN\n\n```python\nfrom awsglue.transforms import *\nfrom pyspark.sql.window import Window\n\n# Read from Bronze\ndf_bronze = spark.read.parquet(args[''bronze_path''])\n\n# Deduplication\nbusiness_keys = args[''business_keys''].split('','')\nwindow_spec = Window.partitionBy(*business_keys).orderBy(F.col("_ingestion_timestamp").desc())\n\ndf_silver = df_bronze \\\n    .withColumn("row_num", F.row_number().over(window_spec)) \\\n    .filter(F.col("row_num") == 1) \\\n    .drop("row_num") \\\n    .withColumn("_processed_timestamp", F.current_timestamp())\n\n# Write to S3\ndf_silver.write.format("parquet").mode("overwrite").save(args[''silver_path''])\n```',
    true, 'agent-c', 'aws_glue', 'silver',
    '{"description": "AWS Glue Silver Layer cartridge (cleaned and deduplicated)", "version": "4.0", "pyspark_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 9. AWS Glue Gold
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_aws_glue_gold',
    E'# AWS Glue PySpark Gold Layer Cartridge Rules\n\n## 🎯 GOLD LAYER PATTERN\n\n```python\n# Read from Silver\ndf_silver = spark.read.parquet(args[''silver_path''])\n\n# Apply business logic aggregations\ndf_gold = df_silver.groupBy(args[''group_by_columns''].split('','')) \\\n    .agg(*[eval(agg) for agg in args[''aggregations''].split('';'')]) \\\n    .withColumn("_gold_processed_timestamp", F.current_timestamp())\n\n# Write to S3\ndf_gold.write.format("parquet").mode("overwrite").save(args[''gold_path''])\n```',
    true, 'agent-c', 'aws_glue', 'gold',
    '{"description": "AWS Glue Gold Layer cartridge (business-ready aggregated data)", "version": "4.0", "pyspark_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- ================================================================
-- REDSHIFT CARTRIDGES (SQL-Based)
-- ================================================================

-- 10. Redshift Bronze
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_redshift_bronze',
    E'# Redshift SQL Bronze Layer Cartridge Rules\n\n## 🎯 CRITICAL COMPLIANCE REQUIREMENTS\n\n### 1. HEADER\n```sql\n-- ================================================================\n-- L2L MODERNIZATION TRACE: Bronze Layer - {{asset_name}}\n-- Target Platform: AWS Redshift (SQL)\n-- Medallion Layer: Bronze\n-- ================================================================\n```\n\n### 2. BRONZE LAYER PATTERN\n```sql\n-- Create Bronze table with distribution key\nCREATE TABLE IF NOT EXISTS {{ bronze_schema }}.{{ bronze_table }} (\n    -- Source columns\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    \n    -- Bronze metadata\n    _ingestion_timestamp TIMESTAMP DEFAULT GETDATE(),\n    _source_file VARCHAR(500),\n    _record_hash VARCHAR(64)\n)\nDISTKEY({{ distribution_key }})\nSORTKEY(_ingestion_timestamp);\n\n-- COPY from S3\nCOPY {{ bronze_schema }}.{{ bronze_table }}\nFROM ''{{ s3_uri }}''\nIAM_ROLE ''{{ iam_role }}''\nFORMAT AS CSV\nIGNOREHEADER 1\nTIMEFORMAT ''auto'';\n\n-- Track row counts\nSELECT ''LOADED'' AS status, COUNT(*) AS row_count\nFROM {{ bronze_schema }}.{{ bronze_table }}\nWHERE _ingestion_timestamp >= DATEADD(minute, -5, GETDATE());\n```\n\n### 3. VALIDATION\n- ✅ DISTKEY for distribution\n- ✅ SORTKEY for query performance\n- ✅ COPY command from S3',
    true, 'agent-c', 'redshift', 'bronze',
    '{"description": "Redshift Bronze Layer cartridge (raw data ingestion)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 11. Redshift Silver
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_redshift_silver',
    E'# Redshift SQL Silver Layer Cartridge Rules\n\n## 🎯 SILVER LAYER PATTERN\n\n```sql\nCREATE TABLE IF NOT EXISTS {{ silver_schema }}.{{ silver_table }} (\n    {{#each columns}}\n    {{name}} {{data_type}},\n    {{/each}}\n    _processed_timestamp TIMESTAMP DEFAULT GETDATE(),\n    _is_current BOOLEAN DEFAULT TRUE\n)\nDISTKEY({{ distribution_key }})\nSORTKEY({{ business_key }});\n\n-- Merge logic (Redshift doesn''t support MERGE, use DELETE+INSERT)\nBEGIN TRANSACTION;\n\nDELETE FROM {{ silver_schema }}.{{ silver_table }}\nWHERE {{ business_key }} IN (\n    SELECT DISTINCT {{ business_key }}\n    FROM {{ bronze_schema }}.{{ bronze_table }}\n    WHERE _ingestion_timestamp > ''{{ last_run_timestamp }}''\n);\n\nINSERT INTO {{ silver_schema }}.{{ silver_table }}\nSELECT DISTINCT ON ({{ business_key }})\n    *,\n    GETDATE() AS _processed_timestamp,\n    TRUE AS _is_current\nFROM {{ bronze_schema }}.{{ bronze_table }}\nWHERE _ingestion_timestamp > ''{{ last_run_timestamp }}''\nORDER BY {{ business_key }}, _ingestion_timestamp DESC;\n\nCOMMIT;\n```',
    true, 'agent-c', 'redshift', 'silver',
    '{"description": "Redshift Silver Layer cartridge (cleaned and deduplicated)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- 12. Redshift Gold
INSERT INTO public.utm_prompts (
    prompt_id, content, is_active, agent_id, tech_stack, pattern_type, metadata, created_at, updated_at
) VALUES (
    'cartridge_redshift_gold',
    E'# Redshift SQL Gold Layer Cartridge Rules\n\n## 🎯 GOLD LAYER PATTERN\n\n```sql\nCREATE TABLE IF NOT EXISTS {{ gold_schema }}.{{ gold_table }} AS\nSELECT\n    {{#each aggregations}}\n    {{expression}} AS {{alias}},\n    {{/each}}\n    GETDATE() AS _gold_processed_timestamp\nFROM {{ silver_schema }}.{{ silver_table }}\nGROUP BY {{group_by_columns}};\n\n-- Optimize with VACUUM and ANALYZE\nVACUUM {{ gold_schema }}.{{ gold_table }};\nANALYZE {{ gold_schema }}.{{ gold_table }};\n```',
    true, 'agent-c', 'redshift', 'gold',
    '{"description": "Redshift Gold Layer cartridge (business-ready aggregated data)", "version": "4.0", "sql_based": true}'::jsonb,
    NOW(), NOW()
) ON CONFLICT (prompt_id) DO UPDATE SET content = EXCLUDED.content, updated_at = NOW();

-- ================================================================
-- VERIFICATION
-- ================================================================

-- Verify all cartridges were inserted
SELECT 
    tech_stack,
    pattern_type,
    COUNT(*) as cartridge_count
FROM public.utm_prompts
WHERE prompt_id LIKE 'cartridge_%'
GROUP BY tech_stack, pattern_type
ORDER BY tech_stack, pattern_type;

-- Expected result:
-- tech_stack     | pattern_type | cartridge_count
-- ---------------+--------------+----------------
-- aws_glue       | bronze       | 1
-- aws_glue       | gold         | 1
-- aws_glue       | silver       | 1
-- bigquery       | bronze       | 1
-- bigquery       | gold         | 1
-- bigquery       | silver       | 1
-- databricks     | bronze       | 1
-- databricks     | direct       | 1
-- databricks     | gold         | 1
-- databricks     | silver       | 1
-- fabric         | bronze       | 1
-- fabric         | gold         | 1
-- fabric         | silver       | 1
-- pyspark        | direct       | 1
-- redshift       | bronze       | 1
-- redshift       | gold         | 1
-- redshift       | silver       | 1
-- snowflake      | bronze       | 1
-- snowflake      | gold         | 1
-- snowflake      | silver       | 1

-- Total: 20 cartridges

-- List all cartridge prompts
SELECT 
    prompt_id,
    tech_stack,
    pattern_type,
    LENGTH(content) as chars,
    metadata->>'sql_based' as sql_based,
    metadata->>'pyspark_based' as pyspark_based,
    is_active
FROM public.utm_prompts
WHERE prompt_id LIKE 'cartridge_%'
ORDER BY tech_stack, pattern_type;
