"""
Sprint 8 Migration Runner - utm_code_validations Table
=======================================================

Purpose:
    Applies Sprint 8 database migration to create utm_code_validations table.
    This table stores real-time validation history for code generated by Agent C.

Features:
    - Reads migration SQL file
    - Provides manual execution instructions
    - Verifies table creation
    - Tests insert functionality
    - Clean rollback option

Usage:
    python apply_sprint8_migration.py

Author: Legacy2Lake Engineering
Date: 2026-02-11 (Sprint 8)
Version: v1.0
"""

import os
import sys
import json
from datetime import datetime
from supabase import create_client, Client

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from apps.api.services.persistence_service import SupabasePersistence
except ImportError:
    # Fallback for standalone execution
    pass


# ================================================================
# CONFIGURATION
# ================================================================

MIGRATION_FILE = "migrations/sprint8_code_validations_table.sql"
TABLE_NAME = "utm_code_validations"


# ================================================================
# HELPER FUNCTIONS
# ================================================================

def load_migration_sql():
    """Load migration SQL file"""
    migration_path = os.path.join(os.path.dirname(__file__), MIGRATION_FILE)
    
    if not os.path.exists(migration_path):
        print(f"❌ Migration file not found: {migration_path}")
        sys.exit(1)
    
    with open(migration_path, 'r', encoding='utf-8') as f:
        sql_content = f.read()
    
    print(f"✅ Loaded migration file: {migration_path}")
    print(f"   SQL size: {len(sql_content)} characters\n")
    
    return sql_content


def get_supabase_client():
    """Get Supabase client"""
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_KEY")
    
    if not url or not key:
        print("❌ SUPABASE_URL and SUPABASE_KEY environment variables required")
        print("\nPlease set them in your .env file:")
        print("  SUPABASE_URL=https://your-project.supabase.co")
        print("  SUPABASE_KEY=your-anon-key")
        sys.exit(1)
    
    client = create_client(url, key)
    print(f"✅ Connected to Supabase: {url}\n")
    
    return client


def verify_table_exists(client: Client):
    """Verify utm_code_validations table exists"""
    try:
        # Query with limit 0 to just check if table exists
        response = client.table(TABLE_NAME).select("validation_id").limit(0).execute()
        
        print(f"✅ Table '{TABLE_NAME}' exists and is accessible\n")
        return True
    
    except Exception as e:
        print(f"❌ Table '{TABLE_NAME}' does not exist or is not accessible")
        print(f"   Error: {str(e)}\n")
        return False


def test_insert(client: Client, tenant_id: str, project_id: str):
    """Test insert into utm_code_validations"""
    try:
        # Generate test validation record
        test_record = {
            'project_id': project_id,
            'task_id': None,
            'tech_id': 'pyspark',
            'layer': 'bronze',
            'code_hash': 'test_hash_' + datetime.utcnow().isoformat(),
            'code_length': 500,
            'is_valid': True,
            'errors_count': 0,
            'warnings_count': 1,
            'info_count': 2,
            'attempt_number': 1,
            'max_attempts': 3,
            'validation_issues': json.dumps([
                {
                    'level': 'WARNING',
                    'check_name': 'no_comments',
                    'message': 'No comments found in code',
                    'suggestion': 'Add comments to explain logic'
                }
            ]),
            'test_code_generated': True,
            'test_cases_count': 3,
            'tenant_id': tenant_id
        }
        
        response = client.table(TABLE_NAME).insert(test_record).execute()
        
        if response.data:
            validation_id = response.data[0]['validation_id']
            print(f"✅ Test insert successful!")
            print(f"   validation_id: {validation_id}")
            print(f"   tech_id: {test_record['tech_id']}")
            print(f"   layer: {test_record['layer']}")
            print(f"   is_valid: {test_record['is_valid']}")
            print(f"   errors_count: {test_record['errors_count']}")
            print(f"   warnings_count: {test_record['warnings_count']}\n")
            
            return validation_id
        else:
            print("❌ Test insert failed: No data returned\n")
            return None
    
    except Exception as e:
        print(f"❌ Test insert failed: {str(e)}\n")
        return None


def test_query(client: Client, validation_id: str):
    """Test query utm_code_validations"""
    try:
        response = client.table(TABLE_NAME).select("*").eq("validation_id", validation_id).execute()
        
        if response.data:
            record = response.data[0]
            print(f"✅ Test query successful!")
            print(f"   Retrieved validation_id: {record['validation_id']}")
            print(f"   tech_id: {record['tech_id']}")
            print(f"   is_valid: {record['is_valid']}")
            print(f"   validated_at: {record['validated_at']}\n")
            
            return True
        else:
            print("❌ Test query failed: No data returned\n")
            return False
    
    except Exception as e:
        print(f"❌ Test query failed: {str(e)}\n")
        return False


def cleanup_test_data(client: Client, validation_id: str):
    """Delete test validation record"""
    try:
        response = client.table(TABLE_NAME).delete().eq("validation_id", validation_id).execute()
        print(f"✅ Test data cleaned up (validation_id: {validation_id})\n")
    except Exception as e:
        print(f"❌ Cleanup failed: {str(e)}\n")


# ================================================================
# MAIN EXECUTION
# ================================================================

def main():
    print("=" * 70)
    print("Sprint 8 Migration Runner - utm_code_validations Table")
    print("=" * 70)
    print()
    
    # Step 1: Load SQL
    sql_content = load_migration_sql()
    
    # Step 2: Connect to Supabase
    client = get_supabase_client()
    
    # Step 3: Display manual execution instructions
    print("=" * 70)
    print("MANUAL SQL EXECUTION REQUIRED")
    print("=" * 70)
    print()
    print("⚠️  Supabase Python client does not support DDL operations.")
    print("   You must run the SQL manually using one of these methods:\n")
    
    print("Option 1: Supabase Dashboard (Recommended)")
    print("-" * 70)
    print("1. Go to: https://supabase.com/dashboard")
    print("2. Select your project")
    print("3. Navigate to: SQL Editor")
    print("4. Create a new query")
    print("5. Paste the SQL from: migrations/sprint8_code_validations_table.sql")
    print("6. Click 'Run' to execute\n")
    
    print("Option 2: psql (PostgreSQL CLI)")
    print("-" * 70)
    print("psql -h <your-db-host> -U postgres -d postgres -f migrations/sprint8_code_validations_table.sql\n")
    
    print("Option 3: DBeaver / pgAdmin")
    print("-" * 70)
    print("1. Connect to your Supabase database")
    print("2. Open SQL editor")
    print("3. Paste the SQL from: migrations/sprint8_code_validations_table.sql")
    print("4. Execute\n")
    
    print("=" * 70)
    print()
    
    # Step 4: Wait for user to run SQL
    input("Press ENTER after you have executed the SQL manually...")
    print()
    
    # Step 5: Verify table exists
    print("=" * 70)
    print("VERIFICATION")
    print("=" * 70)
    print()
    
    if not verify_table_exists(client):
        print("❌ Migration verification failed. Please run the SQL manually.\n")
        sys.exit(1)
    
    # Step 6: Test insert
    print("=" * 70)
    print("TESTING INSERT")
    print("=" * 70)
    print()
    
    # Get tenant_id and project_id from environment or use defaults
    tenant_id = os.getenv("TEST_TENANT_ID", "00000000-0000-0000-0000-000000000001")
    project_id = os.getenv("TEST_PROJECT_ID", "00000000-0000-0000-0000-000000000002")
    
    print(f"Using test tenant_id: {tenant_id}")
    print(f"Using test project_id: {project_id}\n")
    
    validation_id = test_insert(client, tenant_id, project_id)
    
    if not validation_id:
        print("❌ Insert test failed. Check table structure and RLS policies.\n")
        sys.exit(1)
    
    # Step 7: Test query
    print("=" * 70)
    print("TESTING QUERY")
    print("=" * 70)
    print()
    
    if not test_query(client, validation_id):
        print("❌ Query test failed. Check RLS policies.\n")
        sys.exit(1)
    
    # Step 8: Cleanup
    print("=" * 70)
    print("CLEANUP")
    print("=" * 70)
    print()
    
    cleanup_test_data(client, validation_id)
    
    # Step 9: Success!
    print("=" * 70)
    print("MIGRATION COMPLETE")
    print("=" * 70)
    print()
    print("✅ Sprint 8 migration applied successfully!")
    print()
    print("Summary:")
    print(f"  - Table created: {TABLE_NAME}")
    print("  - Indexes created: 7")
    print("  - RLS enabled: Yes")
    print("  - Test insert: ✅ PASSED")
    print("  - Test query: ✅ PASSED")
    print()
    print("Next steps:")
    print("  - Validation Service is now ready to store validation history")
    print("  - API endpoints can query validation stats")
    print("  - Agent C will automatically log validation attempts")
    print()
    print("=" * 70)


if __name__ == "__main__":
    main()
