-- Migration: Add missing agents to utm_agent_catalog
-- Agent B (Cartographer) and Agent D (Auditor)
-- Date: 2026-02-09

-- Add Agent B
INSERT INTO utm_agent_catalog (agent_id, name, display_name, description, role_description, is_active)
VALUES (
    'agent-b',
    'Agent B (Cartographer)',
    'Cartographer Agent',
    'Translates legacy control flow and data flow structures into a modern lineage mesh. Builds execution graphs and precedence constraints for orchestration.',
    'Lineage & Mesh builder',
    TRUE
)
ON CONFLICT (agent_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    role_description = EXCLUDED.role_description,
    is_active = EXCLUDED.is_active;

-- Add Agent D  
INSERT INTO utm_agent_catalog (agent_id, name, display_name, description, role_description, is_active)
VALUES (
    'agent-d',
    'Agent D (Auditor)',
    'Architectural Auditor',
    'Reviews modernized code generated by other agents and certifies cloud architecture compliance. Validates Databricks and PySpark best practices.',
    'Senior Cloud Architecture Auditor',
    TRUE
)
ON CONFLICT (agent_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    role_description = EXCLUDED.role_description,
    is_active = EXCLUDED.is_active;

-- Verify all agents
SELECT 
    agent_id,
    display_name,
    LEFT(description, 60) as description_preview,
    is_active
FROM utm_agent_catalog
ORDER BY agent_id;
