
name: 'migration_base2'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  migration_base2:
    Bronze:
      +materialized: view
      +schema: bronze
    Silver:
      +materialized: table
      +file_format: delta
      +schema: silver
    Gold:
      +materialized: table
      +schema: gold
