# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
-- BRONZE LAYER (Staging)
-- Generated by Shift-T Architect Agent
-- Source: DimShipper.py

with source as (
    select * from {{ source('legacy_source', 'DimShipper') }}
),

renamed as (
    select
        *,
        current_timestamp() as _ingested_at
    from source
)

select * from renamed
