# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
-- GOLD LAYER (Marts/Business)
-- Type: DIMENSION
-- Generated by Shift-T Architect Agent

with silver as (
    select * from {{ ref('stg_DimCustomers') }}
)

select * from silver
