"""
GitHub Push Service
Pushes generated migration artifacts to a GitHub repository and optionally creates a PR.

Usage:
    service = GitHubPushService(tenant_id=tenant_id)
    result = await service.push_artifacts(
        project_id="my-project",
        storage=storage,
        base_path="solutions/tenant/my-project",
        repo_url="https://github.com/org/repo",
        token="ghp_xxxx",
        branch="legacy2lake-migration",
        target_path="modernized/",
        commit_message="Legacy2Lake: Add modernized PySpark code",
        create_pr=True,
        pr_title="[Legacy2Lake] Modernization artifacts",
        pr_body="Automated migration artifacts generated by Legacy2Lake UTM v4.0"
    )
"""

import os
import shutil
import subprocess
import tempfile
import json
import re
from typing import Optional, Dict, Any, List
from pathlib import Path
from datetime import datetime

try:
    import httpx
except ImportError:
    httpx = None

try:
    from apps.api.utils.logger import logger
    from apps.api.services.persistence_service import PersistenceService
except ImportError:
    try:
        from utils.logger import logger
        from services.persistence_service import PersistenceService
    except ImportError:
        from ..utils.logger import logger
        from .persistence_service import PersistenceService


class GitHubPushService:
    """
    Clones a target GitHub repository, injects generated migration files,
    creates a new branch, commits, pushes, and optionally opens a Pull Request.
    """

    def __init__(self, tenant_id: Optional[str] = None):
        self.tenant_id = tenant_id

    # ─────────────────────────────────────────────────────────────
    # Public entry point
    # ─────────────────────────────────────────────────────────────

    async def push_artifacts(
        self,
        project_id: str,
        storage,
        base_path: str,
        repo_url: str,
        token: str,
        branch: str = "legacy2lake-migration",
        target_path: str = "modernized/",
        commit_message: str = "Legacy2Lake: Add modernized migration code",
        create_pr: bool = False,
        pr_title: str = "[Legacy2Lake] Modernization Artifacts",
        pr_body: str = "Migration artifacts generated automatically by Legacy2Lake UTM v4.0.",
    ) -> Dict[str, Any]:
        """
        Full pipeline: collect files → clone repo → copy → commit → push → optional PR.
        Returns a result dict with keys: success, branch, pr_url, files_pushed, error
        """
        tmpdir = tempfile.mkdtemp(prefix="l2l_github_")
        try:
            # 1. Collect generated files from storage
            logger.info(f"[GitHub] Collecting generated files for project {project_id}", "GitHubPush")
            files = self._collect_files(storage, base_path, project_id)
            if not files:
                return {"success": False, "error": "No generated files found to push."}

            logger.info(f"[GitHub] Found {len(files)} files to push", "GitHubPush")

            # 2. Clone the target repository
            authenticated_url = self._inject_token(repo_url, token)
            repo_dir = os.path.join(tmpdir, "repo")

            logger.info(f"[GitHub] Cloning {repo_url}...", "GitHubPush")
            clone_result = self._run_git(["clone", "--depth=1", authenticated_url, repo_dir])
            if not clone_result["ok"]:
                return {"success": False, "error": f"Clone failed: {clone_result['stderr']}"}

            # 3. Detect default branch
            default_branch = self._get_default_branch(repo_dir)

            # 4. Create new branch
            branch = self._sanitize_branch(branch)
            self._run_git(["checkout", "-b", branch], cwd=repo_dir)

            # 5. Copy generated files to target_path inside repo
            target_dir = os.path.join(repo_dir, target_path.strip("/"))
            os.makedirs(target_dir, exist_ok=True)

            readme_lines = [
                "# Legacy2Lake — Modernization Artifacts",
                f"",
                f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
                f"Project: {project_id}",
                f"",
                "## Contents",
                "",
            ]
            pushed_files: List[str] = []
            for rel_path, content in files.items():
                dest = os.path.join(target_dir, rel_path)
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                mode = "wb" if isinstance(content, bytes) else "w"
                with open(dest, mode) as f:
                    f.write(content)
                pushed_files.append(rel_path)
                readme_lines.append(f"- `{target_path}/{rel_path}`")

            # Write a README.md into the target folder
            with open(os.path.join(target_dir, "README.md"), "w") as f:
                f.write("\n".join(readme_lines))
            pushed_files.append("README.md")

            # 6. Git config (needed for commit author in CI environments)
            self._run_git(["config", "user.email", "legacy2lake@platform.ai"], cwd=repo_dir)
            self._run_git(["config", "user.name", "Legacy2Lake Bot"], cwd=repo_dir)

            # 7. Stage + commit
            self._run_git(["add", "-A"], cwd=repo_dir)
            commit_result = self._run_git(["commit", "-m", commit_message], cwd=repo_dir)
            if not commit_result["ok"]:
                return {"success": False, "error": f"Commit failed: {commit_result['stderr']}"}

            # 8. Push
            push_result = self._run_git(["push", "origin", branch], cwd=repo_dir)
            if not push_result["ok"]:
                return {"success": False, "error": f"Push failed: {push_result['stderr']}"}

            logger.info(f"[GitHub] Pushed branch '{branch}' successfully", "GitHubPush")

            # 9. Optionally create a Pull Request via GitHub API
            pr_url = None
            if create_pr and httpx:
                pr_url = await self._create_pull_request(
                    repo_url=repo_url,
                    token=token,
                    head=branch,
                    base=default_branch,
                    title=pr_title,
                    body=pr_body,
                )

            branch_url = self._build_branch_url(repo_url, branch)
            return {
                "success": True,
                "branch": branch,
                "branch_url": branch_url,
                "pr_url": pr_url,
                "files_pushed": len(pushed_files),
                "file_list": pushed_files,
            }

        except Exception as e:
            logger.error(f"[GitHub] Push failed: {e}", "GitHubPush")
            return {"success": False, "error": str(e)}
        finally:
            shutil.rmtree(tmpdir, ignore_errors=True)

    # ─────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────

    def _flatten_tree(self, nodes: List[Dict[str, Any]]) -> List[str]:
        """
        Recursively flatten the tree returned by storage.list_files() into a list
        of raw file paths (the 'path' field on leaf nodes, which equals the full S3 key).
        """
        paths: List[str] = []
        for node in nodes:
            if node.get("type") == "file":
                p = node.get("path") or node.get("key")
                if p:
                    paths.append(p)
            elif node.get("type") == "folder" and node.get("children"):
                paths.extend(self._flatten_tree(node["children"]))
        return paths

    def _collect_files(self, storage, base_path: str, project_id: str) -> Dict[str, Any]:
        """Collect all generated files from R2 / local storage for the project."""
        files: Dict[str, Any] = {}
        # Folders to include in the push
        target_folders = ["drafting", "refinement"]
        for folder in target_folders:
            prefix = f"{base_path.rstrip('/')}/{folder}/"
            try:
                tree = storage.list_files(prefix)
                # list_files returns a nested tree of dicts; flatten to file paths
                raw_keys = self._flatten_tree(tree) if tree else []
                for raw_key in raw_keys:
                    content = storage.read_file(raw_key)
                    if content:
                        rel = raw_key.replace(prefix, "", 1)
                        files[f"{folder}/{rel}"] = content
            except Exception as e:
                logger.error(f"[GitHub] Could not list {prefix}: {e}", "GitHubPush")

        return files

    def _inject_token(self, repo_url: str, token: str) -> str:
        """Inject PAT token into HTTPS URL for authentication."""
        repo_url = repo_url.strip()
        if repo_url.startswith("https://"):
            return repo_url.replace("https://", f"https://{token}@", 1)
        if repo_url.startswith("http://"):
            return repo_url.replace("http://", f"http://{token}@", 1)
        return repo_url  # SSH — no injection needed

    def _sanitize_branch(self, branch: str) -> str:
        """Ensure branch name is valid git ref."""
        branch = re.sub(r"[^a-zA-Z0-9/_.-]", "-", branch)
        return branch[:100]

    def _get_default_branch(self, repo_dir: str) -> str:
        result = self._run_git(
            ["symbolic-ref", "refs/remotes/origin/HEAD", "--short"], cwd=repo_dir
        )
        if result["ok"] and result["stdout"].strip():
            return result["stdout"].strip().replace("origin/", "")
        return "main"

    def _build_branch_url(self, repo_url: str, branch: str) -> str:
        """Build a browsable URL for the branch."""
        clean = re.sub(r"https://[^@]+@", "https://", repo_url)
        clean = clean.rstrip("/").removesuffix(".git")
        return f"{clean}/tree/{branch}"

    def _run_git(self, args: List[str], cwd: Optional[str] = None) -> Dict[str, Any]:
        """Run a git command and return {ok, stdout, stderr}."""
        try:
            result = subprocess.run(
                ["git"] + args,
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=120,
            )
            return {
                "ok": result.returncode == 0,
                "stdout": result.stdout.strip(),
                "stderr": result.stderr.strip(),
            }
        except subprocess.TimeoutExpired:
            return {"ok": False, "stdout": "", "stderr": "git command timed out (120s)"}
        except FileNotFoundError:
            return {"ok": False, "stdout": "", "stderr": "git not found — ensure git is installed on the server"}
        except Exception as e:
            return {"ok": False, "stdout": "", "stderr": str(e)}

    async def _create_pull_request(
        self,
        repo_url: str,
        token: str,
        head: str,
        base: str,
        title: str,
        body: str,
    ) -> Optional[str]:
        """Create a GitHub PR via REST API. Returns PR URL or None."""
        try:
            # Extract owner/repo from URL
            match = re.search(r"github\.com[:/](.+?)(?:\.git)?$", repo_url)
            if not match:
                return None
            owner_repo = match.group(1).strip("/")

            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"https://api.github.com/repos/{owner_repo}/pulls",
                    headers={
                        "Authorization": f"Bearer {token}",
                        "Accept": "application/vnd.github+json",
                        "X-GitHub-Api-Version": "2022-11-28",
                    },
                    json={"title": title, "body": body, "head": head, "base": base},
                )
                if resp.status_code in (200, 201):
                    data = resp.json()
                    pr_url = data.get("html_url")
                    logger.info(f"[GitHub] PR created: {pr_url}", "GitHubPush")
                    return pr_url
                else:
                    logger.error(
                        f"[GitHub] PR creation failed: {resp.status_code} {resp.text}", "GitHubPush"
                    )
                    return None
        except Exception as e:
            logger.error(f"[GitHub] PR creation error: {e}", "GitHubPush")
            return None
