"""
Template Engine Service - Sprint 9
===================================

Purpose:
    Generates code using Jinja2 templates with dynamic parameter injection.
    Eliminates hardcoded values by using schema metadata and design registry parameters.

Features:
    - Jinja2 template rendering
    - Dynamic column references from schema
    - Dynamic table names from parameters
    - Dynamic paths from design registry
    - Support for PySpark, Snowflake, DBT templates

Usage:
    engine = TemplateEngine()
    
    code = await engine.render_template(
        template_name='pyspark_bronze.jinja2',
        context={
            'schema': table_schema,
            'params': project_params,
            'layer': 'bronze'
        }
    )

Integration:
    - Used by Agent C for code generation
    - Uses SchemaMetadataService for schema info
    - Uses ParameterExtractor for project params

Author: Legacy2Lake Engineering
Date: 2026-02-11 (Sprint 9)
Version: v1.0
"""

from typing import Dict, Any, Optional
from jinja2 import Environment, BaseLoader, TemplateNotFound
from pathlib import Path

try:
    from apps.api.services.schema_metadata_service import TableSchema, ColumnMetadata
    from apps.api.services.parameter_extractor_service import ProjectParameters
    from apps.api.utils.logger import logger
except ImportError:
    from services.schema_metadata_service import TableSchema, ColumnMetadata
    from services.parameter_extractor_service import ProjectParameters
    from utils.logger import logger


# ================================================================
# PYSPARK TEMPLATES
# ================================================================

PYSPARK_BRONZE_TEMPLATE = """# BRONZE LAYER INGESTION
# Generated by Legacy2Lake UTM (Sprint 9 - Zero-Hardcode)
# Source: {{ schema.source_name }}
# Target: {{ target_table_full }}

from pyspark.sql import SparkSession
from pyspark.sql.functions import current_timestamp, lit, col
from delta.tables import DeltaTable

# Configuration
CATALOG = "{{ params.catalog_name }}"
BRONZE_SCHEMA = "{{ params.bronze_schema }}"
TARGET_TABLE = "{{ target_table_name }}"
TARGET_PATH = "{{ target_file_path }}"

# Initialize Spark
spark = SparkSession.builder.appName("bronze_{{ schema.table_name }}").getOrCreate()

# Read source data
{% if schema.source_type == 'SSIS' %}
# Source: SSIS Package
# TODO: Replace with actual source connection
df_source = spark.read \\
    .format("jdbc") \\
    .option("url", "jdbc:sqlserver://source-server:1433;databaseName=SourceDB") \\
    .option("dbtable", "{{ schema.table_name }}") \\
    .option("user", dbutils.secrets.get(scope="source", key="username")) \\
    .option("password", dbutils.secrets.get(scope="source", key="password")) \\
    .load()
{% elif schema.source_type == 'SQL_PROC' %}
# Source: SQL Stored Procedure
# TODO: Execute stored procedure and read results
df_source = spark.read \\
    .format("jdbc") \\
    .option("url", "jdbc:sqlserver://source-server:1433;databaseName=SourceDB") \\
    .option("query", "EXEC dbo.{{ schema.source_name }}") \\
    .option("user", dbutils.secrets.get(scope="source", key="username")) \\
    .option("password", dbutils.secrets.get(scope="source", key="password")) \\
    .load()
{% else %}
# Source: File
df_source = spark.read \\
    .format("csv") \\
    .option("header", "true") \\
    .option("inferSchema", "true") \\
    .load("{{ source_path }}")
{% endif %}

# Select columns (no hardcoded column names)
source_columns = [
{% for col in schema.columns %}
    "{{ col.name }}"{{ "," if not loop.last else "" }}
{% endfor %}
]

df_bronze = df_source.select(*source_columns)

# Add ingestion metadata (Bronze layer requirement)
df_bronze = df_bronze \\
    .withColumn("_ingestion_timestamp", current_timestamp()) \\
    .withColumn("_ingestion_date", current_timestamp().cast("date")) \\
    .withColumn("_source_file", lit("{{ schema.source_name }}")) \\
    .withColumn("_source_system", lit("{{ schema.source_type }}"))

# Write to Delta Lake
df_bronze.write \\
    .format("delta") \\
    .mode("append") \\
    .option("mergeSchema", "true") \\
    .option("dataChange", "true") \\
    .saveAsTable(f"{CATALOG}.{BRONZE_SCHEMA}.{TARGET_TABLE}")

# Log completion
print(f"✅ Bronze ingestion complete: {CATALOG}.{BRONZE_SCHEMA}.{TARGET_TABLE}")
print(f"   Rows ingested: {df_bronze.count()}")
print(f"   Schema: {df_bronze.schema.simpleString()}")
"""


PYSPARK_SILVER_TEMPLATE = """# SILVER LAYER TRANSFORMATION
# Generated by Legacy2Lake UTM (Sprint 9 - Zero-Hardcode)
# Source: {{ source_table_full }}
# Target: {{ target_table_full }}

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp
from delta.tables import DeltaTable

# Configuration
CATALOG = "{{ params.catalog_name }}"
BRONZE_SCHEMA = "{{ params.bronze_schema }}"
SILVER_SCHEMA = "{{ params.silver_schema }}"
SOURCE_TABLE = "{{ source_table_name }}"
TARGET_TABLE = "{{ target_table_name }}"

# Initialize Spark
spark = SparkSession.builder.appName("silver_{{ schema.table_name }}").getOrCreate()

# Read Bronze
df_bronze = spark.read.table(f"{CATALOG}.{BRONZE_SCHEMA}.{SOURCE_TABLE}")

# Data quality transformations
df_clean = df_bronze

# Remove duplicates using primary key
{% if schema.primary_key %}
df_clean = df_clean.dropDuplicates([
{% for pk in schema.primary_key %}
    "{{ pk }}"{{ "," if not loop.last else "" }}
{% endfor %}
])
{% endif %}

# Remove nulls in primary key columns
{% if schema.primary_key %}
{% for pk in schema.primary_key %}
df_clean = df_clean.filter(col("{{ pk }}").isNotNull())
{% endfor %}
{% endif %}

# Select business columns (exclude audit columns)
business_columns = [
{% for col in schema.columns %}
{% if not col.name.startswith('_') %}
    "{{ col.name }}"{{ "," if not loop.last else "" }}
{% endif %}
{% endfor %}
]

df_silver = df_clean.select(*business_columns)

# Add Silver audit columns
df_silver = df_silver \\
    .withColumn("_silver_updated_at", current_timestamp())

# Write to Delta with SCD Type 2 (Upsert)
target_table_path = f"{CATALOG}.{SILVER_SCHEMA}.{TARGET_TABLE}"

if spark.catalog.tableExists(target_table_path){% if schema.primary_key %} and len({{ schema.primary_key }}) > 0{% endif %}:
    # Table exists - perform merge (upsert)
    target_table = DeltaTable.forName(spark, target_table_path)
    
    # Build merge condition
    {% if schema.primary_key %}
    merge_condition = " AND ".join([
    {% for pk in schema.primary_key %}
        f"target.{{ pk }} = source.{{ pk }}"{{ "," if not loop.last else "" }}
    {% endfor %}
    ])
    {% else %}
    merge_condition = "1=0"  # No PK - always insert
    {% endif %}
    
    target_table.alias("target").merge(
        df_silver.alias("source"),
        merge_condition
    ).whenMatchedUpdateAll() \\
     .whenNotMatchedInsertAll() \\
     .execute()
    
    print(f"✅ Silver upsert complete: {target_table_path}")
else:
    # First load - overwrite
    df_silver.write \\
        .format("delta") \\
        .mode("overwrite") \\
        .saveAsTable(target_table_path)
    
    print(f"✅ Silver initial load complete: {target_table_path}")

print(f"   Schema: {df_silver.schema.simpleString()}")
"""


PYSPARK_GOLD_TEMPLATE = """# GOLD LAYER - BUSINESS VIEW
# Generated by Legacy2Lake UTM (Sprint 9 - Zero-Hardcode)
# Source: {{ source_table_full }}
# Target: {{ target_table_full }}
# Type: {{ table_type }}

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum as spark_sum, count, avg

# Configuration
CATALOG = "{{ params.catalog_name }}"
SILVER_SCHEMA = "{{ params.silver_schema }}"
GOLD_SCHEMA = "{{ params.gold_schema }}"
SOURCE_TABLE = "{{ source_table_name }}"
TARGET_TABLE = "{{ target_table_name }}"

# Initialize Spark
spark = SparkSession.builder.appName("gold_{{ schema.table_name }}").getOrCreate()

# Read Silver
df_silver = spark.read.table(f"{CATALOG}.{SILVER_SCHEMA}.{SOURCE_TABLE}")

{% if table_type == 'DIMENSION' %}
# Gold Logic: Dimension table (no aggregation)
df_gold = df_silver.select(
{% for col in schema.columns %}
{% if not col.name.startswith('_') %}
    "{{ col.name }}"{{ "," if not loop.last else "" }}
{% endif %}
{% endfor %}
)

{% elif table_type == 'FACT' %}
# Gold Logic: Fact table with business metrics
# TODO: Adjust aggregations based on business requirements
df_gold = df_silver.select("*")

{% if schema.foreign_keys %}
# Add business metrics (example)
# df_gold = df_gold.withColumn("total_amount", col("quantity") * col("unit_price"))
{% endif %}

{% else %}
# Gold Logic: Generic business view
df_gold = df_silver.select("*")
{% endif %}

# Write to Gold
target_table_path = f"{CATALOG}.{GOLD_SCHEMA}.{TARGET_TABLE}"

df_gold.write \\
    .format("delta") \\
    .mode("overwrite") \\
    .option("overwriteSchema", "true") \\
    .saveAsTable(target_table_path)

print(f"✅ Gold layer complete: {target_table_path}")
print(f"   Rows: {df_gold.count()}")
print(f"   Schema: {df_gold.schema.simpleString()}")
"""


# ================================================================
# TEMPLATE ENGINE
# ================================================================

class TemplateEngine:
    """
    Template engine for zero-hardcode code generation.
    Uses Jinja2 to render templates with dynamic context.
    """
    
    # Built-in templates
    TEMPLATES = {
        'pyspark_bronze': PYSPARK_BRONZE_TEMPLATE,
        'pyspark_silver': PYSPARK_SILVER_TEMPLATE,
        'pyspark_gold': PYSPARK_GOLD_TEMPLATE
    }
    
    def __init__(self):
        self.env = Environment(loader=BaseLoader())
        
        # Add custom filters
        self.env.filters['snake_case'] = self._snake_case
        self.env.filters['camel_case'] = self._camel_case
    
    
    async def render_template(
        self,
        template_name: str,
        schema: TableSchema,
        params: ProjectParameters,
        layer: str = 'bronze',
        **extra_context
    ) -> str:
        """
        Render template with dynamic context.
        
        Args:
            template_name: Template name (e.g., 'pyspark_bronze')
            schema: TableSchema from SchemaMetadataService
            params: ProjectParameters from ParameterExtractor
            layer: Target layer ('bronze', 'silver', 'gold')
            **extra_context: Additional context variables
        
        Returns:
            Rendered code as string
        """
        logger.info(f"[TemplateEngine] Rendering template: {template_name}, layer={layer}", "TemplateEngine")
        
        # Get template
        template_content = self.TEMPLATES.get(template_name)
        
        if not template_content:
            raise TemplateNotFound(f"Template not found: {template_name}")
        
        template = self.env.from_string(template_content)
        
        # Build context
        context = self._build_context(schema, params, layer, **extra_context)
        
        # Render
        code = template.render(**context)
        
        logger.info(f"[TemplateEngine] Template rendered: {len(code)} chars", "TemplateEngine")
        
        return code
    
    
    def _build_context(
        self,
        schema: TableSchema,
        params: ProjectParameters,
        layer: str,
        **extra_context
    ) -> Dict[str, Any]:
        """
        Build Jinja2 context from schema and parameters.
        
        Returns:
            Dictionary with all template variables
        """
        # Resolve table names
        from apps.api.services.parameter_extractor_service import ParameterExtractor
        extractor = ParameterExtractor()
        extractor._cache = params  # Set cache
        
        source_table_name = schema.table_name
        target_table_name = extractor.resolve_table_name(source_table_name, layer, params)
        
        # Build full paths
        if layer == 'bronze':
            source_table_full = None  # Bronze reads from source
            target_table_full = extractor.get_full_table_path(target_table_name, 'bronze', params)
            target_file_path = extractor.get_file_path(target_table_name, 'bronze', params)
        elif layer == 'silver':
            # Silver reads from bronze
            bronze_table_name = extractor.resolve_table_name(source_table_name, 'bronze', params)
            source_table_full = extractor.get_full_table_path(bronze_table_name, 'bronze', params)
            target_table_full = extractor.get_full_table_path(target_table_name, 'silver', params)
            target_file_path = extractor.get_file_path(target_table_name, 'silver', params)
        elif layer == 'gold':
            # Gold reads from silver
            silver_table_name = extractor.resolve_table_name(source_table_name, 'silver', params)
            source_table_full = extractor.get_full_table_path(silver_table_name, 'silver', params)
            target_table_full = extractor.get_full_table_path(target_table_name, 'gold', params)
            target_file_path = extractor.get_file_path(target_table_name, 'gold', params)
        else:
            source_table_full = None
            target_table_full = target_table_name
            target_file_path = f"/tmp/{target_table_name}"
        
        # Build context
        context = {
            'schema': schema,
            'params': params,
            'layer': layer,
            'source_table_name': source_table_name,
            'target_table_name': target_table_name,
            'source_table_full': source_table_full,
            'target_table_full': target_table_full,
            'target_file_path': target_file_path,
            'table_type': extra_context.get('table_type', 'DIMENSION'),
            'source_path': extra_context.get('source_path', '/tmp/source.csv')
        }
        
        # Merge extra context
        context.update(extra_context)
        
        return context
    
    
    def _snake_case(self, text: str) -> str:
        """Convert text to snake_case"""
        import re
        text = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
        text = re.sub('([a-z0-9])([A-Z])', r'\1_\2', text)
        return text.lower()
    
    
    def _camel_case(self, text: str) -> str:
        """Convert text to CamelCase"""
        words = text.replace('_', ' ').replace('-', ' ').split()
        return ''.join(word.capitalize() for word in words)
