# COMMAND ----------
# Title: DimCategory.dtsx
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# Extract parameter for categoryid > ? (Assume widget or parameter passed)
categoryid_min = int(dbutils.widgets.get('categoryid_min', '-1'))

# Secure JDBC connection setup
jdbc_url = dbutils.secrets.get('jdbc', 'sqlserver_url')
jdbc_user = dbutils.secrets.get('jdbc', 'sqlserver_user')
jdbc_password = dbutils.secrets.get('jdbc', 'sqlserver_password')

source_query = f"""
SELECT categoryid, categoryname FROM Production.Categories WHERE categoryid > {categoryid_min}
"""

# Read source data explicitly
source_df = (
    spark.read.format('jdbc')
    .option('url', jdbc_url)
    .option('user', jdbc_user)
    .option('password', jdbc_password)
    .option('dbtable', f"({source_query}) as src")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups required for this task

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "base.dbo.DimCategory"
bk_cols = ["categoryid"]
sk_col = "CategoryKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
staged_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define unknown row explicitly
    unknown_row = {
        "CategoryKey": -1,
        "categoryid": -1,
        "categoryname": "Unknown"
    }
    # Check if unknown exists
    if df.filter(col("CategoryKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row], schema=df.schema)
        df = df.unionByName(unknown_df)
    return df

staged_df = ensure_unknown_member(staged_df)

# 4. Mandatory Type Casting (STRICT)
# Target schema: CategoryKey (INTEGER), categoryid (INTEGER), categoryname (STRING)
staged_df = staged_df.withColumn("CategoryKey", col("CategoryKey").cast("integer"))
staged_df = staged_df.withColumn("categoryid", col("categoryid").cast("integer"))
staged_df = staged_df.withColumn("categoryname", col("categoryname").cast("string"))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Idempotent overwrite of DimCategory
(
    staged_df
    .write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(target_table_name)
)

# 6. Optimization (Z-ORDER)
deltaTable = DeltaTable.forName(spark, target_table_name)
deltaTable.optimize().executeZOrderBy("categoryid")
