# COMMAND ----------
# Title: DimEmployee.dtsx
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Source (HR.Employees via JDBC)
# Securely fetch credentials
jdbc_url = dbutils.secrets.get(scope="HR_DB", key="jdbc_url")
jdbc_user = dbutils.secrets.get(scope="HR_DB", key="username")
jdbc_password = dbutils.secrets.get(scope="HR_DB", key="password")

# Parameterize empid threshold (default to 0 if not provided)
empid_threshold = int(dbutils.widgets.get("empid_threshold", "0"))

source_query = f"""
SELECT empid, (firstname + ' ' + lastname) as fullname, title, city, country, address, phone
FROM HR.Employees
WHERE empid > {empid_threshold}
"""

# Read source data
source_df = (
    spark.read.format("jdbc")
    .option("url", jdbc_url)
    .option("user", jdbc_user)
    .option("password", jdbc_password)
    .option("dbtable", f"({source_query}) as src")
    .load()
)

# 3. Transformations (Apply Logic)
# No lookups specified. No business logic beyond source query.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "DimEmployee"
bk_cols = ["empid"]
sk_col = "EmployeeKey"

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = source_df.join(df_target, on=bk_cols, how="left")
else:
    df_joined = source_df.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
staged_df = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    unknown_row = {
        "EmployeeKey": -1,
        "empid": -1,
        "fullname": "Unknown",
        "title": "Unknown",
        "city": "Unknown",
        "country": "Unknown",
        "address": "Unknown",
        "phone": "Unknown"
    }
    # Check if unknown exists
    if df.filter(col("EmployeeKey") == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = df.unionByName(unknown_df)
    return df

staged_df = ensure_unknown_member(staged_df)

# 4. Mandatory Type Casting (STRICT)
# Define target schema explicitly (as per platform rules)
target_schema = [
    {"name": "EmployeeKey", "type": "INTEGER"},
    {"name": "empid", "type": "INTEGER"},
    {"name": "fullname", "type": "STRING"},
    {"name": "title", "type": "STRING"},
    {"name": "city", "type": "STRING"},
    {"name": "country", "type": "STRING"},
    {"name": "address", "type": "STRING"},
    {"name": "phone", "type": "STRING"}
]

for field in target_schema:
    col_name = field["name"]
    target_type = field["type"]
    if col_name in staged_df.columns:
        staged_df = staged_df.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge into DimEmployee (idempotent)
staged_df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)

# 6. Optimization (Z-ORDER on empid)
deltaTable = DeltaTable.forName(spark, target_table_name)
deltaTable.optimize().zorderBy("empid")
