# COMMAND ----------
# Title: DimProduct.dtsx Migration
# Auto-Generated by Platform Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Source (Bronze)
# Use JDBC connection for the input query
jdbc_url = dbutils.secrets.get('jdbc', 'prod_url')
jdbc_user = dbutils.secrets.get('jdbc', 'prod_user')
jdbc_password = dbutils.secrets.get('jdbc', 'prod_password')

source_query = "SELECT * FROM Production.Products"
df_source = spark.read.format("jdbc") \
    .option("url", jdbc_url) \
    .option("user", jdbc_user) \
    .option("password", jdbc_password) \
    .option("dbtable", f"({source_query}) as src") \
    .load()

# 3. Transformations (Apply Logic)
# No lookups specified. Direct mapping.

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
target_table_name = "dbo.DimProduct"
bk_cols = ["ProductID"]  # Assuming ProductID is the business key
sk_col = "DimProductSK"  # Surrogate Key column name

# 1. Get Existing Keys (Handle if table doesn't exist yet)
try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

# 2. Join Source with Target to find existing SKs
if df_target is not None:
    df_joined = df_source.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_source.withColumn(sk_col, lit(None).cast("integer"))

# 3. Generate Keys for New Rows ONLY
window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)

# 4. Union
from pyspark.sql import DataFrame

def unionByName_safe(df1: DataFrame, df2: DataFrame) -> DataFrame:
    # Ensure both DataFrames have the same columns
    cols = list(set(df1.columns) | set(df2.columns))
    df1 = df1.select([col(c) if c in df1.columns else lit(None).alias(c) for c in cols])
    df2 = df2.select([col(c) if c in df2.columns else lit(None).alias(c) for c in cols])
    return df1.unionByName(df2)

df_with_sk = unionByName_safe(df_existing, df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the unknown row explicitly
    unknown_row = {
        sk_col: -1,
        "ProductID": -1,
        "ProductName": "Unknown",
        "ProductNumber": "Unknown",
        "Color": "Unknown",
        "StandardCost": 0.0,
        "ListPrice": 0.0,
        "Size": "Unknown",
        "Weight": 0.0,
        "ProductCategoryID": -1,
        "ProductModelID": -1,
        "SellStartDate": None,
        "SellEndDate": None,
        "DiscontinuedDate": None,
        "rowguid": None,
        "ModifiedDate": None
    }
    # Check if unknown exists
    if df.filter(col(sk_col) == -1).count() == 0:
        unknown_df = spark.createDataFrame([unknown_row])
        df = unionByName_safe(df, unknown_df)
    return df

df_with_sk = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# Define the target schema explicitly (as per best practice, since schema is not provided)
target_schema = [
    {"name": "DimProductSK", "type": "INTEGER"},
    {"name": "ProductID", "type": "INTEGER"},
    {"name": "ProductName", "type": "STRING"},
    {"name": "ProductNumber", "type": "STRING"},
    {"name": "Color", "type": "STRING"},
    {"name": "StandardCost", "type": "DECIMAL(19,4)"},
    {"name": "ListPrice", "type": "DECIMAL(19,4)"},
    {"name": "Size", "type": "STRING"},
    {"name": "Weight", "type": "DECIMAL(19,4)"},
    {"name": "ProductCategoryID", "type": "INTEGER"},
    {"name": "ProductModelID", "type": "INTEGER"},
    {"name": "SellStartDate", "type": "TIMESTAMP"},
    {"name": "SellEndDate", "type": "TIMESTAMP"},
    {"name": "DiscontinuedDate", "type": "TIMESTAMP"},
    {"name": "rowguid", "type": "STRING"},
    {"name": "ModifiedDate", "type": "TIMESTAMP"}
]

for field in target_schema:
    col_name = field["name"]
    target_type = field["type"]
    if col_name in df_with_sk.columns:
        df_with_sk = df_with_sk.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# Overwrite/merge into target table
(
    df_with_sk.write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(target_table_name)
)

# 6. Optimization (Z-ORDER)
# Z-ORDER on ProductID for query performance
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (ProductID)")
