# COMMAND ----------
# Title: DimProduct.dtsx
# Auto-Generated by Shift-T Developer Agent
# --------------------------------------------------

# 1. Setup & Config
from delta.tables import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

# 2. Reading Bronze / Source
# -- JDBC connection details (replace with your actual values or widgets)
db_url = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-url")
db_user = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-user")
db_password = dbutils.secrets.get(scope="jdbc-secrets", key="sqlserver-password")

source_query = "SELECT * FROM Production.Products"
df_source = spark.read.format("jdbc") \
    .option("url", db_url) \
    .option("dbtable", f"({source_query}) as src") \
    .option("user", db_user) \
    .option("password", db_password) \
    .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") \
    .load()

# 3. Transformations (Apply Logic)
# -- No lookups or additional logic specified in task definition.
df_staged = df_source

# 3.1 Surrogate Key Generation (STABLE & IDEMPOTENT)
# SAFE MIGRATION PATTERN: Lookup existing keys, generate new ones only for new members.
# For DimProduct, assume 'ProductKey' is the surrogate key and 'ProductID' is the business key.
target_table_name = "dbo.DimProduct"
bk_cols = ["ProductID"]
sk_col = "ProductKey"

try:
    df_target = spark.read.table(target_table_name).select(*bk_cols, sk_col)
    max_sk = df_target.agg(max(col(sk_col))).collect()[0][0] or 0
except Exception:
    df_target = None
    max_sk = 0

if df_target is not None:
    df_joined = df_staged.join(df_target, on=bk_cols, how="left")
else:
    df_joined = df_staged.withColumn(sk_col, lit(None).cast("integer"))

window_spec = Window.orderBy(*bk_cols)
df_existing = df_joined.filter(col(sk_col).isNotNull())
df_new = df_joined.filter(col(sk_col).isNull()).drop(sk_col)
df_new = df_new.withColumn(sk_col, row_number().over(window_spec) + max_sk)
df_with_sk = df_existing.unionByName(df_new)

# 3.2 Unknown Member Handling (For Dimensions)
def ensure_unknown_member(df):
    # Define the schema for the unknown member
    unknown_dict = {col: -1 if dtype in ["int", "integer"] else None for col, dtype in zip(df.columns, [f.dataType.simpleString() for f in df.schema])}
    unknown_dict[sk_col] = -1
    unknown_dict[bk_cols[0]] = -1
    unknown_row = spark.createDataFrame([unknown_dict], df.schema)
    if df.filter(col(sk_col) == -1).count() == 0:
        return df.unionByName(unknown_row)
    else:
        return df

df_final = ensure_unknown_member(df_with_sk)

# 4. Mandatory Type Casting (STRICT)
# -- You must provide the target schema for strict casting. Since the schema is not provided, we infer types from the source.
for field in df_final.schema.fields:
    col_name = field.name
    target_type = field.dataType.simpleString()
    df_final = df_final.withColumn(col_name, col(col_name).cast(target_type))

# 5. Writing to Silver/Gold (Apply Platform Pattern)
# -- Overwrite the target table (idempotent load for dimension)
df_final.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table_name)

# 6. Optimization (Z-ORDER)
# -- Z-ORDER on ProductID for query performance
spark.sql(f"OPTIMIZE {target_table_name} ZORDER BY (ProductID)")
