"""
Migrate Hardcoded Templates to Database - v4.0 Zero-Hardcode Core

This script migrates hardcoded templates from template_engine_service.py
to the utm_prompts table in the database.

Usage:
    python migrate_templates_to_db.py
    
Environment Variables:
    SUPABASE_URL: Supabase project URL
    SUPABASE_KEY: Supabase service role key (or anon key)

Author: Legacy2Lake Engineering
Date: February 14, 2026
Version: v4.0.0
"""

import os
import sys
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

try:
    from apps.api.services.persistence_service import SupabasePersistence
    from apps.api.services.prompts.prompt_service import PromptService
    from apps.api.utils.logger import logger
except ImportError:
    from services.persistence_service import SupabasePersistence
    from services.prompts.prompt_service import PromptService
    from utils.logger import logger


# ================================================================
# TEMPLATE DEFINITIONS (From template_engine_service.py)
# ================================================================

PYSPARK_BRONZE_TEMPLATE = """# BRONZE LAYER INGESTION
# Generated by Legacy2Lake UTM v4.0 - Zero-Hardcode Core
# Source: {{schema.source_name}}
# Target: {{target_table_full}}

from pyspark.sql import SparkSession
from pyspark.sql.functions import current_timestamp, lit, col
from delta.tables import DeltaTable

# Configuration
CATALOG = "{{params.catalog_name}}"
BRONZE_SCHEMA = "{{params.bronze_schema}}"
TARGET_TABLE = "{{target_table_name}}"
TARGET_PATH = "{{target_file_path}}"

# Initialize Spark
spark = SparkSession.builder.appName("bronze_{{schema.table_name}}").getOrCreate()

# Read source data
source_columns = [
{{#each schema.columns}}
    "{{name}}"{{#unless @last}},{{/unless}}
{{/each}}
]

# TODO: Configure actual source connection
df_source = spark.read \\
    .format("jdbc") \\
    .option("url", "jdbc:sqlserver://source-server:1433;databaseName=SourceDB") \\
    .option("dbtable", "{{schema.table_name}}") \\
    .load()

df_bronze = df_source.select(*source_columns)

# Add ingestion metadata (Bronze layer requirement)
df_bronze = df_bronze \\
    .withColumn("_ingestion_timestamp", current_timestamp()) \\
    .withColumn("_ingestion_date", current_timestamp().cast("date")) \\
    .withColumn("_source_file", lit("{{schema.source_name}}")) \\
    .withColumn("_source_system", lit("{{schema.source_type}}"))

# Write to Delta Lake
df_bronze.write \\
    .format("delta") \\
    .mode("append") \\
    .option("mergeSchema", "true") \\
    .option("dataChange", "true") \\
    .saveAsTable(f"{CATALOG}.{BRONZE_SCHEMA}.{TARGET_TABLE}")

print(f"✅ Bronze ingestion complete: {CATALOG}.{BRONZE_SCHEMA}.{TARGET_TABLE}")
print(f"   Rows ingested: {df_bronze.count()}")
"""


PYSPARK_SILVER_TEMPLATE = """# SILVER LAYER TRANSFORMATION
# Generated by Legacy2Lake UTM v4.0 - Zero-Hardcode Core
# Source: {{source_table_full}}
# Target: {{target_table_full}}

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp
from delta.tables import DeltaTable

# Configuration
CATALOG = "{{params.catalog_name}}"
BRONZE_SCHEMA = "{{params.bronze_schema}}"
SILVER_SCHEMA = "{{params.silver_schema}}"
SOURCE_TABLE = "{{source_table_name}}"
TARGET_TABLE = "{{target_table_name}}"

# Initialize Spark
spark = SparkSession.builder.appName("silver_{{schema.table_name}}").getOrCreate()

# Read Bronze
df_bronze = spark.read.table(f"{CATALOG}.{BRONZE_SCHEMA}.{SOURCE_TABLE}")

# Data quality transformations
df_clean = df_bronze

# Remove duplicates and nulls
{{#if schema.primary_key}}
df_clean = df_clean.dropDuplicates({{schema.primary_key | json}})
{{#each schema.primary_key}}
df_clean = df_clean.filter(col("{{this}}").isNotNull())
{{/each}}
{{/if}}

# Select business columns (exclude audit columns)
business_columns = [col for col in df_clean.columns if not col.startswith('_')]
df_silver = df_clean.select(*business_columns)

# Add Silver audit columns
df_silver = df_silver.withColumn("_silver_updated_at", current_timestamp())

# Write to Delta with Upsert
target_table_path = f"{CATALOG}.{SILVER_SCHEMA}.{TARGET_TABLE}"

if spark.catalog.tableExists(target_table_path):
    target_table = DeltaTable.forName(spark, target_table_path)
    {{#if schema.primary_key}}
    merge_condition = " AND ".join([f"target.{pk} = source.{pk}" for pk in {{schema.primary_key | json}}])
    {{else}}
    merge_condition = "1=0"  # No PK - always insert
    {{/if}}
    
    target_table.alias("target").merge(
        df_silver.alias("source"),
        merge_condition
    ).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
else:
    df_silver.write.format("delta").mode("overwrite").saveAsTable(target_table_path)

print(f"✅ Silver transformation complete: {target_table_path}")
"""


PYSPARK_GOLD_TEMPLATE = """# GOLD LAYER - BUSINESS VIEW
# Generated by Legacy2Lake UTM v4.0 - Zero-Hardcode Core
# Source: {{source_table_full}}
# Target: {{target_table_full}}

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

# Configuration
CATALOG = "{{params.catalog_name}}"
SILVER_SCHEMA = "{{params.silver_schema}}"
GOLD_SCHEMA = "{{params.gold_schema}}"
SOURCE_TABLE = "{{source_table_name}}"
TARGET_TABLE = "{{target_table_name}}"

# Initialize Spark
spark = SparkSession.builder.appName("gold_{{schema.table_name}}").getOrCreate()

# Read Silver
df_silver = spark.read.table(f"{CATALOG}.{SILVER_SCHEMA}.{SOURCE_TABLE}")

# Business logic - Select relevant columns
business_columns = [col for col in df_silver.columns if not col.startswith('_')]
df_gold = df_silver.select(*business_columns)

# Write to Gold
target_table_path = f"{CATALOG}.{GOLD_SCHEMA}.{TARGET_TABLE}"

df_gold.write \\
    .format("delta") \\
    .mode("overwrite") \\
    .option("overwriteSchema", "true") \\
    .saveAsTable(target_table_path)

print(f"✅ Gold layer complete: {target_table_path}")
print(f"   Rows: {df_gold.count()}")
"""


# ================================================================
# MIGRATION PROMPTS
# ================================================================

PROMPTS_TO_MIGRATE = [
    {
        "prompt_id": "agent_c_bronze_pyspark",
        "content": PYSPARK_BRONZE_TEMPLATE,
        "tech_stack": "pyspark",
        "pattern_type": "bronze",
        "agent_id": "agent-c",
        "metadata": {
            "description": "Bronze layer ingestion template for PySpark",
            "version": "4.0.0",
            "migrated_from": "template_engine_service.py",
            "migration_date": "2026-02-14",
            "tags": ["production", "tested", "medallion", "bronze"],
            "variables": [
                "schema.source_name",
                "schema.table_name",
                "schema.columns",
                "params.catalog_name",
                "params.bronze_schema",
                "target_table_name",
                "target_file_path"
            ]
        }
    },
    {
        "prompt_id": "agent_c_silver_pyspark",
        "content": PYSPARK_SILVER_TEMPLATE,
        "tech_stack": "pyspark",
        "pattern_type": "silver",
        "agent_id": "agent-c",
        "metadata": {
            "description": "Silver layer transformation template for PySpark",
            "version": "4.0.0",
            "migrated_from": "template_engine_service.py",
            "migration_date": "2026-02-14",
            "tags": ["production", "tested", "medallion", "silver"],
            "variables": [
                "schema.table_name",
                "schema.primary_key",
                "params.catalog_name",
                "params.bronze_schema",
                "params.silver_schema",
                "source_table_name",
                "target_table_name",
                "source_table_full",
                "target_table_full"
            ]
        }
    },
    {
        "prompt_id": "agent_c_gold_pyspark",
        "content": PYSPARK_GOLD_TEMPLATE,
        "tech_stack": "pyspark",
        "pattern_type": "gold",
        "agent_id": "agent-c",
        "metadata": {
            "description": "Gold layer business view template for PySpark",
            "version": "4.0.0",
            "migrated_from": "template_engine_service.py",
            "migration_date": "2026-02-14",
            "tags": ["production", "tested", "medallion", "gold"],
            "variables": [
                "schema.table_name",
                "params.catalog_name",
                "params.silver_schema",
                "params.gold_schema",
                "source_table_name",
                "target_table_name",
                "source_table_full",
                "target_table_full"
            ]
        }
    }
]


# ================================================================
# MIGRATION FUNCTION
# ================================================================

async def migrate_templates():
    """
    Migrate hardcoded templates to utm_prompts table
    """
    print("=" * 80)
    print("v4.0 Zero-Hardcode Core - Template Migration")
    print("=" * 80)
    print()
    
    # Check environment variables
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_KEY")
    
    if not supabase_url or not supabase_key:
        print("❌ ERROR: Environment variables not set")
        print("   Please set SUPABASE_URL and SUPABASE_KEY")
        return False
    
    print(f"✓ Supabase URL: {supabase_url}")
    print(f"✓ Supabase Key: {'*' * 20}...{supabase_key[-4:]}")
    print()
    
    # Initialize services (without tenant_id for global prompts)
    prompt_service = PromptService(tenant_id=None, client_id=None)
    
    print(f"Migrating {len(PROMPTS_TO_MIGRATE)} templates to database...")
    print()
    
    success_count = 0
    error_count = 0
    
    for prompt_data in PROMPTS_TO_MIGRATE:
        prompt_id = prompt_data["prompt_id"]
        
        try:
            print(f"Processing: {prompt_id}")
            print(f"  Tech: {prompt_data['tech_stack']}")
            print(f"  Pattern: {prompt_data['pattern_type']}")
            print(f"  Length: {len(prompt_data['content'])} chars")
            
            # Check if prompt already exists
            existing = await prompt_service.get_prompt(prompt_id, use_cache=False)
            
            if existing:
                print(f"  ⚠️  Prompt already exists, updating...")
                
                # Update existing prompt
                await prompt_service.update_prompt(
                    prompt_id=prompt_id,
                    content=prompt_data["content"],
                    tech_stack=prompt_data["tech_stack"],
                    pattern_type=prompt_data["pattern_type"],
                    agent_id=prompt_data["agent_id"],
                    metadata=prompt_data["metadata"],
                    is_active=True
                )
                
                print(f"  ✅ Updated successfully")
            else:
                # Create new prompt
                await prompt_service.create_prompt(
                    prompt_id=prompt_id,
                    content=prompt_data["content"],
                    tech_stack=prompt_data["tech_stack"],
                    pattern_type=prompt_data["pattern_type"],
                    agent_id=prompt_data["agent_id"],
                    metadata=prompt_data["metadata"]
                )
                
                print(f"  ✅ Created successfully")
            
            success_count += 1
            print()
            
        except Exception as e:
            error_count += 1
            print(f"  ❌ Error: {e}")
            print()
    
    print("=" * 80)
    print("Migration Summary")
    print("=" * 80)
    print(f"✅ Successful: {success_count}")
    print(f"❌ Errors: {error_count}")
    print(f"📊 Total: {len(PROMPTS_TO_MIGRATE)}")
    print()
    
    if error_count == 0:
        print("🎉 Migration completed successfully!")
        return True
    else:
        print("⚠️  Migration completed with errors")
        return False


# ================================================================
# MAIN
# ================================================================

if __name__ == "__main__":
    import asyncio
    
    print()
    print("╔═══════════════════════════════════════════════════════════════╗")
    print("║  Legacy2Lake UTM v4.0 - Zero-Hardcode Core                   ║")
    print("║  Template Migration Script                                    ║")
    print("╚═══════════════════════════════════════════════════════════════╝")
    print()
    
    try:
        success = asyncio.run(migrate_templates())
        
        if success:
            print()
            print("Next steps:")
            print("1. Verify prompts in database: SELECT * FROM utm_prompts;")
            print("2. Test code generation with new prompts")
            print("3. Remove hardcoded templates from template_engine_service.py (optional)")
            print()
            sys.exit(0)
        else:
            sys.exit(1)
            
    except KeyboardInterrupt:
        print()
        print("Migration cancelled by user")
        sys.exit(1)
    except Exception as e:
        print()
        print(f"❌ Migration failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
