"""
Validate Generated Code: Validate Python code generated by cartridges

Performs syntax validation and technology-specific checks on generated code.

Usage:
    python scripts/validate_generated_code.py <output_dir>     # Validate all .py files
    python scripts/validate_generated_code.py <file.py>        # Validate single file

Author: Development Team
Date: 2026-02-10
Version: 1.0.0
"""

import ast
import sys
from pathlib import Path
from typing import Dict, List, Tuple
from dataclasses import dataclass
from enum import Enum


class ValidationLevel(Enum):
    ERROR = "ERROR"
    WARNING = "WARNING"
    INFO = "INFO"


@dataclass
class ValidationResult:
    """Result of a validation check"""
    level: ValidationLevel
    check_name: str
    passed: bool
    message: str


class CodeValidator:
    """Base validator for generated code"""
    
    def validate_python_syntax(self, code: str) -> ValidationResult:
        """Validate that Python code is syntactically correct"""
        try:
            ast.parse(code)
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="syntax",
                passed=True,
                message="Python syntax is valid"
            )
        except SyntaxError as e:
            return ValidationResult(
                level=ValidationLevel.ERROR,
                check_name="syntax",
                passed=False,
                message=f"Syntax error at line {e.lineno}: {e.msg}"
            )
    
    def extract_imports(self, code: str) -> List[str]:
        """Extract all imports from Python code"""
        try:
            tree = ast.parse(code)
            imports = []
            
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    imports.extend([alias.name for alias in node.names])
                elif isinstance(node, ast.ImportFrom):
                    module = node.module or ""
                    imports.append(module)
            
            return imports
        except:
            return []
    
    def has_pattern(self, code: str, pattern: str) -> bool:
        """Check if code contains a specific pattern"""
        return pattern in code
    
    def validate(self, code: str, file_path: Path) -> List[ValidationResult]:
        """
        Validate code (override in subclasses)
        
        Returns:
            List of validation results
        """
        return [self.validate_python_syntax(code)]


class PySparkValidator(CodeValidator):
    """Validator for PySpark code"""
    
    REQUIRED_METADATA_COLUMNS = [
        '_ingestion_timestamp',
        '_ingestion_date',
        '_source_file',
        '_source_system'
    ]
    
    def validate(self, code: str, file_path: Path) -> List[ValidationResult]:
        results = []
        
        # Syntax check
        results.append(self.validate_python_syntax(code))
        
        # PySpark specific checks
        results.append(self.check_spark_session(code))
        results.append(self.check_delta_format(code))
        results.append(self.check_metadata_columns(code))
        results.append(self.check_error_handling(code))
        results.append(self.check_logging(code))
        
        return results
    
    def check_spark_session(self, code: str) -> ValidationResult:
        """Check if SparkSession is imported and created"""
        has_import = 'SparkSession' in code
        has_builder = 'SparkSession.builder' in code
        
        if has_import and has_builder:
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="spark_session",
                passed=True,
                message="SparkSession properly configured"
            )
        else:
            return ValidationResult(
                level=ValidationLevel.ERROR,
                check_name="spark_session",
                passed=False,
                message="Missing SparkSession import or builder"
            )
    
    def check_delta_format(self, code: str) -> ValidationResult:
        """Check if Delta Lake format is used"""
        if 'format("delta")' in code or "format('delta')" in code:
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="delta_format",
                passed=True,
                message="Using Delta Lake format"
            )
        else:
            return ValidationResult(
                level=ValidationLevel.WARNING,
                check_name="delta_format",
                passed=False,
                message="Not using Delta Lake format (may be intentional)"
            )
    
    def check_metadata_columns(self, code: str) -> ValidationResult:
        """Check if all required metadata columns are present"""
        missing = [col for col in self.REQUIRED_METADATA_COLUMNS if col not in code]
        
        if not missing:
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="metadata_columns",
                passed=True,
                message=f"All {len(self.REQUIRED_METADATA_COLUMNS)} metadata columns present"
            )
        else:
            return ValidationResult(
                level=ValidationLevel.ERROR,
                check_name="metadata_columns",
                passed=False,
                message=f"Missing metadata columns: {', '.join(missing)}"
            )
    
    def check_error_handling(self, code: str) -> ValidationResult:
        """Check if proper error handling is implemented"""
        has_try = 'try:' in code
        has_except = 'except' in code
        
        if has_try and has_except:
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="error_handling",
                passed=True,
                message="Error handling present"
            )
        else:
            return ValidationResult(
                level=ValidationLevel.WARNING,
                check_name="error_handling",
                passed=False,
                message="No error handling detected"
            )
    
    def check_logging(self, code: str) -> ValidationResult:
        """Check if logging is implemented"""
        has_logging = 'logger' in code or 'logging' in code or 'print(' in code
        
        if has_logging:
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="logging",
                passed=True,
                message="Logging statements found"
            )
        else:
            return ValidationResult(
                level=ValidationLevel.WARNING,
                check_name="logging",
                passed=False,
                message="No logging statements found"
            )


class SnowflakeValidator(CodeValidator):
    """Validator for Snowflake code"""
    
    def validate(self, code: str, file_path: Path) -> List[ValidationResult]:
        results = []
        
        # Syntax check
        results.append(self.validate_python_syntax(code))
        
        # Snowflake specific checks
        results.append(self.check_snowpark(code))
        
        return results
    
    def check_snowpark(self, code: str) -> ValidationResult:
        """Check if Snowpark imports are present"""
        if 'snowflake.snowpark' in code:
            return ValidationResult(
                level=ValidationLevel.INFO,
                check_name="snowpark",
                passed=True,
                message="Snowpark imports present"
            )
        else:
            return ValidationResult(
                level=ValidationLevel.WARNING,
                check_name="snowpark",
                passed=False,
                message="No Snowpark imports detected"
            )


def get_validator(file_path: Path) -> CodeValidator:
    """
    Determine appropriate validator based on file content or path
    
    Returns:
        Appropriate validator instance
    """
    # Try to detect from path
    path_str = str(file_path).lower()
    
    if 'pyspark' in path_str or 'databricks' in path_str:
        return PySparkValidator()
    elif 'snowflake' in path_str:
        return SnowflakeValidator()
    
    # Try to detect from content
    try:
        code = file_path.read_text(encoding='utf-8')
        
        if 'SparkSession' in code or 'pyspark' in code:
            return PySparkValidator()
        elif 'snowflake.snowpark' in code:
            return SnowflakeValidator()
    except:
        pass
    
    # Default to base validator
    return CodeValidator()


def validate_file(file_path: Path) -> Tuple[List[ValidationResult], bool]:
    """
    Validate a single Python file
    
    Returns:
        Tuple of (validation results, all_passed)
    """
    try:
        code = file_path.read_text(encoding='utf-8')
    except Exception as e:
        return [
            ValidationResult(
                level=ValidationLevel.ERROR,
                check_name="read_file",
                passed=False,
                message=f"Failed to read file: {e}"
            )
        ], False
    
    validator = get_validator(file_path)
    results = validator.validate(code, file_path)
    
    # All passed if no errors
    all_passed = all(
        r.passed or r.level == ValidationLevel.WARNING 
        for r in results
    )
    
    return results, all_passed


def validate_directory(dir_path: Path) -> Dict[str, Tuple[List[ValidationResult], bool]]:
    """
    Validate all Python files in a directory
    
    Returns:
        Dict mapping file paths to validation results
    """
    results = {}
    
    for py_file in dir_path.rglob("*.py"):
        # Skip __init__.py and test files
        if py_file.name == "__init__.py" or py_file.name.startswith("test_"):
            continue
        
        file_results, passed = validate_file(py_file)
        results[str(py_file)] = (file_results, passed)
    
    return results


def print_results(file_path: str, results: List[ValidationResult], passed: bool):
    """Print validation results for a file"""
    # Status icon
    status = "✅" if passed else "❌"
    
    print(f"\n{status} {Path(file_path).name}")
    print("─" * 70)
    
    for result in results:
        # Icon based on level and pass/fail
        if result.passed:
            icon = "✅"
        elif result.level == ValidationLevel.ERROR:
            icon = "❌"
        elif result.level == ValidationLevel.WARNING:
            icon = "⚠️ "
        else:
            icon = "ℹ️ "
        
        print(f"  {icon} {result.check_name}: {result.message}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("\nError: No path provided")
        print("Usage: python scripts/validate_generated_code.py <path>")
        sys.exit(1)
    
    target = Path(sys.argv[1])
    
    if not target.exists():
        print(f"❌ Path not found: {target}")
        sys.exit(1)
    
    print("🔍 Validating Generated Code\n")
    
    if target.is_file():
        # Validate single file
        results, passed = validate_file(target)
        print_results(str(target), results, passed)
        
        sys.exit(0 if passed else 1)
    
    elif target.is_dir():
        # Validate directory
        all_results = validate_directory(target)
        
        if not all_results:
            print("⚠️  No Python files found to validate")
            sys.exit(0)
        
        # Print results for each file
        for file_path, (results, passed) in all_results.items():
            print_results(file_path, results, passed)
        
        # Summary
        total = len(all_results)
        passed_count = sum(1 for _, (_, p) in all_results.items() if p)
        failed_count = total - passed_count
        
        print("\n" + "=" * 70)
        print(f"📊 Summary: {passed_count}/{total} files passed")
        
        if failed_count > 0:
            print(f"   ❌ {failed_count} files have errors")
            sys.exit(1)
        else:
            print("   ✅ All validations passed!")
            sys.exit(0)
    
    else:
        print(f"❌ Invalid path: {target}")
        sys.exit(1)


if __name__ == "__main__":
    main()
