-- Example MERGE SQL pattern generated by the transpiler (one representative example for DimProduct)
-- Replace the table names as needed. This SQL is executed from the pyspark_code via spark.sql().

MERGE INTO gold.dim_product AS tgt
USING (SELECT * FROM tmp_dimproduct_XXXXXXXX) AS src
ON src.productid = tgt.productid
WHEN MATCHED THEN
  UPDATE SET tgt.sk_product=src.sk_product, tgt.productid=src.productid, tgt.productname=src.productname, tgt.supplierid=src.supplierid, tgt.categoryid=src.categoryid, tgt.unitprice=src.unitprice, tgt.discontinued=src.discontinued, tgt.effective_from=src.effective_from, tgt.effective_to=src.effective_to, tgt.is_current=src.is_current
WHEN NOT MATCHED THEN
  INSERT (sk_product, productid, productname, supplierid, categoryid, unitprice, discontinued, effective_from, effective_to, is_current)
  VALUES (src.sk_product, src.productid, src.productname, src.supplierid, src.categoryid, src.unitprice, src.discontinued, src.effective_from, src.effective_to, src.is_current)
WHEN NOT MATCHED BY SOURCE AND tgt.productid IS NOT NULL THEN
  DELETE;
