/*
ANSI MERGE examples generated by transpiler (illustrative). Use the PySpark driver above for executions.
*/

-- Merge for SCD2 (DimProduct)
MERGE INTO gold.dim_product tgt
USING (SELECT sk, productid, productname, supplierid, categoryid, unitprice, discontinued, start_date, end_date, is_current FROM __stg_new_dim_product) src
ON tgt.productid = src.productid AND tgt.is_current = true
WHEN MATCHED THEN
  UPDATE SET tgt.end_date = src.start_date, tgt.is_current = false
WHEN NOT MATCHED THEN
  INSERT (sk, productid, productname, supplierid, categoryid, unitprice, discontinued, start_date, end_date, is_current)
  VALUES (src.sk, src.productid, src.productname, src.supplierid, src.categoryid, src.unitprice, src.discontinued, src.start_date, src.end_date, src.is_current);

-- Merge for FactSales (idempotent by business key orderid + product_sk)
MERGE INTO gold.fact_sales tgt
USING (SELECT orderid, product_sk, cust_sk, emp_sk, shipper_sk, qty, unitprice, discount, amount, etl_loaded_at FROM __stg_fact_sales) src
ON tgt.orderid = src.orderid AND tgt.product_sk = src.product_sk
WHEN MATCHED THEN
  UPDATE SET
    tgt.qty = src.qty,
    tgt.unitprice = src.unitprice,
    tgt.discount = src.discount,
    tgt.amount = src.amount,
    tgt.etl_loaded_at = src.etl_loaded_at
WHEN NOT MATCHED THEN
  INSERT (orderid, product_sk, cust_sk, emp_sk, shipper_sk, qty, unitprice, discount, amount, etl_loaded_at)
  VALUES (src.orderid, src.product_sk, src.cust_sk, src.emp_sk, src.shipper_sk, src.qty, src.unitprice, src.discount, src.amount, src.etl_loaded_at);
