"use client";

import React, { useState } from 'react';
import {
    Package,
    Settings2,
    FileText,
    ExternalLink,
    CheckCircle2,
    ArrowRight,
    Zap,
    Box,
    Terminal,
    Globe,
    HardDrive,
    Trash2,
    Plus,
    Download,
    Eye,
    Database,
    Github,
    GitBranch,
    KeyRound,
    FolderGit2,
    Loader2,
    CheckCheck,
    AlertTriangle
} from 'lucide-react';
import StageHeader from '../StageHeader';

import { fetchWithAuth } from '../../lib/auth-client';
import { API_BASE_URL } from '../../lib/config';
import ExecutiveSummaryPanel from '../ExecutiveSummaryPanel';

interface Variable {
    key: string;
    value: string;
    description: string;
}

interface GitHubConfig {
    repoUrl: string;
    token: string;
    branch: string;
    targetPath: string;
    commitMessage: string;
    createPr: boolean;
}

interface HandoverViewProps {
    projectId: string;
    projectName?: string;
    onStageChange: (stage: number) => void;
    isFullscreen?: boolean;
    onToggleFullscreen?: () => void;
    onReset?: () => void;
    onBackToCurrent?: () => void;
    activeSection?: string;
    onSectionChange?: (section: string) => void;
}

export default function HandoverView({
    projectId,
    projectName,
    onStageChange,
    isFullscreen,
    onToggleFullscreen,
    onReset,
    onBackToCurrent,
    activeSection,
    onSectionChange
}: HandoverViewProps) {
    const [variables, setVariables] = useState<Variable[]>([
        { key: "ENV", value: "prod", description: "Environment tag for naming" },
        { key: "ROOT_PATH", value: "/mnt/data/modernized", description: "Base path for Lakehouse tables" },
        { key: "CATALOG", value: "main", description: "Unity Catalog destination" }
    ]);
    const [selectedCartridge, setSelectedCartridge] = useState<'dbc' | 'sql' | 'yaml'>('dbc');
    const [isExporting, setIsExporting] = useState(false);
    const [showRunbook, setShowRunbook] = useState(false);
    const [project, setProject] = useState<any>(null);
    const [fileStats, setFileStats] = useState({ total: 0, artifacts: 0 });

    // GitHub push state
    const [githubConfig, setGithubConfig] = useState<GitHubConfig>({
        repoUrl: '',
        token: '',
        branch: 'legacy2lake-migration',
        targetPath: 'modernized/',
        commitMessage: 'Legacy2Lake: Add modernized migration code',
        createPr: true,
    });
    const [isPushing, setIsPushing] = useState(false);
    const [pushResult, setPushResult] = useState<{ success: boolean; branch?: string; branch_url?: string; pr_url?: string; files_pushed?: number; error?: string } | null>(null);
    const [showGitHub, setShowGitHub] = useState(false);
    const showOverview = !activeSection || activeSection === 'overview' || activeSection === 'handover-pkg';

    const updateGitHub = (key: keyof GitHubConfig, val: string | boolean) =>
        setGithubConfig(prev => ({ ...prev, [key]: val }));

    const handleGitHubPush = async () => {
        if (!githubConfig.repoUrl || !githubConfig.token) {
            alert('Repository URL and Personal Access Token are required.');
            return;
        }
        setIsPushing(true);
        setPushResult(null);
        try {
            const res = await fetchWithAuth(`/projects/${projectId}/github/push`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    repo_url: githubConfig.repoUrl,
                    token: githubConfig.token,
                    branch: githubConfig.branch,
                    target_path: githubConfig.targetPath,
                    commit_message: githubConfig.commitMessage,
                    create_pr: githubConfig.createPr,
                    pr_title: `[Legacy2Lake] ${projectName || projectId} Modernization`,
                    pr_body: `Automated migration artifacts generated by Legacy2Lake UTM v4.0 for project **${projectName || projectId}**.`,
                }),
            });
            const data = await res.json();
            if (!res.ok) throw new Error(data.detail || 'Push failed');
            setPushResult(data);
        } catch (err) {
            setPushResult({ success: false, error: err instanceof Error ? err.message : String(err) });
        } finally {
            setIsPushing(false);
        }
    };

    React.useEffect(() => {
        fetchWithAuth(`/projects/${projectId}`)
            .then(res => res.json())
            .then(data => {
                setProject(data);
                // Dynamically update default variables based on destination
                if (data.target_tech && data.target_tech.toLowerCase().includes('snowflake')) {
                    setVariables(prev => prev.map(v =>
                        v.key === 'CATALOG' ? { ...v, description: 'Snowflake Database destination' } : v
                    ));
                    setSelectedCartridge('sql');
                } else if (data.target_tech && data.target_tech.toLowerCase().includes('databricks')) {
                    setSelectedCartridge('dbc');
                }
            })
            .catch(err => console.error("Failed to fetch project details:", err));

        // Fetch file stats
        fetchWithAuth(`/projects/${projectId}/files`)
            .then(res => res.json())
            .then(data => {
                let total = 0;
                let artifacts = 0;
                const count = (nodes: any[]) => {
                    nodes.forEach(n => {
                        if (n.type === 'file') {
                            total++;
                            if (n.name.endsWith('.py') || n.name.endsWith('.sql') || n.name.endsWith('.dbc')) artifacts++;
                        }
                        if (n.children) count(n.children);
                    });
                };
                if (data.children) count(data.children);
                setFileStats({ total, artifacts });
            })
            .catch(err => console.error("Failed to fetch file stats:", err));
    }, [projectId]);

    const addVariable = () => {
        setVariables([...variables, { key: "", value: "", description: "" }]);
    };

    const updateVariable = (idx: number, field: keyof Variable, val: string) => {
        const newVars = [...variables];
        newVars[idx][field] = val;
        setVariables(newVars);
    };

    const removeVariable = (idx: number) => {
        setVariables(variables.filter((_, i) => i !== idx));
    };

    const handleExport = async (type: 'delivery' | 'governance') => {
        setIsExporting(true);
        try {
            const exportUrl = `/projects/${projectId}/export/${type}`;

            // Use fetchWithAuth to include authentication headers
            const response = await fetchWithAuth(exportUrl);

            if (!response.ok) {
                let errorMsg = 'Failed to generate export bundle';
                try {
                    const errorData = await response.json();
                    errorMsg = errorData.detail || errorData.message || errorMsg;
                } catch (e) {
                    // Ignore JSON parse error
                }
                throw new Error(errorMsg);
            }

            // Get filename from Content-Disposition header
            const contentDisposition = response.headers.get('Content-Disposition');
            let filename = type === 'delivery'
                ? (projectName ? `Legacy2Lake_Delivery_${projectName}.zip` : "Legacy2Lake_Delivery.zip")
                : (projectName ? `Legacy2Lake_Solution_${projectName}.zip` : "Legacy2Lake_Solution.zip");

            if (contentDisposition) {
                const filenameMatch = contentDisposition.match(/filename="?([^"]+)"?/);
                if (filenameMatch && filenameMatch[1]) {
                    filename = filenameMatch[1];
                }
            }

            // Convert to blob and trigger download
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.style.display = 'none';
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);

            alert(`${type === 'delivery' ? 'Delivery' : 'Governance'} Bundle downloaded successfully!`);
        } catch (error) {
            console.error("Export failed:", error);
            alert(`Failed to export: ${error instanceof Error ? error.message : 'Unknown error'}`);
        } finally {
            setIsExporting(false);
        }
    };

    // Listen for sidebar triggers
    React.useEffect(() => {
        if (activeSection === 'export-delivery') {
            if (!isExporting) {
                handleExport('delivery');
            }
            if (onSectionChange) onSectionChange('handover-pkg');
        } else if (activeSection === 'export-full') {
            if (!isExporting) {
                handleExport('governance');
            }
            if (onSectionChange) onSectionChange('handover-pkg');
        }
    }, [activeSection, onSectionChange]);

    return (
        <div className="flex flex-col h-full bg-[#050505]">
            <StageHeader
                title="Stage 5: Intelligent Handover"
                subtitle="Package the final outputs and prepare the handoff to the receiving team or environment"
                icon={<Package className="text-emerald-500" />}
                helpText="Use Handover to review package readiness, export delivery bundles, and complete the final transfer of project artifacts."
                onApprove={() => handleExport('governance')}
                approveLabel={isExporting ? "Exporting..." : "Complete Migration"}
                isApproveDisabled={isExporting}
                isFullscreen={isFullscreen}
                onToggleFullscreen={onToggleFullscreen}
                onReset={onReset}
                onBackToCurrent={onBackToCurrent}
            />

            <div className="flex-1 overflow-y-auto p-8 max-w-7xl mx-auto w-full custom-scrollbar">

                {showRunbook ? (
                    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                        <div className="bg-black/40 border border-white/5 rounded-3xl p-8 font-mono text-sm text-gray-300 leading-relaxed shadow-2xl">
                            <h2 className="text-white text-lg font-black uppercase tracking-widest mb-6 border-b border-white/5 pb-4"># Modernization Runbook: {projectId}</h2>
                            <p className="mb-4">Generated on: {new Date().toLocaleDateString()}</p>
                            <h3 className="text-emerald-500 font-bold mb-4 mt-8">## 1. Environment Injection Summary</h3>
                            <ul className="space-y-2 mb-8">
                                {variables.map((v, i) => (
                                    <li key={i} className="flex gap-4">
                                        <span className="text-gray-500">[{v.key}]</span>
                                        <span className="text-white">{v.value}</span>
                                        <span className="text-gray-600 italic">// {v.description}</span>
                                    </li>
                                ))}
                            </ul>
                            <h3 className="text-emerald-500 font-bold mb-4">## 2. Deployment Instructions</h3>
                            <p>1. Unzip the bundle into your root artifact workspace.</p>
                            <p>2. Configure the <code>{"${ROOT_PATH}"}</code> to point to your ADLS/S3 bucket.</p>
                            <p>3. Execute the <code>modernization_catalyst.py</code> entry point.</p>

                            <div className="mt-12 p-6 bg-white/5 rounded-2xl border border-white/5 text-center">
                                <FileText size={48} className="mx-auto text-white/20 mb-4" />
                                <p className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-500">End of Documentation</p>
                            </div>
                        </div>
                    </div>
                ) : (showOverview && <>
                    <div className="grid grid-cols-12 gap-8">

                        {/* Left: Variable Grid */}
                        <div className="col-span-12 lg:col-span-8 space-y-6">
                            <div className="bg-black/40 border border-white/5 rounded-3xl p-8 shadow-2xl">
                                <div className="flex items-center justify-between mb-8">
                                    <div className="flex items-center gap-3">
                                        <div className="p-2.5 bg-emerald-500/10 rounded-2xl text-emerald-500 border border-emerald-500/20">
                                            <Settings2 size={20} />
                                        </div>
                                        <div>
                                            <h3 className="text-sm font-black text-white uppercase tracking-wider">Environment Variable Injection</h3>
                                            <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest mt-1">Global logic overrides</p>
                                        </div>
                                    </div>
                                    <button
                                        onClick={addVariable}
                                        className="p-2.5 bg-white/5 hover:bg-white/10 rounded-2xl text-gray-400 hover:text-white active:scale-95 transition-all border border-white/5"
                                    >
                                        <Plus size={20} />
                                    </button>
                                </div>

                                <div className="space-y-4">
                                    {variables.map((v, idx) => (
                                        <div key={idx} className="grid grid-cols-12 gap-4 items-center group animate-in slide-in-from-left duration-300" style={{ animationDelay: `${idx * 50}ms` }}>
                                            <div className="col-span-3">
                                                <input
                                                    className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs font-bold text-emerald-400 placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-emerald-500/50"
                                                    placeholder="VARIABLE_KEY"
                                                    value={v.key}
                                                    onChange={e => updateVariable(idx, 'key', e.target.value.toUpperCase())}
                                                />
                                            </div>
                                            <div className="col-span-3">
                                                <input
                                                    className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-white placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-emerald-500/50"
                                                    placeholder="Value"
                                                    value={v.value}
                                                    onChange={e => updateVariable(idx, 'value', e.target.value)}
                                                />
                                            </div>
                                            <div className="col-span-5">
                                                <input
                                                    className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-gray-400 placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-emerald-500/50"
                                                    placeholder="Description..."
                                                    value={v.description}
                                                    onChange={e => updateVariable(idx, 'description', e.target.value)}
                                                />
                                            </div>
                                            <div className="col-span-1 flex justify-end">
                                                <button onClick={() => removeVariable(idx)} className="p-2.5 text-gray-600 hover:text-red-500 hover:bg-red-500/10 rounded-xl transition-all opacity-0 group-hover:opacity-100">
                                                    <Trash2 size={16} />
                                                </button>
                                            </div>
                                        </div>
                                    ))}
                                    {variables.length === 0 && (
                                        <div className="py-12 text-center border-2 border-dashed border-white/5 rounded-2xl opacity-30">
                                            <p className="text-[10px] font-black uppercase tracking-widest">No variables defined. Using defaults.</p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>

                        {/* Right: Cartridge & Summary */}
                        <div className="col-span-12 lg:col-span-4 space-y-6">

                            {/* Sprint 2: Executive Summary */}
                            <div className="bg-black/40 border border-white/5 rounded-3xl p-6 shadow-2xl">
                                <ExecutiveSummaryPanel projectId={projectId} variant="compact" />
                            </div>

                            {/* Bundle Type */}
                            <div className="bg-black/40 border border-white/5 rounded-3xl p-8 shadow-2xl">
                                <h3 className="text-xs font-black text-white uppercase tracking-widest mb-6">Execution Cartridge</h3>
                                <div className="space-y-3">
                                    {(!project?.target_tech || project.target_tech.toLowerCase().includes('databricks') || project.target_tech.toLowerCase().includes('pyspark')) && (
                                        <CartridgeOption
                                            active={selectedCartridge === 'dbc'}
                                            onClick={() => setSelectedCartridge('dbc')}
                                            title={`${project?.target_tech || 'Databricks'} Archive`}
                                            ext=".dbc"
                                            icon={<Globe size={18} />}
                                        />
                                    )}
                                    {(!project?.target_tech || project.target_tech.toLowerCase().includes('snowflake') || project.target_tech.toLowerCase().includes('sql')) && (
                                        <CartridgeOption
                                            active={selectedCartridge === 'sql'}
                                            onClick={() => setSelectedCartridge('sql')}
                                            title={`${project?.target_tech || 'Snowflake'} Script`}
                                            ext=".sql"
                                            icon={<Database size={18} />}
                                        />
                                    )}
                                    <CartridgeOption
                                        active={selectedCartridge === 'yaml'}
                                        onClick={() => setSelectedCartridge('yaml')}
                                        title="Orchestration Pipeline"
                                        ext=".yaml"
                                        icon={<HardDrive size={18} />}
                                    />
                                </div>
                            </div>

                            {/* Summary Card */}
                            <div className="bg-gradient-to-br from-emerald-600 to-emerald-900 rounded-3xl p-8 text-white relative overflow-hidden group hover:scale-[1.02] transition-all">
                                <Box className="absolute -right-4 -bottom-4 w-32 h-32 text-white/10 group-hover:rotate-12 transition-transform" />
                                <h3 className="text-xs font-black uppercase tracking-[0.2em] mb-2 opacity-60">Ready for Handover</h3>
                                <div className="text-3xl font-black mb-6">Final Bundle</div>
                                <div className="space-y-3">
                                    <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest">
                                        <CheckCircle2 size={12} className="text-emerald-300" /> {fileStats.artifacts > 0 ? `${fileStats.artifacts} Optimized Artifacts` : `Artifacts Generated`}
                                    </div>
                                    <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest">
                                        <CheckCircle2 size={12} className="text-emerald-300" /> Compliance Certificate Included
                                    </div>
                                    <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest">
                                        <CheckCircle2 size={12} className="text-emerald-300" /> {variables.length} Variable overrides detected
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    {/* ── GitHub Push Section ── */}
                    <div className="bg-black/40 border border-white/5 rounded-3xl p-8 shadow-2xl">
                        <div className="flex items-center justify-between mb-6">
                            <div className="flex items-center gap-3">
                                <div className="p-2.5 bg-violet-500/10 rounded-2xl text-violet-400 border border-violet-500/20">
                                    <Github size={20} />
                                </div>
                                <div>
                                    <h3 className="text-sm font-black text-white uppercase tracking-wider">Push to GitHub</h3>
                                    <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest mt-1">Send artifacts directly to your repository</p>
                                </div>
                            </div>
                            <button
                                onClick={() => setShowGitHub(!showGitHub)}
                                className="px-4 py-2 text-[10px] font-black uppercase tracking-widest bg-white/5 hover:bg-violet-500/10 border border-white/10 hover:border-violet-500/30 text-gray-400 hover:text-violet-300 rounded-xl transition-all active:scale-95"
                            >
                                {showGitHub ? 'Hide' : 'Configure'}
                            </button>
                        </div>

                        {showGitHub && (
                            <div className="space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">

                                {/* Repo URL */}
                                <div className="grid grid-cols-12 gap-4">
                                    <div className="col-span-8">
                                        <label className="block text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2 flex items-center gap-1.5">
                                            <FolderGit2 size={11} /> Repository URL
                                        </label>
                                        <input
                                            type="url"
                                            placeholder="https://github.com/org/repo"
                                            value={githubConfig.repoUrl}
                                            onChange={e => updateGitHub('repoUrl', e.target.value)}
                                            className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-white placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-violet-500/50"
                                        />
                                    </div>
                                    <div className="col-span-4">
                                        <label className="block text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2 flex items-center gap-1.5">
                                            <GitBranch size={11} /> Branch
                                        </label>
                                        <input
                                            type="text"
                                            placeholder="legacy2lake-migration"
                                            value={githubConfig.branch}
                                            onChange={e => updateGitHub('branch', e.target.value)}
                                            className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-white placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-violet-500/50"
                                        />
                                    </div>
                                </div>

                                {/* PAT + Target Path */}
                                <div className="grid grid-cols-12 gap-4">
                                    <div className="col-span-8">
                                        <label className="block text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2 flex items-center gap-1.5">
                                            <KeyRound size={11} /> Personal Access Token
                                        </label>
                                        <input
                                            type="password"
                                            placeholder="ghp_••••••••••••••••••••••••••••••"
                                            value={githubConfig.token}
                                            onChange={e => updateGitHub('token', e.target.value)}
                                            className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-white placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-violet-500/50"
                                        />
                                    </div>
                                    <div className="col-span-4">
                                        <label className="block text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2">Target Path</label>
                                        <input
                                            type="text"
                                            placeholder="modernized/"
                                            value={githubConfig.targetPath}
                                            onChange={e => updateGitHub('targetPath', e.target.value)}
                                            className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-white placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-violet-500/50"
                                        />
                                    </div>
                                </div>

                                {/* Commit Message */}
                                <div>
                                    <label className="block text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2">Commit Message</label>
                                    <input
                                        type="text"
                                        placeholder="feat: Legacy2Lake migration artifacts"
                                        value={githubConfig.commitMessage}
                                        onChange={e => updateGitHub('commitMessage', e.target.value)}
                                        className="w-full bg-white/5 border border-white/5 rounded-xl px-4 py-3 text-xs text-white placeholder:text-gray-700 outline-none focus:ring-1 focus:ring-violet-500/50"
                                    />
                                </div>

                                {/* Create PR toggle */}
                                <div className="flex items-center justify-between p-4 bg-white/5 rounded-2xl border border-white/5">
                                    <div>
                                        <p className="text-xs font-black text-white uppercase tracking-wider">Open Pull Request</p>
                                        <p className="text-[10px] text-gray-500 mt-0.5">Automatically create a PR after pushing artifacts</p>
                                    </div>
                                    <button
                                        onClick={() => updateGitHub('createPr', !githubConfig.createPr)}
                                        className={`relative w-12 h-6 rounded-full transition-colors ${githubConfig.createPr ? 'bg-violet-500' : 'bg-white/10'}`}
                                    >
                                        <span className={`absolute top-1 w-4 h-4 rounded-full bg-white shadow transition-transform ${githubConfig.createPr ? 'translate-x-7' : 'translate-x-1'}`} />
                                    </button>
                                </div>

                                {/* Push Button + Result */}
                                <div className="pt-2">
                                    <button
                                        onClick={handleGitHubPush}
                                        disabled={isPushing || !githubConfig.repoUrl || !githubConfig.token}
                                        className="w-full py-4 rounded-2xl font-black text-xs uppercase tracking-widest transition-all active:scale-[0.98] flex items-center justify-center gap-2
                                            disabled:opacity-40 disabled:cursor-not-allowed
                                            bg-violet-600 hover:bg-violet-500 text-white shadow-lg shadow-violet-500/20 hover:shadow-violet-500/40 border border-violet-500/30"
                                    >
                                        {isPushing ? (
                                            <><Loader2 size={14} className="animate-spin" /> Pushing Artifacts...</>
                                        ) : (
                                            <><Github size={14} /> Push to GitHub</>
                                        )}
                                    </button>
                                </div>

                                {/* Result panel */}
                                {pushResult && (
                                    <div className={`p-5 rounded-2xl border animate-in fade-in duration-300 ${pushResult.success ? 'bg-emerald-500/5 border-emerald-500/20' : 'bg-red-500/5 border-red-500/20'}`}>
                                        {pushResult.success ? (
                                            <div className="space-y-3">
                                                <div className="flex items-center gap-2">
                                                    <CheckCheck size={16} className="text-emerald-400 shrink-0" />
                                                    <span className="text-xs font-black text-emerald-400 uppercase tracking-wider">Push successful — {pushResult.files_pushed} files</span>
                                                </div>
                                                {pushResult.branch_url && (
                                                    <a href={pushResult.branch_url} target="_blank" rel="noopener noreferrer"
                                                        className="flex items-center gap-2 text-[10px] text-violet-400 hover:text-violet-300 underline underline-offset-2 transition-colors">
                                                        <GitBranch size={11} /> {pushResult.branch_url}
                                                    </a>
                                                )}
                                                {pushResult.pr_url && (
                                                    <a href={pushResult.pr_url} target="_blank" rel="noopener noreferrer"
                                                        className="flex items-center gap-2 text-[10px] text-violet-400 hover:text-violet-300 underline underline-offset-2 transition-colors">
                                                        <Github size={11} /> Pull Request opened
                                                    </a>
                                                )}
                                                {pushResult.file_list && pushResult.file_list.length > 0 && (
                                                    <div className="mt-3 pt-3 border-t border-white/5">
                                                        <p className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-2">Files pushed:</p>
                                                        <div className="space-y-1 max-h-32 overflow-y-auto custom-scrollbar">
                                                            {pushResult.file_list.map((f: string, i: number) => (
                                                                <p key={i} className="text-[10px] text-gray-500 font-mono truncate">{f}</p>
                                                            ))}
                                                        </div>
                                                    </div>
                                                )}
                                            </div>
                                        ) : (
                                            <div className="flex items-start gap-2">
                                                <AlertTriangle size={16} className="text-red-400 shrink-0 mt-0.5" />
                                                <div>
                                                    <p className="text-xs font-black text-red-400 uppercase tracking-wider">Push failed</p>
                                                    <p className="text-[10px] text-gray-500 mt-1">{pushResult.error || 'Unknown error'}</p>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                </>)}
            </div>
        </div>
    );
}

function CartridgeOption({ active, onClick, title, ext, icon }: any) {
    return (
        <button
            onClick={onClick}
            className={`w-full p-4 rounded-2xl border flex items-center justify-between transition-all ${active ? 'bg-emerald-600/10 border-emerald-500 shadow-lg shadow-emerald-500/10 active:scale-[0.98]' : 'bg-white/5 border-white/5 hover:border-white/10 opacity-60 hover:opacity-100 active:scale-95'}`}
        >
            <div className="flex items-center gap-4">
                <div className={`p-2.5 rounded-xl ${active ? 'bg-emerald-500 text-white' : 'bg-white/5 text-gray-500'}`}>
                    {icon}
                </div>
                <div className="text-left">
                    <div className={`text-xs font-black uppercase tracking-wider ${active ? 'text-white' : 'text-gray-400'}`}>{title}</div>
                    <div className="text-[9px] font-bold text-gray-500 uppercase tracking-widest">{ext} format</div>
                </div>
            </div>
            {active && <Zap size={14} className="text-emerald-500" />}
        </button>
    );
}
