# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
-- SILVER LAYER (Intermediate/Cleansed)
-- Generated by Shift-T Architect Agent
-- Reference: DimCategory_bronze

{{
  config(
    materialized='incremental',
    unique_key=['categoryid']
  )
}}

with bronze as (
    select * from {{ ref('DimCategory_bronze') }}
),

deduplicated as (
    -- Simple deduplication via distinct or window function
    select distinct * from bronze
)

select * from deduplicated

-- Incremental logic
{% if is_incremental() %}
  -- this filter will only be applied on an incremental run
  where _ingested_at > (select max(_ingested_at) from {{ this }})
{% endif %}
