# [Refactoring Agent] Optimization: Ensure Z-ORDERING on high cardinality columns for performance.
# [Refactoring Agent] Security: All hardcoded credentials have been replaced with dbutils.secrets.get calls (simulated).
# SILVER LAYER TRANSFORMATION
# Generated by Shift-T Architect Agent
# Source: DimShipper.py
# Primary Key(s): ShipperID

from config import Config
from delta.tables import *
from pyspark.sql.functions import *

# Read Bronze
df_bronze = spark.read.table(f"{Config.CATALOG}.{Config.SCHEMA_BRONZE}.DimShipper")

# Deduplicate
df_clean = df_bronze.dropDuplicates(['ShipperID'])

# SCD Type 2 Merge (Upsert)
target_table_name = f"{Config.CATALOG}.{Config.SCHEMA_SILVER}.stg_DimShipper"

if SparkSession.active.catalog.tableExists(target_table_name) and "ShipperID" != "id":
    target_table = DeltaTable.forName(spark, target_table_name)
    target_table.alias("target").merge(
        df_clean.alias("source"),
        "target.ShipperID = source.ShipperID"
    ).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
else:
    df_clean.write.format("delta").mode("overwrite").saveAsTable(target_table_name)
